# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('budget_change', 'Budget Change'), ('creative_approval', 'Creative Approval'), ('kpi_update', 'KPI Update'), ('targeting_change', 'Targeting Change'), ('other', 'Other')], help_text='Type of client communication (e.g. budget change, creative approval)', max_length=50)),
                ('stakeholders', models.TextField(blank=True, help_text='Stakeholders involved in this communication. Can include client contacts and internal team members.')),
                ('impacted_areas', models.JSONField(default=list, help_text="List of impacted campaign areas, e.g. ['budget', 'creative', 'kpi', 'targeting']")),
                ('required_actions', models.TextField(help_text='Required follow-up actions derived from this communication.')),
                ('client_deadline', models.DateField(blank=True, help_text='Client-requested deadline for completing the required actions.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional additional notes about the communication.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'client_communication',
                'ordering': ['-created_at'],
            },
        ),
    ]
