# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client_communication', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcommunication',
            name='task',
            field=models.ForeignKey(help_text='Associated workflow task capturing this communication', on_delete=django.db.models.deletion.CASCADE, related_name='client_communications', to='task.task'),
        ),
    ]
