openapi: 3.0.3
info:
  title: Platform Policy Update API
  version: 1.0.0
  description: |
    API for managing Platform Policy Update tasks.
    A Platform Policy Update is a domain payload bound 1:1 to a Task
    with type = "platform_policy_update".

servers:
  - url: /api/policy/

tags:
  - name: PlatformPolicyUpdate
    description: Platform policy update domain APIs

paths:
  /platform-policy-updates/:
    get:
      tags: [PlatformPolicyUpdate]
      summary: List platform policy updates
      description: |
        List platform policy updates.
        Can be filtered by task_id.
      security:
        - bearerAuth: []
      parameters:
        - name: task_id
          in: query
          required: false
          schema:
            type: integer
          description: Filter by associated Task ID
        - name: platform
          in: query
          required: false
          schema:
            type: string
          description: Filter by platform (e.g. meta, google_ads)
        - name: mitigation_status
          in: query
          required: false
          schema:
            type: string
          description: Filter by mitigation status (e.g. not_started, completed)
        - name: policy_change_type
          in: query
          required: false
          schema:
            type: string
          description: Filter by policy change type (e.g. targeting_rules)
        - name: assigned_to_id
          in: query
          required: false
          schema:
            type: integer
          description: Filter by assigned user ID
      responses:
        "200":
          description: Paginated list of platform policy updates
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                    nullable: true
                  previous:
                    type: string
                    format: uri
                    nullable: true
                  results:
                    type: array
                    items:
                      $ref: "#/components/schemas/PlatformPolicyUpdate"
        "401":
          description: Authentication required
        "403":
          description: Permission denied

    post:
      tags: [PlatformPolicyUpdate]
      summary: Create a platform policy update
      description: |
        Create a PlatformPolicyUpdate payload and bind it to an existing Task.
        The referenced Task must have type = "platform_policy_update".
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlatformPolicyUpdateCreate"
      responses:
        "201":
          description: Platform policy update created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformPolicyUpdate"
        "400":
          description: Validation error
        "401":
          description: Authentication required
        "403":
          description: Permission denied

  /platform-policy-updates/{id}/:
    get:
      tags: [PlatformPolicyUpdate]
      summary: Retrieve a platform policy update
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Platform policy update detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformPolicyUpdate"
        "401":
          description: Authentication required
        "403":
          description: Permission denied
        "404":
          description: Not found

    patch:
      tags: [PlatformPolicyUpdate]
      summary: Update a platform policy update
      description: |
        Partially update a platform policy update.
        Supports incremental updates during mitigation and review.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlatformPolicyUpdateUpdate"
      responses:
        "200":
          description: Updated platform policy update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformPolicyUpdate"
        "400":
          description: Validation error
        "401":
          description: Authentication required
        "403":
          description: Permission denied

    delete:
      tags: [PlatformPolicyUpdate]
      summary: Delete a platform policy update
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Deleted successfully
        "401":
          description: Authentication required
        "403":
          description: Permission denied
        "404":
          description: Not found

  /platform-policy-updates/{id}/mark-mitigation-completed/:
    post:
      tags: [PlatformPolicyUpdate]
      summary: Mark mitigation as completed
      description: |
        Set mitigation_status to "completed" and record the timestamp.
        Fails if mitigation is already completed or reviewed.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Mitigation marked as completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformPolicyUpdate"
        "400":
          description: Mitigation is already completed or reviewed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: Authentication required
        "403":
          description: Permission denied

  /platform-policy-updates/{id}/mark-reviewed/:
    post:
      tags: [PlatformPolicyUpdate]
      summary: Mark post-mitigation review as completed
      description: |
        Set mitigation_status to "reviewed" and record the reviewer (current user) and timestamp.
        Requires mitigation_status to be "completed" first.
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Review marked as completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PlatformPolicyUpdate"
        "400":
          description: Mitigation must be completed before review
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        "401":
          description: Authentication required
        "403":
          description: Permission denied

  /policy-choices/:
    get:
      tags: [PlatformPolicyUpdate]
      summary: Get enum choices for policy fields
      description: |
        Returns available choices for Platform, PolicyChangeType, and MitigationStatus.
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Enum choices
          content:
            application/json:
              schema:
                type: object
                properties:
                  platforms:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        label:
                          type: string
                  policy_change_types:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        label:
                          type: string
                  mitigation_statuses:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        label:
                          type: string
        "401":
          description: Authentication required
        "403":
          description: Permission denied

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:

    PlatformPolicyUpdate:
      type: object
      properties:
        id:
          type: integer
        task:
          type: object
          nullable: true
          description: Associated Task summary
          properties:
            id:
              type: integer
            summary:
              type: string
            status:
              type: string
            type:
              type: string

        platform:
          type: string
          enum:
            - meta
            - google_ads
            - tiktok
            - linkedin
            - twitter
            - snapchat
            - pinterest
            - other

        policy_change_type:
          type: string
          enum:
            - targeting_rules
            - content_policy
            - privacy_policy
            - ad_placement
            - budget_policy
            - compliance_requirement
            - data_usage
            - other

        policy_description:
          type: string

        policy_reference_url:
          type: string
          format: uri
          nullable: true

        effective_date:
          type: string
          format: date
          nullable: true

        affected_campaigns:
          type: array
          items:
            type: string

        affected_ad_sets:
          type: array
          items:
            type: string

        affected_assets:
          type: array
          items:
            type: string

        performance_impact:
          type: string

        budget_impact:
          type: string

        compliance_risk:
          type: string

        immediate_actions_required:
          type: string

        action_deadline:
          type: string
          format: date
          nullable: true

        mitigation_status:
          type: string
          enum:
            - not_started
            - planning
            - in_progress
            - completed
            - reviewed

        mitigation_plan:
          type: string

        mitigation_steps:
          type: array
          items:
            type: object
            properties:
              step:
                type: string
              status:
                type: string
                enum:
                  - pending
                  - in_progress
                  - completed
              assigned_to:
                type: integer
                nullable: true
              completed_at:
                type: string
                format: date-time
                nullable: true

        mitigation_execution_notes:
          type: string

        mitigation_completed_at:
          type: string
          format: date-time
          nullable: true

        mitigation_results:
          type: string

        post_mitigation_review:
          type: string

        review_completed_at:
          type: string
          format: date-time
          nullable: true

        reviewed_by:
          type: object
          nullable: true
          description: Reviewer user summary
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
              format: email

        all_impacts_addressed:
          type: boolean

        lessons_learned:
          type: string

        notes:
          type: string

        related_references:
          type: array
          items:
            type: string

        created_by:
          type: object
          nullable: true
          description: Creator user summary
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
              format: email

        assigned_to:
          type: object
          nullable: true
          description: Assigned user summary
          properties:
            id:
              type: integer
            username:
              type: string
            email:
              type: string
              format: email

        created_at:
          type: string
          format: date-time

        updated_at:
          type: string
          format: date-time

      required:
        - id
        - task
        - platform
        - policy_change_type
        - policy_description
        - immediate_actions_required
        - mitigation_status
        - created_at
        - updated_at

    PlatformPolicyUpdateCreate:
      type: object
      required:
        - platform
        - policy_change_type
        - policy_description
        - immediate_actions_required
      properties:
        task_id:
          type: integer
          nullable: true
          description: Associated Task ID (type must be platform_policy_update)
        platform:
          $ref: "#/components/schemas/PlatformPolicyUpdate/properties/platform"
        policy_change_type:
          $ref: "#/components/schemas/PlatformPolicyUpdate/properties/policy_change_type"
        policy_description:
          type: string
        policy_reference_url:
          type: string
          format: uri
        effective_date:
          type: string
          format: date
        affected_campaigns:
          type: array
          items:
            type: string
        affected_ad_sets:
          type: array
          items:
            type: string
        affected_assets:
          type: array
          items:
            type: string
        performance_impact:
          type: string
        budget_impact:
          type: string
        compliance_risk:
          type: string
        immediate_actions_required:
          type: string
        action_deadline:
          type: string
          format: date
        assigned_to_id:
          type: integer
          nullable: true
          description: Assigned user ID

    PlatformPolicyUpdateUpdate:
      type: object
      description: Partial update payload
      properties:
        policy_description:
          type: string
        policy_reference_url:
          type: string
          format: uri
        effective_date:
          type: string
          format: date
        affected_campaigns:
          type: array
          items:
            type: string
        affected_ad_sets:
          type: array
          items:
            type: string
        affected_assets:
          type: array
          items:
            type: string
        performance_impact:
          type: string
        budget_impact:
          type: string
        compliance_risk:
          type: string
        immediate_actions_required:
          type: string
        action_deadline:
          type: string
          format: date
        mitigation_status:
          type: string
        mitigation_plan:
          type: string
        mitigation_steps:
          type: array
          items:
            type: object
        mitigation_execution_notes:
          type: string
        mitigation_completed_at:
          type: string
          format: date-time
        mitigation_results:
          type: string
        post_mitigation_review:
          type: string
        review_completed_at:
          type: string
          format: date-time
        reviewed_by_id:
          type: integer
          nullable: true
        all_impacts_addressed:
          type: boolean
        lessons_learned:
          type: string
        notes:
          type: string
        related_references:
          type: array
          items:
            type: string
        assigned_to_id:
          type: integer
          nullable: true
