# Generated by Django 4.2.23 on 2026-01-21 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miro', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='board',
            new_name='miro_board_project_d10790_idx',
            old_name='miro_board_project_8a3f2d_idx',
        ),
        migrations.RenameIndex(
            model_name='board',
            new_name='miro_board_share_t_082161_idx',
            old_name='miro_board_share_t_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='boarditem',
            new_name='miro_boardi_board_i_89f0fd_idx',
            old_name='miro_boarditem_board_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='boarditem',
            new_name='miro_boardi_parent__23b4aa_idx',
            old_name='miro_boarditem_parent_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='boardrevision',
            new_name='miro_boardr_board_i_6e0b9a_idx',
            old_name='miro_boardrevision_board_abc123_idx',
        ),
    ]
