# Generated by Django 4.2.23 on 2026-02-18 09:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEscalationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=2, help_text='Escalation threshold amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('threshold_currency', models.CharField(help_text='Threshold currency code', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is active')),
            ],
            options={
                'verbose_name': 'Budget Escalation Rule',
                'verbose_name_plural': 'Budget Escalation Rules',
                'db_table': 'budget_escalation_rule',
            },
        ),
        migrations.CreateModel(
            name='BudgetPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total budget pool amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('used_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of budget used from this pool', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(help_text='Currency code (e.g., AUD, USD)', max_length=3)),
            ],
            options={
                'verbose_name': 'Budget Pool',
                'verbose_name_plural': 'Budget Pools',
                'db_table': 'budget_pool',
            },
        ),
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested budget amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(help_text='Currency code', max_length=3)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked')], default='DRAFT', help_text='Current status of the budget request', max_length=50, protected=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='Submission timestamp', null=True)),
                ('is_escalated', models.BooleanField(default=False, help_text='Whether the request has been escalated')),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
            ],
            options={
                'verbose_name': 'Budget Request',
                'verbose_name_plural': 'Budget Requests',
                'db_table': 'budget_request',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
