# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('budget_approval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetrequest',
            name='ad_channel',
            field=models.ForeignKey(help_text='Associated ad channel ID', on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='core.adchannel'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='budget_pool',
            field=models.ForeignKey(help_text='Associated budget pool', on_delete=django.db.models.deletion.PROTECT, related_name='budget_requests', to='budget_approval.budgetpool'),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='current_approver',
            field=models.ForeignKey(help_text='Current approver assigned to this request', on_delete=django.db.models.deletion.PROTECT, related_name='pending_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgetrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Requesting user', on_delete=django.db.models.deletion.CASCADE, related_name='created_budget_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
