# Generated by Django 4.2.23 on 2025-08-04 15:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Requested budget amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='budgetrequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='Submission timestamp', null=True),
        ),
    ]
