# Generated by Django 4.2.23 on 2025-08-18 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovalRecord',
        ),
    ]
