# Generated by Django 4.2.23 on 2025-08-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('budget_approval', '0002_delete_approvalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='task',
            field=models.ForeignKey(help_text='Associated task ID', on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='task.task'),
        ),
    ]
