# Generated by Django 4.2.23 on 2025-08-08 05:32

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0002_alter_budgetrequest_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetescalationrule',
            name='threshold_amount',
            field=models.DecimalField(decimal_places=2, help_text='Escalation threshold amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='budgetpool',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total budget pool amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='budgetpool',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount of budget used from this pool', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
