# Generated by Django 4.2.23 on 2025-08-19 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_object_id'),
        ('budget_approval', '0003_alter_budgetrequest_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetrequest',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Associated task ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='task.task'),
        ),
    ]
