# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Draft title', max_length=200, validators=[django.core.validators.MinLengthValidator(1)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current status of the draft', max_length=20)),
                ('content_blocks', models.JSONField(default=list, help_text='JSON array of content blocks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(help_text='Owner of this draft', on_delete=django.db.models.deletion.CASCADE, related_name='notion_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Plain Text'), ('rich_text', 'Rich Text'), ('heading', 'Heading'), ('list', 'List'), ('quote', 'Quote'), ('code', 'Code Block'), ('divider', 'Divider'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('web_bookmark', 'Web Bookmark')], default='text', help_text='Type of content block', max_length=20)),
                ('content', models.JSONField(default=dict, help_text='Block content and formatting')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the block in the draft')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(help_text='Parent draft', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='notion_editor.draft')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlockAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('preview', 'Preview'), ('save', 'Save'), ('delete', 'Delete'), ('edit', 'Edit'), ('duplicate', 'Duplicate'), ('move_up', 'Move Up'), ('move_down', 'Move Down')], help_text='Type of action', max_length=20)),
                ('label', models.CharField(help_text='Display label for the action button', max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name for the button', max_length=50)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this action is currently enabled')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the action button')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(help_text='Content block this action belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='notion_editor.contentblock')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded media file', max_length=500, upload_to='notion_editor/media/%Y/%m/%d/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], help_text='Type of media file', max_length=20)),
                ('original_filename', models.CharField(help_text='Original filename before upload', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('scan_status', models.CharField(choices=[('ready', 'Ready - File is safe and available'), ('infected', 'Infected - File contains virus/malware'), ('error_scanning', 'ErrorScanning - Scanner error occurred')], default='ready', help_text='Virus scan status of the file', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(blank=True, help_text='Draft this file belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='notion_editor.draft')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='notion_media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['media_type'], name='notion_edit_media_t_51db78_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='notion_edit_uploade_25f7a0_idx'), models.Index(fields=['draft'], name='notion_edit_draft_i_08c937_idx'), models.Index(fields=['scan_status'], name='notion_edit_scan_st_3bb96a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Draft title at this revision', max_length=200)),
                ('content_blocks', models.JSONField(default=list, help_text='Snapshot of content blocks at this revision')),
                ('status', models.CharField(help_text='Draft status at this revision', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1, help_text='Sequential revision number')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_revisions', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(help_text='Parent draft', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='notion_editor.draft')),
            ],
            options={
                'ordering': ['-created_at', '-revision_number'],
                'indexes': [models.Index(fields=['draft', '-created_at'], name='notion_edit_draft_i_c94b1e_idx'), models.Index(fields=['draft', 'revision_number'], name='notion_edit_draft_i_57bce0_idx')],
                'unique_together': {('draft', 'revision_number')},
            },
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['user', 'status'], name='notion_edit_user_id_e848e6_idx'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['created_at'], name='notion_edit_created_d90e97_idx'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['updated_at'], name='notion_edit_updated_3fc3c4_idx'),
        ),
        migrations.AddIndex(
            model_name='draft',
            index=models.Index(fields=['is_deleted'], name='notion_edit_is_dele_14ca5c_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['draft', 'order'], name='notion_edit_draft_i_53e7b2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentblock',
            index=models.Index(fields=['block_type'], name='notion_edit_block_t_4492dc_idx'),
        ),
        migrations.AddIndex(
            model_name='blockaction',
            index=models.Index(fields=['block', 'order'], name='notion_edit_block_i_90d206_idx'),
        ),
        migrations.AddIndex(
            model_name='blockaction',
            index=models.Index(fields=['action_type'], name='notion_edit_action__d23323_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='blockaction',
            unique_together={('block', 'action_type')},
        ),
    ]
