# Generated by Django 4.2.23 on 2025-09-24 09:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Draft title",
                        max_length=200,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        help_text="Current status of the draft",
                        max_length=20,
                    ),
                ),
                (
                    "content_blocks",
                    models.JSONField(
                        default=list, help_text="JSON array of content blocks"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Owner of this draft",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("rich_text", "Rich Text"),
                            ("heading", "Heading"),
                            ("list", "List"),
                            ("quote", "Quote"),
                            ("code", "Code Block"),
                            ("divider", "Divider"),
                        ],
                        default="text",
                        help_text="Type of content block",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        default=dict, help_text="Block content and formatting"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the block in the draft"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        help_text="Parent draft",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="notion_editor.draft",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("preview", "Preview"),
                            ("save", "Save"),
                            ("delete", "Delete"),
                            ("edit", "Edit"),
                            ("duplicate", "Duplicate"),
                            ("move_up", "Move Up"),
                            ("move_down", "Move Down"),
                        ],
                        help_text="Type of action",
                        max_length=20,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Display label for the action button", max_length=50
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon class or name for the button",
                        max_length=50,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this action is currently enabled",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Order of the action button"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        help_text="Content block this action belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="notion_editor.contentblock",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="draft",
            index=models.Index(
                fields=["user", "status"], name="notion_edit_user_id_e848e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draft",
            index=models.Index(
                fields=["created_at"], name="notion_edit_created_d90e97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draft",
            index=models.Index(
                fields=["updated_at"], name="notion_edit_updated_3fc3c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentblock",
            index=models.Index(
                fields=["draft", "order"], name="notion_edit_draft_i_53e7b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contentblock",
            index=models.Index(
                fields=["block_type"], name="notion_edit_block_t_4492dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockaction",
            index=models.Index(
                fields=["block", "order"], name="notion_edit_block_i_90d206_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blockaction",
            index=models.Index(
                fields=["action_type"], name="notion_edit_action__d23323_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="blockaction",
            unique_together={("block", "action_type")},
        ),
    ]
