# Generated by Django 4.2.23 on 2025-09-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion_editor", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="draft",
            index=models.Index(
                fields=["is_deleted"], name="notion_edit_is_dele_14ca5c_idx"
            ),
        ),
    ]
