# Generated by Django 4.2.23 on 2025-10-26 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notion_editor', '0002_draft_notion_edit_is_dele_14ca5c_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Draft title at this revision', max_length=200)),
                ('content_blocks', models.JSONField(default=list, help_text='Snapshot of content blocks at this revision')),
                ('status', models.CharField(help_text='Draft status at this revision', max_length=20)),
                ('revision_number', models.PositiveIntegerField(default=1, help_text='Sequential revision number')),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this revision')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who created this revision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_revisions', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(help_text='Parent draft', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='notion_editor.draft')),
            ],
            options={
                'ordering': ['-created_at', '-revision_number'],
                'indexes': [models.Index(fields=['draft', '-created_at'], name='notion_edit_draft_i_c94b1e_idx'), models.Index(fields=['draft', 'revision_number'], name='notion_edit_draft_i_57bce0_idx')],
                'unique_together': {('draft', 'revision_number')},
            },
        ),
    ]
