# Generated by Django 4.2.23 on 2025-11-22 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion_editor", "0003_draftrevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentblock",
            name="block_type",
            field=models.CharField(
                choices=[
                    ("text", "Plain Text"),
                    ("rich_text", "Rich Text"),
                    ("heading", "Heading"),
                    ("list", "List"),
                    ("quote", "Quote"),
                    ("code", "Code Block"),
                    ("divider", "Divider"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("file", "File"),
                    ("web_bookmark", "Web Bookmark"),
                ],
                default="text",
                help_text="Type of content block",
                max_length=20,
            ),
        ),
        # Use RunSQL to add scan_status column directly
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='notion_editor_mediafile' 
                        AND column_name='scan_status'
                    ) THEN
                        ALTER TABLE notion_editor_mediafile 
                        ADD COLUMN scan_status VARCHAR(20) DEFAULT 'ready' NOT NULL;
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE notion_editor_mediafile 
                DROP COLUMN IF EXISTS scan_status;
            """,
        ),
        # Add constraint for scan_status choices
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.constraint_column_usage 
                        WHERE table_name='notion_editor_mediafile' 
                        AND constraint_name LIKE '%scan_status%'
                    ) THEN
                        ALTER TABLE notion_editor_mediafile 
                        ADD CONSTRAINT notion_editor_mediafile_scan_status_check 
                        CHECK (scan_status IN ('ready', 'infected', 'error_scanning'));
                    END IF;
                END $$;
            """,
            reverse_sql="""
                ALTER TABLE notion_editor_mediafile 
                DROP CONSTRAINT IF EXISTS notion_editor_mediafile_scan_status_check;
            """,
        ),
        # Add index for scan_status
        migrations.RunSQL(
            sql="""
                CREATE INDEX IF NOT EXISTS notion_edit_scan_st_3bb96a_idx 
                ON notion_editor_mediafile (scan_status);
            """,
            reverse_sql="""
                DROP INDEX IF EXISTS notion_edit_scan_st_3bb96a_idx;
            """,
        ),
    ]
