# Generated by Django 4.2.23 on 2025-11-23 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notion_editor", "0004_add_scan_status_to_mediafile"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded media file",
                        max_length=500,
                        upload_to="notion_editor/media/%Y/%m/%d/",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("file", "File"),
                        ],
                        help_text="Type of media file",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original filename before upload", max_length=255
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("ready", "Ready - File is safe and available"),
                            ("infected", "Infected - File contains virus/malware"),
                            (
                                "error_scanning",
                                "ErrorScanning - Scanner error occurred",
                            ),
                        ],
                        default="ready",
                        help_text="Virus scan status of the file",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "draft",
                    models.ForeignKey(
                        blank=True,
                        help_text="Draft this file belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="notion_editor.draft",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded the file",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notion_media_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["media_type"], name="notion_edit_media_t_51db78_idx"
                    ),
                    models.Index(
                        fields=["uploaded_by", "created_at"],
                        name="notion_edit_uploade_25f7a0_idx",
                    ),
                    models.Index(
                        fields=["draft"], name="notion_edit_draft_i_08c937_idx"
                    ),
                    models.Index(
                        fields=["scan_status"], name="notion_edit_scan_st_3bb96a_idx"
                    ),
                ],
            },
        ),
    ]
