# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('creative_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel'), ('collection', 'Collection'), ('email', 'Email')], max_length=30)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Testing', 'Testing'), ('Winner', 'Winner'), ('Loser', 'Loser'), ('Paused', 'Paused')], default='Draft', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('format_payload', models.JSONField(blank=True, default=dict)),
                ('delivery', models.CharField(blank=True, default='', max_length=100)),
                ('bid_strategy', models.CharField(blank=True, default='', max_length=100)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CopyElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('element_key', models.CharField(max_length=120)),
                ('value', models.TextField()),
                ('locale', models.CharField(blank=True, max_length=40, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VariationPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metrics', models.JSONField(default=dict)),
                ('trend_indicator', models.CharField(blank=True, max_length=120, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VariationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_status', models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Testing', 'Testing'), ('Winner', 'Winner'), ('Loser', 'Loser'), ('Paused', 'Paused')], max_length=20)),
                ('to_status', models.CharField(choices=[('Draft', 'Draft'), ('Live', 'Live'), ('Testing', 'Testing'), ('Winner', 'Winner'), ('Loser', 'Loser'), ('Paused', 'Paused')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
