# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('ad_variations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variationstatushistory',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='ad_variations.advariation'),
        ),
        migrations.AddField(
            model_name='variationperformance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='variationperformance',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_entries', to='ad_variations.advariation'),
        ),
        migrations.AddField(
            model_name='copyelement',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_elements', to='ad_variations.advariation'),
        ),
        migrations.AddField(
            model_name='advariation',
            name='ad_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variations', to='ad_variations.adgroup'),
        ),
        migrations.AddField(
            model_name='advariation',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_variations', to='core.project'),
        ),
        migrations.AddField(
            model_name='adgroup',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_groups', to='core.project'),
        ),
    ]
