{
 "title": "k6-dashboard-custom",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Surge - Stress Test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_failed\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Respond Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> group(columns: [\"url\"])\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Checks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"checks\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Crash Point Analysis - Stress Test",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> derivative(unit: 1s, nonNegative: false)\r\n  |> aggregateWindow(every: 1m, fn: mean)"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"data_received\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"data_sent\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Current VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"vus\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_failed\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with _value: r._value * 100.0 }))"
    }
   ]
  },
  {
   "title": "RPS（Requests Per Second）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"http_reqs\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: false)"
    }
   ]
  },
  {
   "title": "p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"k6\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 1m, fn: mean, createEmpty: false)"
    }
   ]
  }
 ]
}