# Generated by Django 5.2.6 on 2025-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_meta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
