# Generated by Django 4.2.23 on 2025-08-30 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('owner_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('in_review', 'in_review'), ('approved', 'approved'), ('published', 'published')], default='draft', max_length=16)),
                ('time_range_start', models.DateTimeField(blank=True, null=True)),
                ('time_range_end', models.DateTimeField(blank=True, null=True)),
                ('slice_config', models.JSONField(blank=True, default=dict)),
                ('query_hash', models.CharField(blank=True, default='', max_length=64)),
                ('export_config_id', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order_index', models.IntegerField()),
                ('content_md', models.TextField(blank=True, default='')),
                ('charts', models.JSONField(blank=True, default=list)),
                ('source_slice_ids', models.JSONField(blank=True, default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('version', models.IntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('blocks', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ReportAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('file_type', models.CharField(choices=[('image', 'image'), ('csv', 'csv'), ('pptx', 'pptx'), ('pdf', 'pdf')], max_length=8)),
                ('checksum', models.CharField(blank=True, default='', max_length=64)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('approver_id', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('comment', models.TextField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAnnotation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('author_id', models.CharField(max_length=64)),
                ('body_md', models.TextField()),
                ('anchor', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'open'), ('resolved', 'resolved')], default='open', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=64, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='reports.report')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annotations', to='reports.reportsection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='report_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.reporttemplate'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('export', 'export'), ('publish', 'publish')], max_length=8)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='queued', max_length=10)),
                ('message', models.TextField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, max_length=64, null=True)),
                ('page_url', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='reports.report')),
                ('result_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='reports.reportasset')),
            ],
        ),
        migrations.CreateModel(
            name='SliceSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('dataset', models.CharField(blank=True, default='', max_length=128)),
                ('dimensions', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('time_grain', models.CharField(blank=True, default='', max_length=16)),
                ('time_range_start', models.DateTimeField(blank=True, null=True)),
                ('time_range_end', models.DateTimeField(blank=True, null=True)),
                ('query_hash', models.CharField(blank=True, default='', max_length=64)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slice_snapshots', to='reports.report')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.reportsection')),
            ],
            options={
                'indexes': [models.Index(fields=['report', 'section'], name='reports_sli_report__2b0802_idx'), models.Index(fields=['time_range_start'], name='reports_sli_time_ra_1bfb3d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['report', 'order_index'], name='reports_rep_report__be44af_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportsection',
            constraint=models.UniqueConstraint(fields=('report', 'order_index'), name='uniq_section_order_per_report'),
        ),
        migrations.AddIndex(
            model_name='reportasset',
            index=models.Index(fields=['report', 'file_type', 'created_at'], name='reports_rep_report__0cf126_idx'),
        ),
        migrations.AddIndex(
            model_name='reportapproval',
            index=models.Index(fields=['report', 'status'], name='reports_rep_report__fba311_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportapproval',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('report', 'approver_id'), name='uniq_pending_approval_per_approver'),
        ),
        migrations.AddIndex(
            model_name='reportannotation',
            index=models.Index(fields=['report', 'status'], name='reports_rep_report__d0032f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportannotation',
            index=models.Index(fields=['created_at'], name='reports_rep_created_cdf740_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status'], name='reports_rep_status_c732ef_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['owner_id', 'status'], name='reports_rep_owner_i_4e5b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='reports_rep_created_a6aabf_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['report', 'type', 'created_at'], name='reports_job_report__5c805d_idx'),
        ),
    ]
