# Generated by Django 4.2.23 on 2025-09-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportasset',
            name='file_type',
            field=models.CharField(choices=[('image', 'image'), ('csv', 'csv'), ('pptx', 'pptx'), ('pdf', 'pdf'), ('confluence', 'confluence')], max_length=16),
        ),
    ]
