# Generated by Django 4.2.23 on 2025-10-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_reportasset_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
