openapi: 3.0.3
info:
  title: Klaviyo Drafts & Workflows API
  version: 1.0.0
  description: API for managing Klaviyo email drafts and workflows (endpoints only)

paths:
  /klaviyo-drafts/:
    post:
      summary: Create a new Klaviyo email draft
      operationId: createKlaviyoDraft
      tags:
        - KlaviyoDrafts
      requestBody:
        description: Email draft payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailDraftCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailDraft'
        '400':
          description: Bad Request

    get:
      summary: List Klaviyo email drafts
      operationId: listKlaviyoDrafts
      tags:
        - KlaviyoDrafts
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            minimum: 1
        - name: page_size
          in: query
          description: Page size for pagination
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: A list of Klaviyo email drafts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmailDraft'

  /klaviyo-drafts/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the Klaviyo email draft
        required: true
        schema:
          type: integer

    get:
      summary: Retrieve a Klaviyo email draft by ID
      operationId: getKlaviyoDraft
      tags:
        - KlaviyoDrafts
      responses:
        '200':
          description: Klaviyo email draft retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailDraft'
        '404':
          description: Not Found

    put:
      summary: Update a Klaviyo email draft by ID
      operationId: updateKlaviyoDraft
      tags:
        - KlaviyoDrafts
      requestBody:
        description: Email draft update payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmailDraftUpdate'
      responses:
        '200':
          description: Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmailDraft'
        '400':
          description: Bad Request
        '404':
          description: Not Found

    delete:
      summary: Delete a Klaviyo email draft by ID
      operationId: deleteKlaviyoDraft
      tags:
        - KlaviyoDrafts
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found

  /klaviyo-workflows/:
    post:
      summary: Create a new Klaviyo workflow
      operationId: createKlaviyoWorkflow
      tags:
        - KlaviyoWorkflows
      requestBody:
        description: Workflow payload
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowCreate'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '400':
          description: Bad Request

  /klaviyo-workflows/{id}:
    parameters:
      - name: id
        in: path
        description: ID of the Klaviyo workflow
        required: true
        schema:
          type: integer

    get:
      summary: Retrieve a Klaviyo workflow by ID
      operationId: getKlaviyoWorkflow
      tags:
        - KlaviyoWorkflows
      responses:
        '200':
          description: Klaviyo workflow retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Workflow'
        '404':
          description: Not Found

components:
  schemas:
    EmailDraft:
      type: object
      properties:
        id:
          type: integer
        user:
          type: integer
          nullable: true
          description: ID of the user who owns this draft
        name:
          type: string
          description: Internal name for identifying the email draft
        subject:
          type: string
          description: Email subject line
        status:
          type: string
          description: Draft lifecycle status
          enum:
            - draft
            - scheduled
            - sent
            - archived
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        blocks:
          type: array
          description: Ordered content blocks belonging to this draft
          items:
            $ref: '#/components/schemas/ContentBlock'
      required:
        - id
        - subject
        - status
        - created_at
        - updated_at

    EmailDraftCreate:
      type: object
      properties:
        user:
          type: integer
          nullable: true
        name:
          type: string
        subject:
          type: string
        status:
          type: string
          enum:
            - draft
            - scheduled
            - sent
            - archived
      required:
        - subject

    EmailDraftUpdate:
      type: object
      properties:
        user:
          type: integer
          nullable: true
        name:
          type: string
        subject:
          type: string
        status:
          type: string
          enum:
            - draft
            - scheduled
            - sent
            - archived

    ContentBlock:
      type: object
      properties:
        id:
          type: integer
        email_draft:
          type: integer
          description: ID of the parent EmailDraft
        block_type:
          type: string
          description: Type of content block (e.g. header, text, image, button)
        content:
          type: object
          nullable: true
          description: JSON payload for this block
        order:
          type: integer
          description: Relative order of the block within the draft
      required:
        - id
        - email_draft
        - block_type
        - order

    Workflow:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
          description: Human-readable workflow name
        is_active:
          type: boolean
          description: Whether the workflow is currently active
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - is_active
        - created_at
        - updated_at

    WorkflowCreate:
      type: object
      properties:
        name:
          type: string
        is_active:
          type: boolean
      required:
        - name
