# Development stage
FROM node:18-alpine

# Set work directory
WORKDIR /app

# Create non-root user
RUN adduser --disabled-password --gecos "" --home /home/appuser appuser

# Copy package.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install -g sonarqube-scanner 
RUN apt-get update && apt-get install -y curl

# Copy the rest of the application
COPY . .

# Assign permission
RUN chown -R appuser:appuser /app

# Switch to non-root user
USER appuser

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["npm", "run", "dev"]
