version: 0.0
os: linux
# Pull source code
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  # Start service in green env
  AfterInstall:
    - location: AWS-Blue-Green-Deploy/start_container.sh
      timeout: 300
      runas: ubuntu

  #  Health check before traffic switching
  # AfterAllowTestTraffic:
  #   - location: AWS-Blue-Green-Deploy/validate_service.sh
  #     timeout: 180
  #     runas: ubuntu

  # Wrapping up work after sucessful deployment(optional)
  # BeforeAllowTraffic:
  #   - location: AWS-Blue-Green-Deploy/cleanup_old_images.sh
  #     timeout: 60
  #     runas: ubuntu