# Development stage
FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Copy source code
COPY . .

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    mediainfo \
    wget \
    unzip \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install sonar-scanner
# RUN wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip \
#     && unzip sonar-scanner-cli-*.zip -d /opt \
#     && rm sonar-scanner-cli-*.zip
# ENV PATH="/opt/sonar-scanner-5.0.1.3006-linux/bin:${PATH}"

# Expose port
EXPOSE 8000

# Add non-root user(Debian/Ubuntu)
RUN adduser --disabled-password --gecos "" appuser
RUN chown -R appuser:appuser /app
USER appuser

# Start development server with ASGI support
CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"] 