#!/bin/bash
set -e

# Wait for sonarqube
# until curl -u ${SONAR_USER}:${SONAR_PWD} -s http://sonarqube:9000/api/system/health | grep -q '"health":"GREEN"'; do
#   echo "Waiting for SonarQube..."
#   sleep 5
# done

# Load token
# if [ -f /token/sonar.env ]; then
#   export $(cat /token/sonar.env | xargs)
# fi

#Sonar scan
# sonar-scanner \
#   -Dsonar.projectKey=mediaJira_Backend \
#   -Dsonar.sources=/app \
#   -Dsonar.host.url=http://sonarqube:9000 \
#   -Dsonar.login=$SONAR_TOKEN || echo "Sonar scan skipped or failed"

# Apply DB migrations (dev): keeps schema in sync when new models/migrations land
export DJANGO_SETTINGS_MODULE=backend.settings
python manage.py migrate --noinput

# Start Django
exec opentelemetry-instrument daphne -b 0.0.0.0 -p 8000 backend.asgi:application
