#!/bin/bash
set -e

# Create static directory if it doesn't exist
mkdir -p /app/static
# Collect static files
python manage.py collectstatic --noinput || true


# Start Django
# exec daphne -b 0.0.0.0 -p 8000 backend.asgi:application


# Start Django
export DJANGO_SETTINGS_MODULE=backend.settings
exec opentelemetry-instrument daphne -b 0.0.0.0 -p 8000 backend.asgi:application
