# Generated by Django 4.2.23 on 2026-01-27 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendars', '0002_event_etag'),
        ('core', '0009_projectinvitation_approval_fields'),
        ('decision', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0021_add_optimization_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Campaign name (mandatory)', max_length=255)),
                ('objective', models.CharField(choices=[('AWARENESS', 'Awareness'), ('CONSIDERATION', 'Consideration'), ('CONVERSION', 'Conversion'), ('RETENTION', 'Retention'), ('ENGAGEMENT', 'Engagement'), ('TRAFFIC', 'Traffic'), ('LEAD_GENERATION', 'Lead Generation'), ('APP_PROMOTION', 'App Promotion')], help_text='Campaign objective (mandatory)', max_length=50)),
                ('platforms', models.JSONField(default=list, help_text='Target platforms as list of Platform choices (mandatory)')),
                ('hypothesis', models.TextField(blank=True, help_text='Strategic hypothesis (optional)', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Organizational tags (optional)')),
                ('start_date', models.DateField(help_text='Campaign start date (mandatory)')),
                ('end_date', models.DateField(blank=True, help_text='Campaign end date (optional)', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual completion date (set when completed)', null=True)),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Budget estimate (optional)', max_digits=15, null=True)),
                ('status', django_fsm.FSMField(choices=[('PLANNING', 'Planning'), ('TESTING', 'Testing'), ('SCALING', 'Scaling'), ('OPTIMIZING', 'Optimizing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNING', help_text='Current lifecycle stage', max_length=20, protected=True)),
                ('status_note', models.TextField(blank=True, help_text='Note explaining current status or last status change', null=True)),
                ('latest_performance_summary', models.JSONField(blank=True, default=dict, help_text='Latest performance snapshot data for quick dashboard display')),
                ('assignee', models.ForeignKey(blank=True, help_text='当前执行负责人（可变更）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(help_text='User who created the campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='Campaign owner (mandatory - Section 3.1)', on_delete=django.db.models.deletion.PROTECT, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.project')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTaskLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(blank=True, help_text="Type of relationship (e.g., 'auto_generated', 'manual', 'milestone')", max_length=50, null=True)),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='campaign.campaign')),
                ('task', models.ForeignKey(help_text='Linked task', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='task.task')),
            ],
            options={
                'db_table': 'campaign_task_links',
            },
        ),
        migrations.CreateModel(
            name='CampaignStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('PLANNING', 'Planning'), ('TESTING', 'Testing'), ('SCALING', 'Scaling'), ('OPTIMIZING', 'Optimizing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], help_text='Previous status', max_length=20)),
                ('to_status', models.CharField(choices=[('PLANNING', 'Planning'), ('TESTING', 'Testing'), ('SCALING', 'Scaling'), ('OPTIMIZING', 'Optimizing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], help_text='New status', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Rationale for status change', null=True)),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='campaign.campaign')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_status_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('OVERDUE_REVIEW', 'Overdue Review Points'), ('PENDING_DECISION', 'Pending Decisions'), ('TASK_DUE', 'Tasks Approaching Due Date'), ('NO_UPDATE_THRESHOLD', 'Campaign Without Updates'), ('MILESTONE_ACHIEVEMENT', 'Achievement Milestones'), ('PERFORMANCE_ALERT', 'Performance Alerts')], help_text='Type of notification', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this notification type is enabled')),
                ('delivery_channels', models.JSONField(default=list, help_text="List of delivery channels (e.g., ['IN_APP', 'EMAIL'])")),
                ('threshold_config', models.JSONField(blank=True, default=dict, help_text="Type-specific thresholds (e.g., {'days_without_update': 7})")),
                ('project', models.ForeignKey(blank=True, help_text='Project-specific preferences (null = global default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.project')),
                ('user', models.ForeignKey(help_text='User these preferences apply to', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='CampaignDecisionLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(blank=True, help_text="What triggered this decision (e.g., 'test_complete', 'threshold_breach', 'manual')", max_length=50, null=True)),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='decision_links', to='campaign.campaign')),
                ('decision', models.ForeignKey(help_text='Linked decision', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='decision.decision')),
            ],
            options={
                'db_table': 'campaign_decision_links',
            },
        ),
        migrations.CreateModel(
            name='CampaignCalendarLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(blank=True, help_text="Type of event (e.g., 'milestone', 'review', 'budget_check', 'test_deadline')", max_length=50, null=True)),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='campaign.campaign')),
                ('event', models.ForeignKey(help_text='Linked calendar event', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='calendars.event')),
            ],
            options={
                'db_table': 'campaign_calendar_links',
            },
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (optional if URL is provided)', null=True, upload_to='campaign/attachments/%Y/%m/%d/')),
                ('url', models.URLField(blank=True, help_text='External URL (optional if file is provided)', max_length=2048, null=True)),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('LINK', 'Link'), ('OTHER', 'Other')], help_text='Type of asset', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as key-value pairs')),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='campaign.campaign')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded/added the attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'campaign_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('STATUS_CHANGE', 'Campaign Status Change'), ('MILESTONE_DATE', 'Milestone Date Reached'), ('PERFORMANCE_THRESHOLD', 'Performance Threshold'), ('TIME_BASED', 'Time-Based (e.g., X days since)'), ('CONSECUTIVE_CHECKINS', 'Consecutive Check-ins Pattern')], help_text='What triggers this automation', max_length=50)),
                ('trigger_config', models.JSONField(default=dict, help_text="Trigger-specific configuration (e.g., {'from_status': 'TESTING', 'to_status': 'SCALING'})")),
                ('action_type', models.CharField(choices=[('CREATE_TASK', 'Create Task'), ('CREATE_DECISION', 'Create Decision Card'), ('CREATE_CALENDAR_EVENT', 'Create Calendar Event'), ('SEND_NOTIFICATION', 'Send Notification')], help_text='What action to take', max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text='Action-specific configuration (e.g., task template, decision template)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this trigger is active (Section 5.4: can be toggled off)')),
                ('prevent_duplicates', models.BooleanField(default=True, help_text='Prevent creating duplicate tasks/decisions for same issue')),
                ('duplicate_check_config', models.JSONField(blank=True, default=dict, help_text='How to check for duplicates (e.g., time window, key fields)')),
                ('project', models.ForeignKey(help_text='Project this trigger applies to', on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to='core.project')),
            ],
            options={
                'db_table': 'automation_triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, help_text='When the trigger was fired')),
                ('executed_successfully', models.BooleanField(default=True, help_text='Whether the action completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('trigger_context', models.JSONField(blank=True, default=dict, help_text='Context data at trigger time (for debugging/auditing)')),
                ('campaign', models.ForeignKey(help_text='Campaign this execution was for', on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='campaign.campaign')),
                ('created_decision', models.ForeignKey(blank=True, help_text='Decision created by this automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_source', to='decision.decision')),
                ('created_event', models.ForeignKey(blank=True, help_text='Calendar event created by this automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_source', to='calendars.event')),
                ('created_task', models.ForeignKey(blank=True, help_text='Task created by this automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_source', to='task.task')),
                ('trigger', models.ForeignKey(help_text='Which trigger was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='campaign.automationtrigger')),
            ],
            options={
                'db_table': 'automation_executions',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(choices=[('LAUNCH', 'Campaign Launch'), ('MID_TEST', 'Mid-Test Review'), ('TEST_COMPLETE', 'Test Completion'), ('OPTIMIZATION', 'Major Optimization'), ('WEEKLY_REVIEW', 'Weekly Review'), ('MONTHLY_REVIEW', 'Monthly Review'), ('CUSTOM', 'Custom Milestone')], default='CUSTOM', help_text='Type of milestone this snapshot represents', max_length=30)),
                ('spend', models.DecimalField(decimal_places=2, help_text='Total spend at this milestone (mandatory)', max_digits=15)),
                ('metric_type', models.CharField(choices=[('CPA', 'Cost Per Acquisition'), ('ROAS', 'Return on Ad Spend'), ('CTR', 'Click-Through Rate'), ('CPM', 'Cost Per Mille'), ('CPC', 'Cost Per Click'), ('CONVERSIONS', 'Conversions'), ('REVENUE', 'Revenue'), ('IMPRESSIONS', 'Impressions'), ('CLICKS', 'Clicks'), ('ENGAGEMENT_RATE', 'Engagement Rate')], help_text='Type of primary metric (mandatory)', max_length=30)),
                ('metric_value', models.DecimalField(decimal_places=4, help_text='Value of primary metric (mandatory)', max_digits=15)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change vs previous period (optional)', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, help_text='Free-form observations (optional)', null=True)),
                ('screenshot', models.FileField(blank=True, help_text='Optional screenshot attachment', null=True, upload_to='campaign/snapshots/%Y/%m/%d/')),
                ('additional_metrics', models.JSONField(blank=True, default=dict, help_text='Additional metrics as key-value pairs')),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='campaign.campaign')),
                ('snapshot_by', models.ForeignKey(help_text='User who created the snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_snapshots',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', '-created_at'], name='performance_campaig_355f52_idx'), models.Index(fields=['metric_type', '-created_at'], name='performance_metric__ef6ad2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCheckIn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], help_text='Campaign health indicator', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Brief optional note', null=True)),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='campaign.campaign')),
                ('checked_by', models.ForeignKey(help_text='User who made the check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_check_ins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'performance_check_ins',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign', '-created_at'], name='performance_campaig_846a80_idx'), models.Index(fields=['sentiment', '-created_at'], name='performance_sentime_7b8164_idx')],
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (must be unique within scope)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description', null=True)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Template version number')),
                ('sharing_scope', models.CharField(choices=[('PERSONAL', 'Personal (Private)'), ('TEAM', 'Team-wide'), ('ORGANIZATION', 'Organization-wide')], default='PERSONAL', help_text='Who can use this template', max_length=20)),
                ('objective', models.CharField(blank=True, choices=[('AWARENESS', 'Awareness'), ('CONSIDERATION', 'Consideration'), ('CONVERSION', 'Conversion'), ('RETENTION', 'Retention'), ('ENGAGEMENT', 'Engagement'), ('TRAFFIC', 'Traffic'), ('LEAD_GENERATION', 'Lead Generation'), ('APP_PROMOTION', 'App Promotion')], help_text='Default objective', max_length=50, null=True)),
                ('platforms', models.JSONField(blank=True, default=list, help_text='Suggested platform list')),
                ('hypothesis_framework', models.TextField(blank=True, help_text='Hypothesis template or framework', null=True)),
                ('tag_suggestions', models.JSONField(blank=True, default=list, help_text='Suggested tags')),
                ('task_checklist', models.JSONField(blank=True, default=list, help_text='Task checklist with due date formulas')),
                ('review_schedule_pattern', models.JSONField(blank=True, default=dict, help_text="Review schedule pattern (e.g., {'frequency': 'weekly', 'day': 'Monday'})")),
                ('decision_point_triggers', models.JSONField(blank=True, default=list, help_text='Automated decision point triggers')),
                ('recommended_variation_count', models.PositiveIntegerField(default=3, help_text='Recommended number of variations')),
                ('variation_templates', models.JSONField(blank=True, default=list, help_text='Copy element templates for variations')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this template is archived (soft delete - preserves campaign history)')),
                ('creator', models.ForeignKey(help_text='User who created the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaign_templates', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Project scope (for team/org templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to='core.project')),
            ],
            options={
                'db_table': 'campaign_templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator', 'sharing_scope', 'is_archived'], name='campaign_te_creator_97d259_idx'), models.Index(fields=['project', 'sharing_scope', 'is_archived'], name='campaign_te_project_83e7cb_idx'), models.Index(fields=['name'], name='campaign_te_name_0922a4_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campaigntemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('sharing_scope', 'PERSONAL')), fields=('creator', 'name', 'sharing_scope'), name='unique_template_name_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='campaigntemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('sharing_scope__in', ['TEAM', 'ORGANIZATION'])), fields=('project', 'name', 'sharing_scope'), name='unique_template_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='campaigntasklink',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_ta_campaig_a1dc00_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntasklink',
            index=models.Index(fields=['task'], name='campaign_ta_task_id_7f3b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntasklink',
            unique_together={('campaign', 'task')},
        ),
        migrations.AddIndex(
            model_name='campaignstatushistory',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_st_campaig_051ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignnotificationpreference',
            index=models.Index(fields=['user', 'enabled'], name='campaign_no_user_id_919d60_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignnotificationpreference',
            index=models.Index(fields=['project', 'enabled'], name='campaign_no_project_ee2b76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignnotificationpreference',
            unique_together={('user', 'project', 'notification_type')},
        ),
        migrations.AddIndex(
            model_name='campaigndecisionlink',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_de_campaig_7eba3a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndecisionlink',
            index=models.Index(fields=['decision'], name='campaign_de_decisio_ec0334_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigndecisionlink',
            unique_together={('campaign', 'decision')},
        ),
        migrations.AddIndex(
            model_name='campaigncalendarlink',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_ca_campaig_50334e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncalendarlink',
            index=models.Index(fields=['event'], name='campaign_ca_event_i_5493e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncalendarlink',
            unique_together={('campaign', 'event')},
        ),
        migrations.AddIndex(
            model_name='campaignattachment',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_at_campaig_2b0159_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignattachment',
            index=models.Index(fields=['asset_type', '-created_at'], name='campaign_at_asset_t_3aa49f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['project', 'status', '-created_at'], name='campaigns_project_b8f117_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'status'], name='campaigns_owner_i_6dac12_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['assignee', 'status'], name='campaigns_assigne_58e0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='campaigns_start_d_5c7483_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['project', 'start_date'], name='campaigns_project_12f5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['project', 'is_active'], name='automation__project_8acb42_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['trigger_type', 'is_active'], name='automation__trigger_e4b5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['campaign', '-triggered_at'], name='automation__campaig_524b51_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['trigger', '-triggered_at'], name='automation__trigger_639c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['executed_successfully'], name='automation__execute_2bd21c_idx'),
        ),
    ]
