# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, help_text='When the trigger was fired')),
                ('executed_successfully', models.BooleanField(default=True, help_text='Whether the action completed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed', null=True)),
                ('trigger_context', models.JSONField(blank=True, default=dict, help_text='Context data at trigger time (for debugging/auditing)')),
            ],
            options={
                'db_table': 'automation_executions',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationTrigger',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('STATUS_CHANGE', 'Campaign Status Change'), ('MILESTONE_DATE', 'Milestone Date Reached'), ('PERFORMANCE_THRESHOLD', 'Performance Threshold'), ('TIME_BASED', 'Time-Based (e.g., X days since)'), ('CONSECUTIVE_CHECKINS', 'Consecutive Check-ins Pattern')], help_text='What triggers this automation', max_length=50)),
                ('trigger_config', models.JSONField(default=dict, help_text="Trigger-specific configuration (e.g., {'from_status': 'TESTING', 'to_status': 'SCALING'})")),
                ('action_type', models.CharField(choices=[('CREATE_TASK', 'Create Task'), ('CREATE_DECISION', 'Create Decision Card'), ('CREATE_CALENDAR_EVENT', 'Create Calendar Event'), ('SEND_NOTIFICATION', 'Send Notification')], help_text='What action to take', max_length=50)),
                ('action_config', models.JSONField(default=dict, help_text='Action-specific configuration (e.g., task template, decision template)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this trigger is active (Section 5.4: can be toggled off)')),
                ('prevent_duplicates', models.BooleanField(default=True, help_text='Prevent creating duplicate tasks/decisions for same issue')),
                ('duplicate_check_config', models.JSONField(blank=True, default=dict, help_text='How to check for duplicates (e.g., time window, key fields)')),
            ],
            options={
                'db_table': 'automation_triggers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Campaign name (mandatory)', max_length=255)),
                ('objective', models.CharField(choices=[('AWARENESS', 'Awareness'), ('CONSIDERATION', 'Consideration'), ('CONVERSION', 'Conversion'), ('RETENTION', 'Retention'), ('ENGAGEMENT', 'Engagement'), ('TRAFFIC', 'Traffic'), ('LEAD_GENERATION', 'Lead Generation'), ('APP_PROMOTION', 'App Promotion')], help_text='Campaign objective (mandatory)', max_length=50)),
                ('platforms', models.JSONField(default=list, help_text='Target platforms as list of Platform choices (mandatory)')),
                ('hypothesis', models.TextField(blank=True, help_text='Strategic hypothesis (optional)', null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Organizational tags (optional)')),
                ('start_date', models.DateField(help_text='Campaign start date (mandatory)')),
                ('end_date', models.DateField(blank=True, help_text='Campaign end date (optional)', null=True)),
                ('actual_completion_date', models.DateField(blank=True, help_text='Actual completion date (set when completed)', null=True)),
                ('budget_estimate', models.DecimalField(blank=True, decimal_places=2, help_text='Budget estimate (optional)', max_digits=15, null=True)),
                ('status', django_fsm.FSMField(choices=[('PLANNING', 'Planning'), ('TESTING', 'Testing'), ('SCALING', 'Scaling'), ('OPTIMIZING', 'Optimizing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='PLANNING', help_text='Current lifecycle stage', max_length=20, protected=True)),
                ('status_note', models.TextField(blank=True, help_text='Note explaining current status or last status change', null=True)),
                ('latest_performance_summary', models.JSONField(blank=True, default=dict, help_text='Latest performance snapshot data for quick dashboard display')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, help_text='Uploaded file (optional if URL is provided)', null=True, upload_to='campaign/attachments/%Y/%m/%d/')),
                ('url', models.URLField(blank=True, help_text='External URL (optional if file is provided)', max_length=2048, null=True)),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('LINK', 'Link'), ('OTHER', 'Other')], help_text='Type of asset', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata as key-value pairs')),
            ],
            options={
                'db_table': 'campaign_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignCalendarLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(blank=True, help_text="Type of event (e.g., 'milestone', 'review', 'budget_check', 'test_deadline')", max_length=50, null=True)),
            ],
            options={
                'db_table': 'campaign_calendar_links',
            },
        ),
        migrations.CreateModel(
            name='CampaignDecisionLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(blank=True, help_text="What triggered this decision (e.g., 'test_complete', 'threshold_breach', 'manual')", max_length=50, null=True)),
            ],
            options={
                'db_table': 'campaign_decision_links',
            },
        ),
        migrations.CreateModel(
            name='CampaignNotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('OVERDUE_REVIEW', 'Overdue Review Points'), ('PENDING_DECISION', 'Pending Decisions'), ('TASK_DUE', 'Tasks Approaching Due Date'), ('NO_UPDATE_THRESHOLD', 'Campaign Without Updates'), ('MILESTONE_ACHIEVEMENT', 'Achievement Milestones'), ('PERFORMANCE_ALERT', 'Performance Alerts')], help_text='Type of notification', max_length=50)),
                ('enabled', models.BooleanField(default=True, help_text='Whether this notification type is enabled')),
                ('delivery_channels', models.JSONField(default=list, help_text="List of delivery channels (e.g., ['IN_APP', 'EMAIL'])")),
                ('threshold_config', models.JSONField(blank=True, default=dict, help_text="Type-specific thresholds (e.g., {'days_without_update': 7})")),
            ],
            options={
                'db_table': 'campaign_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='CampaignStatusHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(choices=[('PLANNING', 'Planning'), ('TESTING', 'Testing'), ('SCALING', 'Scaling'), ('OPTIMIZING', 'Optimizing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], help_text='Previous status', max_length=20)),
                ('to_status', models.CharField(choices=[('PLANNING', 'Planning'), ('TESTING', 'Testing'), ('SCALING', 'Scaling'), ('OPTIMIZING', 'Optimizing'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], help_text='New status', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Rationale for status change', null=True)),
            ],
            options={
                'db_table': 'campaign_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTaskLink',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_type', models.CharField(blank=True, help_text="Type of relationship (e.g., 'auto_generated', 'manual', 'milestone')", max_length=50, null=True)),
            ],
            options={
                'db_table': 'campaign_task_links',
            },
        ),
        migrations.CreateModel(
            name='CampaignTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Template name (must be unique within scope)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Template description', null=True)),
                ('version_number', models.PositiveIntegerField(default=1, help_text='Template version number')),
                ('sharing_scope', models.CharField(choices=[('PERSONAL', 'Personal (Private)'), ('TEAM', 'Team-wide'), ('ORGANIZATION', 'Organization-wide')], default='PERSONAL', help_text='Who can use this template', max_length=20)),
                ('objective', models.CharField(blank=True, choices=[('AWARENESS', 'Awareness'), ('CONSIDERATION', 'Consideration'), ('CONVERSION', 'Conversion'), ('RETENTION', 'Retention'), ('ENGAGEMENT', 'Engagement'), ('TRAFFIC', 'Traffic'), ('LEAD_GENERATION', 'Lead Generation'), ('APP_PROMOTION', 'App Promotion')], help_text='Default objective', max_length=50, null=True)),
                ('platforms', models.JSONField(blank=True, default=list, help_text='Suggested platform list')),
                ('hypothesis_framework', models.TextField(blank=True, help_text='Hypothesis template or framework', null=True)),
                ('tag_suggestions', models.JSONField(blank=True, default=list, help_text='Suggested tags')),
                ('task_checklist', models.JSONField(blank=True, default=list, help_text='Task checklist with due date formulas')),
                ('review_schedule_pattern', models.JSONField(blank=True, default=dict, help_text="Review schedule pattern (e.g., {'frequency': 'weekly', 'day': 'Monday'})")),
                ('decision_point_triggers', models.JSONField(blank=True, default=list, help_text='Automated decision point triggers')),
                ('recommended_variation_count', models.PositiveIntegerField(default=3, help_text='Recommended number of variations')),
                ('variation_templates', models.JSONField(blank=True, default=list, help_text='Copy element templates for variations')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Number of times this template has been used')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this template is archived (soft delete - preserves campaign history)')),
            ],
            options={
                'db_table': 'campaign_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCheckIn',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('NEGATIVE', 'Negative')], help_text='Campaign health indicator', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Brief optional note', null=True)),
            ],
            options={
                'db_table': 'performance_check_ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(choices=[('LAUNCH', 'Campaign Launch'), ('MID_TEST', 'Mid-Test Review'), ('TEST_COMPLETE', 'Test Completion'), ('OPTIMIZATION', 'Major Optimization'), ('WEEKLY_REVIEW', 'Weekly Review'), ('MONTHLY_REVIEW', 'Monthly Review'), ('CUSTOM', 'Custom Milestone')], default='CUSTOM', help_text='Type of milestone this snapshot represents', max_length=30)),
                ('spend', models.DecimalField(decimal_places=2, help_text='Total spend at this milestone (mandatory)', max_digits=15)),
                ('metric_type', models.CharField(choices=[('CPA', 'Cost Per Acquisition'), ('ROAS', 'Return on Ad Spend'), ('CTR', 'Click-Through Rate'), ('CPM', 'Cost Per Mille'), ('CPC', 'Cost Per Click'), ('CONVERSIONS', 'Conversions'), ('REVENUE', 'Revenue'), ('IMPRESSIONS', 'Impressions'), ('CLICKS', 'Clicks'), ('ENGAGEMENT_RATE', 'Engagement Rate')], help_text='Type of primary metric (mandatory)', max_length=30)),
                ('metric_value', models.DecimalField(decimal_places=4, help_text='Value of primary metric (mandatory)', max_digits=15)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change vs previous period (optional)', max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, help_text='Free-form observations (optional)', null=True)),
                ('screenshot', models.FileField(blank=True, help_text='Optional screenshot attachment', null=True, upload_to='campaign/snapshots/%Y/%m/%d/')),
                ('additional_metrics', models.JSONField(blank=True, default=dict, help_text='Additional metrics as key-value pairs')),
                ('campaign', models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='campaign.campaign')),
            ],
            options={
                'db_table': 'performance_snapshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
