# Generated by Django 4.2.23 on 2025-12-16 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_rename_core_projec_email_abc123_idx_core_projec_email_45393c_idx_and_more'),
        ('task', '0006_alter_task_type_alter_taskcomment_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignTask',
            fields=[
                ('campaign_task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Campaign task title', max_length=255)),
                ('scheduled_date', models.DateTimeField(help_text='Scheduled start date/time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional end date/time', null=True)),
                ('channel', models.CharField(choices=[('GoogleAds', 'Google Ads'), ('FacebookAds', 'Facebook Ads'), ('TikTokAds', 'TikTok Ads')], help_text='Ad channel', max_length=20)),
                ('creative_asset_ids', models.JSONField(default=list, help_text='Array of asset IDs or asset objects')),
                ('audience_config', models.JSONField(default=dict, help_text='Audience configuration (type-specific)')),
                ('external_ids_json', models.JSONField(blank=True, default=dict, help_text='External platform IDs (campaignId, adSetIds, etc.)', null=True)),
                ('status', django_fsm.FSMField(choices=[('Scheduled', 'Scheduled'), ('Launched', 'Launched'), ('Paused', 'Paused'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Archived', 'Archived')], default='Scheduled', help_text='Current status of the campaign task', max_length=20)),
                ('platform_status', models.CharField(blank=True, help_text='Native status from external platform', max_length=100, null=True)),
                ('roi_threshold', models.FloatField(blank=True, help_text='ROI threshold for alerts', null=True)),
                ('paused_reason', models.TextField(blank=True, help_text='Reason for pausing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created the campaign task', on_delete=django.db.models.deletion.CASCADE, related_name='created_campaign_tasks', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, help_text='Reference to generic Task model', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_tasks', to='task.task')),
            ],
            options={
                'db_table': 'campaign_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ROIAlertTrigger',
            fields=[
                ('roi_alert_trigger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_key', models.CharField(choices=[('roas', 'ROAS'), ('roi', 'ROI'), ('cpa', 'CPA'), ('ctr', 'CTR'), ('cpc', 'CPC')], help_text='Metric to monitor', max_length=10)),
                ('comparator', models.CharField(choices=[('<', '<'), ('<=', '<='), ('>', '>'), ('>=', '>='), ('=', '=')], help_text='Comparison operator', max_length=2)),
                ('threshold', models.FloatField(help_text='Threshold value')),
                ('lookback_minutes', models.IntegerField(default=60, help_text='Lookback window in minutes')),
                ('action', models.CharField(choices=[('NotifyOnly', 'Notify Only'), ('AutoPause', 'Auto Pause')], help_text='Action to take', max_length=15)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_task', models.ForeignKey(help_text='Reference to CampaignTask', on_delete=django.db.models.deletion.CASCADE, related_name='roi_alerts', to='campaign.campaigntask')),
            ],
            options={
                'db_table': 'roi_alert_trigger',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['campaign_task', 'is_active'], name='roi_alert_t_campaig_c56957_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('execution_log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('Launch', 'Launch'), ('Pause', 'Pause'), ('Resume', 'Resume'), ('Adjust', 'Adjust'), ('AlertTrigger', 'Alert Trigger'), ('MetricIngest', 'Metric Ingest'), ('Complete', 'Complete'), ('Fail', 'Fail')], help_text='Type of operation event', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Event timestamp')),
                ('result', models.CharField(choices=[('Success', 'Success'), ('Error', 'Error')], help_text='Result of the operation', max_length=10)),
                ('message', models.TextField(blank=True, help_text='Human-readable message', null=True)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Normalized metrics snapshot', null=True)),
                ('channel_response', models.JSONField(blank=True, default=dict, help_text='Raw platform response payload', null=True)),
                ('actor_user_id', models.ForeignKey(blank=True, help_text='User who triggered the action (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_actions', to=settings.AUTH_USER_MODEL)),
                ('campaign_task', models.ForeignKey(help_text='Reference to CampaignTask', on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='campaign.campaigntask')),
            ],
            options={
                'db_table': 'execution_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['campaign_task', '-timestamp'], name='execution_l_campaig_02a959_idx'), models.Index(fields=['event'], name='execution_l_event_625ec4_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChannelConfig',
            fields=[
                ('channel_config_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('GoogleAds', 'Google Ads'), ('FacebookAds', 'Facebook Ads'), ('TikTokAds', 'TikTok Ads')], help_text='Ad channel', max_length=20)),
                ('auth_token', models.CharField(blank=True, help_text='Placeholder; OAuth managed elsewhere', max_length=500)),
                ('settings_json', models.JSONField(default=dict, help_text='Channel-specific settings (account_id, timezone, currency, etc.)')),
                ('last_refreshed', models.DateTimeField(blank=True, help_text='Last token refresh time', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this config is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(help_text='Team this configuration belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='channel_configs', to='core.team')),
            ],
            options={
                'db_table': 'channel_config',
                'indexes': [models.Index(fields=['team', 'channel'], name='channel_con_team_id_068a19_idx')],
                'unique_together': {('team', 'channel')},
            },
        ),
        migrations.AddIndex(
            model_name='campaigntask',
            index=models.Index(fields=['status'], name='campaign_ta_status_294faf_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntask',
            index=models.Index(fields=['channel'], name='campaign_ta_channel_ce183e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntask',
            index=models.Index(fields=['created_by'], name='campaign_ta_created_b4ca6b_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntask',
            index=models.Index(fields=['scheduled_date'], name='campaign_ta_schedul_f2ed5b_idx'),
        ),
    ]
