# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesnapshot',
            name='snapshot_by',
            field=models.ForeignKey(help_text='User who created the snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancecheckin',
            name='campaign',
            field=models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='performancecheckin',
            name='checked_by',
            field=models.ForeignKey(help_text='User who made the check-in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_check_ins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='creator',
            field=models.ForeignKey(help_text='User who created the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaign_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigntemplate',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project scope (for team/org templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_templates', to='core.project'),
        ),
        migrations.AddField(
            model_name='campaigntasklink',
            name='campaign',
            field=models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='task_links', to='campaign.campaign'),
        ),
    ]
