# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('campaign', '0002_initial'),
        ('task', '0001_initial'),
        ('calendars', '0002_initial'),
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntasklink',
            name='task',
            field=models.ForeignKey(help_text='Linked task', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='task.task'),
        ),
        migrations.AddField(
            model_name='campaignstatushistory',
            name='campaign',
            field=models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='campaignstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaignnotificationpreference',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project-specific preferences (null = global default)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='core.project'),
        ),
        migrations.AddField(
            model_name='campaignnotificationpreference',
            name='user',
            field=models.ForeignKey(help_text='User these preferences apply to', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaigndecisionlink',
            name='campaign',
            field=models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='decision_links', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndecisionlink',
            name='decision',
            field=models.ForeignKey(help_text='Linked decision', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='decision.decision'),
        ),
        migrations.AddField(
            model_name='campaigncalendarlink',
            name='campaign',
            field=models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_links', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='campaigncalendarlink',
            name='event',
            field=models.ForeignKey(help_text='Linked calendar event', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_links', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='campaignattachment',
            name='campaign',
            field=models.ForeignKey(help_text='Associated campaign', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='campaignattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded/added the attachment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='当前执行负责人（可变更）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(help_text='User who created the campaign', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='owner',
            field=models.ForeignKey(help_text='Campaign owner (mandatory - Section 3.1)', on_delete=django.db.models.deletion.PROTECT, related_name='owned_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project',
            field=models.ForeignKey(help_text='Project this campaign belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='core.project'),
        ),
        migrations.AddField(
            model_name='automationtrigger',
            name='project',
            field=models.ForeignKey(help_text='Project this trigger applies to', on_delete=django.db.models.deletion.CASCADE, related_name='automation_triggers', to='core.project'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='campaign',
            field=models.ForeignKey(help_text='Campaign this execution was for', on_delete=django.db.models.deletion.CASCADE, related_name='automation_executions', to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='created_decision',
            field=models.ForeignKey(blank=True, help_text='Decision created by this automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_source', to='decision.decision'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='created_event',
            field=models.ForeignKey(blank=True, help_text='Calendar event created by this automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_source', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='created_task',
            field=models.ForeignKey(blank=True, help_text='Task created by this automation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_source', to='task.task'),
        ),
        migrations.AddField(
            model_name='automationexecution',
            name='trigger',
            field=models.ForeignKey(help_text='Which trigger was executed', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='campaign.automationtrigger'),
        ),
        migrations.AddIndex(
            model_name='performancesnapshot',
            index=models.Index(fields=['campaign', '-created_at'], name='performance_campaig_355f52_idx'),
        ),
        migrations.AddIndex(
            model_name='performancesnapshot',
            index=models.Index(fields=['metric_type', '-created_at'], name='performance_metric__ef6ad2_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecheckin',
            index=models.Index(fields=['campaign', '-created_at'], name='performance_campaig_846a80_idx'),
        ),
        migrations.AddIndex(
            model_name='performancecheckin',
            index=models.Index(fields=['sentiment', '-created_at'], name='performance_sentime_7b8164_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['creator', 'sharing_scope', 'is_archived'], name='campaign_te_creator_97d259_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['project', 'sharing_scope', 'is_archived'], name='campaign_te_project_83e7cb_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntemplate',
            index=models.Index(fields=['name'], name='campaign_te_name_0922a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigntemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('sharing_scope', 'PERSONAL')), fields=('creator', 'name', 'sharing_scope'), name='unique_template_name_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='campaigntemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('sharing_scope__in', ['TEAM', 'ORGANIZATION'])), fields=('project', 'name', 'sharing_scope'), name='unique_template_name_per_project'),
        ),
        migrations.AddIndex(
            model_name='campaigntasklink',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_ta_campaig_a1dc00_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigntasklink',
            index=models.Index(fields=['task'], name='campaign_ta_task_id_7f3b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigntasklink',
            unique_together={('campaign', 'task')},
        ),
        migrations.AddIndex(
            model_name='campaignstatushistory',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_st_campaig_051ca0_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignnotificationpreference',
            index=models.Index(fields=['user', 'enabled'], name='campaign_no_user_id_919d60_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignnotificationpreference',
            index=models.Index(fields=['project', 'enabled'], name='campaign_no_project_ee2b76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignnotificationpreference',
            unique_together={('user', 'project', 'notification_type')},
        ),
        migrations.AddIndex(
            model_name='campaigndecisionlink',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_de_campaig_7eba3a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndecisionlink',
            index=models.Index(fields=['decision'], name='campaign_de_decisio_ec0334_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigndecisionlink',
            unique_together={('campaign', 'decision')},
        ),
        migrations.AddIndex(
            model_name='campaigncalendarlink',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_ca_campaig_50334e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncalendarlink',
            index=models.Index(fields=['event'], name='campaign_ca_event_i_5493e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigncalendarlink',
            unique_together={('campaign', 'event')},
        ),
        migrations.AddIndex(
            model_name='campaignattachment',
            index=models.Index(fields=['campaign', '-created_at'], name='campaign_at_campaig_2b0159_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignattachment',
            index=models.Index(fields=['asset_type', '-created_at'], name='campaign_at_asset_t_3aa49f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['project', 'status', '-created_at'], name='campaigns_project_b8f117_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['owner', 'status'], name='campaigns_owner_i_6dac12_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['assignee', 'status'], name='campaigns_assigne_58e0b2_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['start_date', 'end_date'], name='campaigns_start_d_5c7483_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['project', 'start_date'], name='campaigns_project_12f5e3_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['project', 'is_active'], name='automation__project_8acb42_idx'),
        ),
        migrations.AddIndex(
            model_name='automationtrigger',
            index=models.Index(fields=['trigger_type', 'is_active'], name='automation__trigger_e4b5fd_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['campaign', '-triggered_at'], name='automation__campaig_524b51_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['trigger', '-triggered_at'], name='automation__trigger_639c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='automationexecution',
            index=models.Index(fields=['executed_successfully'], name='automation__execute_2bd21c_idx'),
        ),
    ]
