# Generated by Django 4.2.23 on 2026-03-04 10:54

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('chat', '0001_initial'), ('chat', '0002_initial')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('private', 'Private Chat'), ('group', 'Group Chat')], default='private', help_text='Type of chat: private (1-on-1) or group', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Name for group chats (optional for private chats)', max_length=200, null=True)),
                ('project', models.ForeignKey(help_text='Project this chat belongs to (required)', on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, default='', help_text='Text content of the message')),
                ('has_attachments', models.BooleanField(default=False, help_text='Whether this message has attachments (for optimization)')),
                ('forwarded_from_sender_display', models.CharField(blank=True, help_text='Snapshot of original sender display name at forward time', max_length=255, null=True)),
                ('forwarded_from_created_at', models.DateTimeField(blank=True, help_text='Snapshot of original message creation time at forward time', null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat')),
                ('forwarded_from_message', models.ForeignKey(blank=True, help_text='Original message that this message was forwarded from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='chat.message')),
                ('sender', models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this chat')),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Last time the user read messages in this chat (for quick unread count)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is still active in the chat')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', help_text='Current status of the message for this user', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the message was delivered to the user', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user read the message', null=True)),
                ('message', models.ForeignKey(help_text='The message this status refers to', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.message')),
                ('user', models.ForeignKey(help_text='The recipient user', on_delete=django.db.models.deletion.CASCADE, related_name='message_statuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Message statuses',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'status'], name='chat_messag_message_af4e97_idx'), models.Index(fields=['user', 'status'], name='chat_messag_user_id_5081a2_idx'), models.Index(fields=['message', 'user'], name='chat_messag_message_c98ef4_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(help_text='The uploaded file', upload_to=chat.models.temp_attachment_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='document', help_text='Type of attachment: image, video, or document', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', help_text='MIME type of the file', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for images and videos', null=True, upload_to='chat/thumbnails/')),
                ('message', models.ForeignKey(blank=True, help_text='The message this attachment belongs to (null for temp uploads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
                ('uploader', models.ForeignKey(help_text='User who uploaded this attachment', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='chat_messag_message_a261d7_idx'), models.Index(fields=['uploader', 'created_at'], name='chat_messag_uploade_c87818_idx'), models.Index(fields=['file_type'], name='chat_messag_file_ty_820d59_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'created_at'], name='chat_messag_chat_id_0c7b25_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='chat_messag_sender__b02346_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', '-created_at'], name='chat_messag_chat_id_013eed_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'is_active'], name='chat_chatpa_user_id_7c5807_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat', 'is_active'], name='chat_chatpa_chat_id_38ce59_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat', 'user')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['project', '-updated_at'], name='chat_chat_project_a6870a_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', '-updated_at'], name='chat_chat_type_4d953f_idx'),
        ),
    ]
