# Generated by Django 4.2.23 on 2026-02-18 09:55

import chat.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('private', 'Private Chat'), ('group', 'Group Chat')], default='private', help_text='Type of chat: private (1-on-1) or group', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Name for group chats (optional for private chats)', max_length=200, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True, help_text='When the user joined this chat')),
                ('last_read_at', models.DateTimeField(blank=True, help_text='Last time the user read messages in this chat (for quick unread count)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this user is still active in the chat')),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True, default='', help_text='Text content of the message')),
                ('has_attachments', models.BooleanField(default=False, help_text='Whether this message has attachments (for optimization)')),
                ('forwarded_from_sender_display', models.CharField(blank=True, help_text='Snapshot of original sender display name at forward time', max_length=255, null=True)),
                ('forwarded_from_created_at', models.DateTimeField(blank=True, help_text='Snapshot of original message creation time at forward time', null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(help_text='The uploaded file', upload_to=chat.models.temp_attachment_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='document', help_text='Type of attachment: image, video, or document', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', help_text='MIME type of the file', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for images and videos', null=True, upload_to='chat/thumbnails/')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read')], default='sent', help_text='Current status of the message for this user', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When the message was delivered to the user', null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the user read the message', null=True)),
                ('message', models.ForeignKey(help_text='The message this status refers to', on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='chat.message')),
            ],
            options={
                'verbose_name_plural': 'Message statuses',
                'ordering': ['created_at'],
            },
        ),
    ]
