# Generated by Django 4.2.23 on 2026-01-17 11:14

import chat.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_attachments',
            field=models.BooleanField(default=False, help_text='Whether this message has attachments (for optimization)'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Text content of the message'),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('file', models.FileField(help_text='The uploaded file', upload_to=chat.models.temp_attachment_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], default='document', help_text='Type of attachment: image, video, or document', max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('original_filename', models.CharField(help_text='Original filename as uploaded', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', help_text='MIME type of the file', max_length=100)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for images and videos', null=True, upload_to='chat/thumbnails/')),
                ('message', models.ForeignKey(blank=True, help_text='The message this attachment belongs to (null for temp uploads)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message')),
                ('uploader', models.ForeignKey(help_text='User who uploaded this attachment', on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message', 'created_at'], name='chat_messag_message_a261d7_idx'), models.Index(fields=['uploader', 'created_at'], name='chat_messag_uploade_c87818_idx'), models.Index(fields=['file_type'], name='chat_messag_file_ty_820d59_idx')],
            },
        ),
    ]
