# Generated by Django 4.2 on 2026-02-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_message_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='forwarded_from_created_at',
            field=models.DateTimeField(blank=True, help_text='Snapshot of original message creation time at forward time', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from_message',
            field=models.ForeignKey(blank=True, db_index=True, help_text='Original message that this message was forwarded from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_messages', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='forwarded_from_sender_display',
            field=models.CharField(blank=True, help_text='Snapshot of original sender display name at forward time', max_length=255, null=True),
        ),
    ]
