# Generated by Django 4.2.23 on 2025-11-04 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokCreative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('music', 'Music')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('preview_url', models.URLField(max_length=1000)),
                ('scan_status', django_fsm.FSMField(choices=[('incoming', 'Incoming - File just uploaded'), ('scanning', 'Scanning - Virus scan in progress'), ('ready', 'Ready - File is safe and available'), ('infected', 'Infected - File contains virus/malware'), ('missing', 'Missing - File missing from storage'), ('error_scanning', 'ErrorScanning - Scanner error occurred')], default='incoming', max_length=20, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_tiktok_creatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Creative',
                'verbose_name_plural': 'TikTok Creatives',
                'db_table': 'tiktok_creative',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gid', models.CharField(blank=True, db_index=True, help_text='External display ID (e.g., G-2025-0001)', max_length=20, null=True, unique=True)),
                ('name', models.CharField(help_text='Group name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_ad_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Ad Group',
                'verbose_name_plural': 'TikTok Ad Groups',
                'db_table': 'tiktok_ad_group',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AdDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aid', models.CharField(blank=True, db_index=True, help_text='External display ID (e.g., AD-2025-001001)', max_length=20, null=True, unique=True)),
                ('name', models.CharField(blank=True, help_text='Ad internal name', max_length=255, null=True)),
                ('ad_text', models.TextField(blank=True, help_text='Ad text/copy', null=True)),
                ('call_to_action', models.CharField(blank=True, help_text="CTA as single value: None=OFF, ''=DYNAMIC, non-empty=STANDARD label", max_length=100, null=True)),
                ('creative_type', models.CharField(blank=True, choices=[('SINGLE_VIDEO', 'Single Video'), ('SINGLE_IMAGE', 'Single Image'), ('CAROUSEL_VIDEO', 'Carousel Video'), ('CAROUSEL_IMAGE', 'Carousel Image')], help_text='Creative type (e.g., SINGLE_VIDEO, SINGLE_IMAGE)', max_length=20, null=True)),
                ('opt_status', models.IntegerField(default=0, help_text='Optimization status')),
                ('assets', models.JSONField(blank=True, default=dict, help_text='Asset information including primary creative and image list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_group', models.ForeignKey(blank=True, help_text='Ad group this draft belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_drafts', to='tiktok.adgroup')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiktok_ad_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Ad Draft',
                'verbose_name_plural': 'TikTok Ad Drafts',
                'db_table': 'tiktok_ad_draft',
                'ordering': ['-updated_at'],
            },
        ),
    ]
