# Generated by Django 4.2.23 on 2025-10-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TikTokCreative',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('music', 'Music')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('preview_url', models.URLField(max_length=1000)),
                ('scan_status', models.CharField(choices=[('incoming', 'Incoming - File just uploaded'), ('scanning', 'Scanning - Virus scan in progress'), ('ready', 'Ready - File is safe and available'), ('infected', 'Infected - File contains virus/malware'), ('missing', 'Missing - File missing from storage'), ('error_scanning', 'ErrorScanning - Scanner error occurred')], default='incoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_tiktok_creatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TikTok Creative',
                'verbose_name_plural': 'TikTok Creatives',
                'db_table': 'tiktok_creative',
                'ordering': ['-created_at'],
            },
        ),
    ]
