# Generated by Django 4.2.23 on 2025-11-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPreview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(db_index=True, max_length=64, unique=True)),
                ('version_id', models.CharField(help_text='Version identifier at time of snapshot', max_length=64)),
                ('snapshot_json', models.JSONField(help_text='Minimal state to render preview, including signed media URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ad_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_previews', to='tiktok.addraft')),
            ],
            options={
                'db_table': 'tiktok_public_preview',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='tiktok_publ_slug_7a212b_idx'), models.Index(fields=['ad_draft', 'created_at'], name='tiktok_publ_ad_draf_8db347_idx')],
            },
        ),
    ]
