# Generated by Django 4.2.23 on 2025-11-25 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiktok', '0003_add_expires_at_to_publicpreview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='publicpreview',
            new_name='tiktok_publ_expires_d8ddf7_idx',
            old_name='tiktok_publ_expires_abc123_idx',
        ),
    ]
