# Generated by Django 4.2.23 on 2026-04-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0002_meetingdocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetingdocument",
            name="yjs_state",
            field=models.TextField(blank=True, default=""),
        ),
    ]
