# Generated by Django 4.2.23 on 2026-04-01 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0003_drop_meetingtemplate_block_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='meetingtemplate',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingtemplate',
            name='id',
            field=models.CharField(default=meetings.models._meeting_template_id, editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
