# Generated by Django 4.2.23 on 2026-04-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0004_artifactlink_lookup_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Soft-delete flag (added in migration 0002)."
            ),
        ),
    ]
