# Generated by Django 4.2.23 on 2026-04-07 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0005_merge_meetingdocument_yjs_and_template_user"),
        ("meetings", "0006_merge_meetingdocument_and_knowledge_preservation"),
    ]

    operations = []
