# Generated by Django 4.2.23 on 2025-08-05 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrospectiveTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("reported", "Reported"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        help_text="Current status of the retrospective task",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the retrospective was scheduled",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the retrospective analysis started",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the retrospective analysis completed",
                        null=True,
                    ),
                ),
                (
                    "report_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the generated report (PDF/PPT)",
                        null=True,
                    ),
                ),
                (
                    "report_generated_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was generated", null=True
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the report was reviewed", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        help_text="Campaign this retrospective is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="retrospectives",
                        to="campaigns.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this retrospective",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_retrospectives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed and approved the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_retrospectives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Retrospective Task",
                "verbose_name_plural": "Retrospective Tasks",
                "ordering": ["-scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the insight", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the insight"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        help_text="Severity level of the insight",
                        max_length=20,
                    ),
                ),
                (
                    "rule_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the rule that triggered this insight",
                        max_length=100,
                    ),
                ),
                (
                    "triggered_kpis",
                    models.JSONField(
                        default=list,
                        help_text="List of KPI IDs that triggered this insight",
                    ),
                ),
                (
                    "suggested_actions",
                    models.JSONField(
                        default=list,
                        help_text="List of suggested actions to address the insight",
                    ),
                ),
                (
                    "generated_by",
                    models.CharField(
                        choices=[
                            ("rule_engine", "Rule Engine"),
                            ("manual", "Manual Entry"),
                            ("ai", "AI Generated"),
                        ],
                        default="rule_engine",
                        help_text="How this insight was generated",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this insight (if manual)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retrospective",
                    models.ForeignKey(
                        help_text="Retrospective task this insight belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="retrospective.retrospectivetask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight",
                "verbose_name_plural": "Insights",
                "ordering": ["-severity", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="retrospectivetask",
            index=models.Index(
                fields=["status", "scheduled_at"], name="retrospecti_status_3efe7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrospectivetask",
            index=models.Index(
                fields=["campaign", "status"], name="retrospecti_campaig_3f0f99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrospectivetask",
            index=models.Index(
                fields=["created_by", "status"], name="retrospecti_created_ba13fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["severity", "created_at"], name="retrospecti_severit_2574cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["rule_id", "severity"], name="retrospecti_rule_id_a821de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["generated_by", "created_at"],
                name="retrospecti_generat_1c62f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["retrospective", "severity"],
                name="retrospecti_retrosp_8314b3_idx",
            ),
        ),
    ]
