# Generated by Django 4.2.23 on 2025-09-10 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("retrospective", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="retrospectivetask",
            options={
                "ordering": ["-scheduled_at"],
                "permissions": [
                    ("approve_report", "Can approve retrospective reports")
                ],
                "verbose_name": "Retrospective Task",
                "verbose_name_plural": "Retrospective Tasks",
            },
        ),
    ]
