# Generated by Django 4.2.23 on 2025-10-15 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of this reusable block.', max_length=255)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('button', 'Button'), ('divider', 'Divider'), ('html', 'Custom HTML')], default='text', help_text='Type of the content block (text, image, etc.).', max_length=50)),
                ('props', models.JSONField(default=dict, help_text='JSON configuration and content data for the block.')),
                ('shared', models.BooleanField(default=False, help_text='If true, block can be reused across multiple drafts.')),
                ('editable', models.BooleanField(default=True, help_text='Whether the block is editable inside drafts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who created this content block.', on_delete=django.db.models.deletion.CASCADE, related_name='created_blocks', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, help_text='User who last modified this content block.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Block',
                'verbose_name_plural': 'Content Blocks',
                'db_table': 'content_blocks',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(help_text='Subject line of the email.', max_length=200)),
                ('content_blocks', models.JSONField(default=list, help_text='JSON array of inline (non-reusable) blocks inside this email.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_email_drafts', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_email_drafts', to=settings.AUTH_USER_MODEL)),
                ('reusable_blocks', models.ManyToManyField(blank=True, help_text='Reusable content blocks linked to this email draft.', related_name='used_in_drafts', to='klaviyo_draft.contentblock')),
            ],
            options={
                'verbose_name': 'Email Draft',
                'verbose_name_plural': 'Email Drafts',
                'db_table': 'email_drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('triggers', models.JSONField(default=list)),
                ('actions', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('email_drafts', models.ManyToManyField(blank=True, help_text='Email drafts used in this workflow.', related_name='workflows', to='klaviyo_draft.emaildraft')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriggerLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_data', models.JSONField(default=dict)),
                ('execution_status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_log', models.JSONField(default=list)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_workflows', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_logs', to='klaviyo_draft.workflow')),
            ],
            options={
                'db_table': 'trigger_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PreviewLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('context_used', models.JSONField(default=dict)),
                ('rendered_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previewed_drafts', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='klaviyo_draft.emaildraft')),
            ],
            options={
                'db_table': 'preview_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
