import { useEffect, useState } from "react";
import { derivedEventToEventDTO } from "@/lib/api/calendarApi";
import {
  CalendarAPI,
  CalendarDTO,
  CalendarViewResponse,
  CalendarViewType,
  EventDTO,
} from "@/lib/api/calendarApi";
import { addDays, startOfDay, startOfWeek } from "date-fns";

interface UseCalendarViewOptions {
  viewType: CalendarViewType;
  currentDate: Date;
  calendarIds?: string[];
}

interface UseCalendarViewResult {
  events: EventDTO[];
  calendars: CalendarDTO[];
  isLoading: boolean;
  error: Error | null;
  refetch: () => void;
}

const cache = new Map<string, CalendarViewResponse>();

function buildCacheKey(opts: UseCalendarViewOptions): string {
  const { viewType, currentDate, calendarIds } = opts;
  const baseDate = startOfDay(currentDate).toISOString();
  const ids = (calendarIds || []).slice().sort().join(",");
  return `${viewType}:${baseDate}:${ids}`;
}

export function useCalendarView(
  options: UseCalendarViewOptions,
): UseCalendarViewResult {
  const [events, setEvents] = useState<EventDTO[]>([]);
  const [calendars, setCalendars] = useState<CalendarDTO[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<Error | null>(null);

  const { viewType, currentDate, calendarIds } = options;

  const key = buildCacheKey(options);

  const load = () => {
    setIsLoading(true);
    setError(null);

    const existing = cache.get(key);
    if (existing) {
      setEvents(existing.events);
      setCalendars(existing.calendars);
      setIsLoading(false);
      return;
    }

    let request;
    if (viewType === "day") {
      const start = startOfDay(currentDate);
      const end = addDays(start, 1);
      request = CalendarAPI.getAgendaView({
        start_date: start.toISOString(),
        end_date: end.toISOString(),
        calendar_ids: calendarIds,
      });
    } else if (viewType === "week") {
      const start = startOfWeek(currentDate, { weekStartsOn: 1 });
      const end = addDays(start, 7);
      request = CalendarAPI.getAgendaView({
        start_date: start.toISOString(),
        end_date: end.toISOString(),
        calendar_ids: calendarIds,
      });
    } else if (viewType === "month") {
      request = CalendarAPI.getMonthView({
        year: currentDate.getFullYear(),
        month: currentDate.getMonth() + 1,
        calendar_ids: calendarIds,
      });
    } else {
      // agenda & year reuse agenda endpoint for now.
      const start = startOfDay(currentDate);
      const end = new Date(start);
      end.setDate(end.getDate() + (viewType === "agenda" ? 7 : 365));
      request = CalendarAPI.getAgendaView({
        start_date: start.toISOString(),
        end_date: end.toISOString(),
        calendar_ids: calendarIds,
      });
    }

    request
      .then(async (response) => {
      cache.set(key, response.data);

    // Also get derived events (events automatically generated by Decision/Task)
      let derivedEvents: EventDTO[] = [];
      try {
      // 计算当前视图的时间范围
        let start: string;
        let end: string;
        if (viewType === "day") {
          start = startOfDay(currentDate).toISOString();
          end = addDays(startOfDay(currentDate), 1).toISOString();
        } else if (viewType === "week") {
          const weekStart = startOfWeek(currentDate, { weekStartsOn: 1 });
          start = weekStart.toISOString();
          end = addDays(weekStart, 7).toISOString();
        } else if (viewType === "month") {
          start = new Date(currentDate.getFullYear(), currentDate.getMonth(), 1).toISOString();
          end = new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1).toISOString();
      } else {
        start = startOfDay(currentDate).toISOString();
        end = addDays(startOfDay(currentDate), 7).toISOString();
      }

      const derivedResponse = await CalendarAPI.getDerivedEvents({ start, end });
      derivedEvents = derivedResponse.data.map(derivedEventToEventDTO);
    } catch {
      // derived events Failure to obtain does not affect the display of the main calendar
      console.warn("Failed to load derived calendar events");
    }

    setEvents([...response.data.events, ...derivedEvents]);
    setCalendars(response.data.calendars);
  })
      

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);

  const refetch = () => {
    cache.delete(key);
    load();
  };

  return { events, calendars, isLoading, error, refetch };
}
