# Generated by Django 4.2.23 on 2026-01-26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0022_add_platform_policy_update_task_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPolicyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google_ads', 'Google Ads'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('other', 'Other')], help_text='The advertising platform that updated its policies', max_length=50)),
                ('policy_change_type', models.CharField(choices=[('targeting_rules', 'Targeting Rules'), ('content_policy', 'Content Policy'), ('privacy_policy', 'Privacy Policy'), ('ad_placement', 'Ad Placement'), ('budget_policy', 'Budget Policy'), ('compliance_requirement', 'Compliance Requirement'), ('data_usage', 'Data Usage'), ('other', 'Other')], help_text='Type of policy change (e.g., targeting rules, content policy)', max_length=50)),
                ('policy_description', models.TextField(help_text='Detailed description of the policy change and its implications')),
                ('policy_reference_url', models.URLField(blank=True, help_text='Link to official policy documentation or announcement', max_length=500, null=True)),
                ('effective_date', models.DateField(blank=True, help_text='Date when the policy change takes effect', null=True)),
                ('affected_campaigns', models.JSONField(blank=True, default=list, help_text='List of affected campaign IDs, names, or identifiers')),
                ('affected_ad_sets', models.JSONField(blank=True, default=list, help_text='List of affected ad set IDs, names, or identifiers')),
                ('affected_assets', models.JSONField(blank=True, default=list, help_text='List of affected asset IDs or references')),
                ('performance_impact', models.TextField(blank=True, help_text='Description of potential impact on campaign performance metrics')),
                ('budget_impact', models.TextField(blank=True, help_text='Description of potential impact on budget allocation or spending')),
                ('compliance_risk', models.TextField(blank=True, help_text='Assessment of compliance risks if actions are not taken')),
                ('immediate_actions_required', models.TextField(help_text='Immediate actions needed to remain compliant with the new policy')),
                ('action_deadline', models.DateField(blank=True, help_text='Deadline for completing immediate actions', null=True)),
                ('mitigation_status', models.CharField(choices=[('not_started', 'Not Started'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='not_started', help_text='Current status of mitigation efforts', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True, help_text='Detailed plan for mitigating the impact of the policy change')),
                ('mitigation_steps', models.JSONField(blank=True, default=list, help_text="List of mitigation steps with status tracking. Format: [{'step': 'description', 'status': 'pending|in_progress|completed', 'assigned_to': user_id, 'completed_at': datetime}]")),
                ('mitigation_execution_notes', models.TextField(blank=True, help_text='Notes on the execution of mitigation steps')),
                ('mitigation_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when mitigation was completed', null=True)),
                ('mitigation_results', models.TextField(blank=True, help_text='Results and outcomes of the mitigation efforts')),
                ('post_mitigation_review', models.TextField(blank=True, help_text='Review after mitigation to ensure all impacts were addressed')),
                ('review_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when post-mitigation review was completed', null=True)),
                ('all_impacts_addressed', models.BooleanField(default=False, help_text='Whether all impacts have been addressed and verified')),
                ('lessons_learned', models.TextField(blank=True, help_text='Lessons learned for handling future platform policy updates')),
                ('notes', models.TextField(blank=True, help_text='Additional notes linking to relevant campaigns, assets, or policy documentation')),
                ('related_references', models.JSONField(blank=True, default=list, help_text='Links or references to campaigns, assets, policy documentation, or external resources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for handling this policy update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_policy_updates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this policy update task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_updates', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who completed the post-mitigation review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Policy Update',
                'verbose_name_plural': 'Platform Policy Updates',
                'db_table': 'platform_policy_update',
                'ordering': ['-created_at'],
            },
        ),
    ]
