# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformPolicyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google_ads', 'Google Ads'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('other', 'Other')], help_text='Advertising platform that issued the policy update', max_length=50)),
                ('policy_change_type', models.CharField(choices=[('targeting_rules', 'Targeting Rules'), ('content_policy', 'Content Policy'), ('privacy_policy', 'Privacy Policy'), ('ad_placement', 'Ad Placement'), ('budget_policy', 'Budget Policy'), ('compliance_requirement', 'Compliance Requirement'), ('data_usage', 'Data Usage'), ('other', 'Other')], help_text='Type of policy change', max_length=50)),
                ('policy_description', models.TextField(help_text='Detailed description of the policy change and implications')),
                ('policy_reference_url', models.URLField(blank=True, help_text='Official platform policy or announcement URL', max_length=500, null=True)),
                ('effective_date', models.DateField(blank=True, help_text='Date when the policy change becomes effective', null=True)),
                ('affected_campaigns', models.JSONField(blank=True, default=list, help_text='Affected campaign identifiers (IDs, names, external refs)')),
                ('affected_ad_sets', models.JSONField(blank=True, default=list, help_text='Affected ad set identifiers')),
                ('affected_assets', models.JSONField(blank=True, default=list, help_text='Affected asset identifiers or references')),
                ('performance_impact', models.TextField(blank=True, help_text='Potential impact on performance metrics')),
                ('budget_impact', models.TextField(blank=True, help_text='Potential impact on budget or spend')),
                ('compliance_risk', models.TextField(blank=True, help_text='Risk if policy change is not addressed')),
                ('immediate_actions_required', models.TextField(help_text='Immediate actions required to remain compliant')),
                ('action_deadline', models.DateField(blank=True, help_text='Deadline for required immediate actions', null=True)),
                ('mitigation_status', models.CharField(choices=[('not_started', 'Not Started'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='not_started', help_text='Current mitigation lifecycle status', max_length=20)),
                ('mitigation_plan', models.TextField(blank=True, help_text='Mitigation planning notes')),
                ('mitigation_steps', models.JSONField(blank=True, default=list, help_text="Step-level mitigation tracking. Example: [{'step': '...', 'status': 'pending|in_progress|completed', 'assigned_to': <user_id|null>, 'completed_at': <iso8601|null>}]")),
                ('mitigation_execution_notes', models.TextField(blank=True, help_text='Execution notes during mitigation')),
                ('mitigation_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when mitigation was completed', null=True)),
                ('mitigation_results', models.TextField(blank=True, help_text='Results or outcomes after mitigation')),
                ('post_mitigation_review', models.TextField(blank=True, help_text='Review notes after mitigation completion')),
                ('review_completed_at', models.DateTimeField(blank=True, help_text='Timestamp when review was completed', null=True)),
                ('all_impacts_addressed', models.BooleanField(default=False, help_text='Whether all identified impacts were addressed')),
                ('lessons_learned', models.TextField(blank=True, help_text='Lessons learned for future policy updates')),
                ('notes', models.TextField(blank=True, help_text='Additional notes (may include links)')),
                ('related_references', models.JSONField(blank=True, default=list, help_text='Additional related references or external links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for handling this policy update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_platform_policy_updates', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this policy update record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_policy_updates', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Reviewer of the post-mitigation outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_platform_policy_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'platform_policy_update',
                'ordering': ['-created_at'],
            },
        ),
    ]
