# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('task', '0001_initial'),
        ('policy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformpolicyupdate',
            name='task',
            field=models.OneToOneField(blank=True, help_text='Associated workflow task (type = platform_policy_update)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_policy_update', to='task.task'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['platform', 'mitigation_status'], name='platform_po_platfor_2296bf_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['assigned_to', 'mitigation_status'], name='platform_po_assigne_57aa26_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['effective_date'], name='platform_po_effecti_b23c60_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['created_at'], name='platform_po_created_ff6ba1_idx'),
        ),
    ]
