# Generated by Django 4.2.23 on 2026-01-29 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0022_add_platform_policy_update_task_type'),
        ('policy', '0002_wipe_platform_policy_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platformpolicyupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='platformpolicyupdate',
            name='task',
            field=models.OneToOneField(blank=True, help_text='Associated workflow task (type = platform_policy_update)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform_policy_update', to='task.task'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='action_deadline',
            field=models.DateField(blank=True, help_text='Deadline for required immediate actions', null=True),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='affected_ad_sets',
            field=models.JSONField(blank=True, default=list, help_text='Affected ad set identifiers'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='affected_assets',
            field=models.JSONField(blank=True, default=list, help_text='Affected asset identifiers or references'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='affected_campaigns',
            field=models.JSONField(blank=True, default=list, help_text='Affected campaign identifiers (IDs, names, external refs)'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='all_impacts_addressed',
            field=models.BooleanField(default=False, help_text='Whether all identified impacts were addressed'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User responsible for handling this policy update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_platform_policy_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='budget_impact',
            field=models.TextField(blank=True, help_text='Potential impact on budget or spend'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='compliance_risk',
            field=models.TextField(blank=True, help_text='Risk if policy change is not addressed'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this policy update record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_platform_policy_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date when the policy change becomes effective', null=True),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='immediate_actions_required',
            field=models.TextField(help_text='Immediate actions required to remain compliant'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Lessons learned for future policy updates'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='mitigation_execution_notes',
            field=models.TextField(blank=True, help_text='Execution notes during mitigation'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='mitigation_plan',
            field=models.TextField(blank=True, help_text='Mitigation planning notes'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='mitigation_results',
            field=models.TextField(blank=True, help_text='Results or outcomes after mitigation'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='mitigation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='not_started', help_text='Current mitigation lifecycle status', max_length=20),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='mitigation_steps',
            field=models.JSONField(blank=True, default=list, help_text="Step-level mitigation tracking. Example: [{'step': '...', 'status': 'pending|in_progress|completed', 'assigned_to': <user_id|null>, 'completed_at': <iso8601|null>}]"),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes (may include links)'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='performance_impact',
            field=models.TextField(blank=True, help_text='Potential impact on performance metrics'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='platform',
            field=models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google_ads', 'Google Ads'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter/X'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('other', 'Other')], help_text='Advertising platform that issued the policy update', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='policy_change_type',
            field=models.CharField(choices=[('targeting_rules', 'Targeting Rules'), ('content_policy', 'Content Policy'), ('privacy_policy', 'Privacy Policy'), ('ad_placement', 'Ad Placement'), ('budget_policy', 'Budget Policy'), ('compliance_requirement', 'Compliance Requirement'), ('data_usage', 'Data Usage'), ('other', 'Other')], help_text='Type of policy change', max_length=50),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='policy_description',
            field=models.TextField(help_text='Detailed description of the policy change and implications'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='policy_reference_url',
            field=models.URLField(blank=True, help_text='Official platform policy or announcement URL', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='post_mitigation_review',
            field=models.TextField(blank=True, help_text='Review notes after mitigation completion'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='related_references',
            field=models.JSONField(blank=True, default=list, help_text='Additional related references or external links'),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='review_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when review was completed', null=True),
        ),
        migrations.AlterField(
            model_name='platformpolicyupdate',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Reviewer of the post-mitigation outcome', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_platform_policy_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['platform', 'mitigation_status'], name='platform_po_platfor_2296bf_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['assigned_to', 'mitigation_status'], name='platform_po_assigne_57aa26_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['effective_date'], name='platform_po_effecti_b23c60_idx'),
        ),
        migrations.AddIndex(
            model_name='platformpolicyupdate',
            index=models.Index(fields=['created_at'], name='platform_po_created_ff6ba1_idx'),
        ),
    ]
