# Generated by Django 4.2.23 on 2025-10-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsPhotoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, default='', help_text='图片描述')),
                ('image_hash', models.CharField(blank=True, default='', help_text='图片hash值', max_length=255)),
                ('url', models.CharField(blank=True, default='', help_text='图片URL', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleAdsVideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='YouTube Video', help_text='视频标题', max_length=255)),
                ('video_id', models.CharField(blank=True, default='', help_text='YouTube视频ID', max_length=64)),
                ('image_url', models.CharField(blank=True, default='', help_text='缩略图URL (placeholder)', max_length=512)),
                ('message', models.TextField(blank=True, default='', help_text='视频描述')),
            ],
        ),
    ]
