# Generated by Django 4.2.23 on 2025-10-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0002_googleadsphotodata_googleadsvideodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsivedisplayadinfo',
            name='logo_images',
            field=models.ManyToManyField(blank=True, help_text='Logo images to be used in the ad', related_name='responsive_display_ad_logo_images', to='google_ads.googleadsphotodata'),
        ),
        migrations.AlterField(
            model_name='responsivedisplayadinfo',
            name='marketing_images',
            field=models.ManyToManyField(blank=True, help_text='Marketing images to be used in the ad', related_name='responsive_display_ad_marketing_images', to='google_ads.googleadsphotodata'),
        ),
        migrations.AlterField(
            model_name='responsivedisplayadinfo',
            name='square_logo_images',
            field=models.ManyToManyField(blank=True, help_text='Square logo images to be used in the ad', related_name='responsive_display_ad_square_logo_images', to='google_ads.googleadsphotodata'),
        ),
        migrations.AlterField(
            model_name='responsivedisplayadinfo',
            name='square_marketing_images',
            field=models.ManyToManyField(blank=True, help_text='Square marketing images to be used in the ad', related_name='responsive_display_ad_square_marketing_images', to='google_ads.googleadsphotodata'),
        ),
        migrations.AlterField(
            model_name='responsivedisplayadinfo',
            name='youtube_videos',
            field=models.ManyToManyField(blank=True, help_text='Optional YouTube videos for the ad', related_name='responsive_display_ad_youtube_videos', to='google_ads.googleadsvideodata'),
        ),
    ]
