# Generated by Django 4.2.23 on 2025-10-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0003_alter_responsivedisplayadinfo_logo_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoresponsiveadinfo',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text='YouTube video asset used for the ad (only one value supported)', related_name='video_responsive_ad_videos', to='google_ads.googleadsvideodata'),
        ),
    ]
