# Generated by Django 4.2.23 on 2025-10-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0004_alter_videoresponsiveadinfo_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published'), ('PAUSED', 'Paused')], default='DRAFT', help_text='Ad status for workflow management', max_length=20),
        ),
    ]
