# Generated by Django 4.2.23 on 2025-10-25 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0005_alter_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoadinfo',
            name='video_asset',
            field=models.ForeignKey(blank=True, help_text='The Asset resource name of this video (GoogleAdsVideoData)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='google_ads.googleadsvideodata'),
        ),
        migrations.AlterField(
            model_name='videoresponsiveadinfo',
            name='companion_banners',
            field=models.ManyToManyField(blank=True, help_text='Image asset used for the companion banner (only one value supported)', related_name='video_responsive_ad_companion_banners', to='google_ads.googleadsphotodata'),
        ),
    ]
