# Generated by Django 4.2.23 on 2025-11-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_ads', '0006_alter_videoadinfo_video_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(blank=True, help_text='Immutable. The name of the ad. This is only used to be able to identify the ad. Must be unique.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='googleadsphotodata',
            name='caption',
            field=models.TextField(blank=True, default='', help_text='Image caption'),
        ),
        migrations.AlterField(
            model_name='googleadsphotodata',
            name='image_hash',
            field=models.CharField(blank=True, default='', help_text='Image hash', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleadsphotodata',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Image URL', max_length=512),
        ),
        migrations.AlterField(
            model_name='googleadsvideodata',
            name='image_url',
            field=models.CharField(blank=True, default='', help_text='Thumbnail URL (placeholder)', max_length=512),
        ),
        migrations.AlterField(
            model_name='googleadsvideodata',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Video description'),
        ),
        migrations.AlterField(
            model_name='googleadsvideodata',
            name='title',
            field=models.CharField(blank=True, default='YouTube Video', help_text='Video title', max_length=255),
        ),
        migrations.AlterField(
            model_name='googleadsvideodata',
            name='video_id',
            field=models.CharField(blank=True, default='', help_text='YouTube video ID', max_length=64),
        ),
    ]
