#!/bin/bash
set -e

# Initiate stanza-create
if [ ! -f "/var/lib/pgbackrest/archive/mediajira_db/archive.info" ]; then
  echo "Initializing pgBackRest stanza..."
  pgbackrest --stanza=mediajira_db stanza-create
fi

chown -R postgres:postgres /var/lib/pgbackrest /var/log/pgbackrest
chmod -R 755 /var/lib/pgbackrest /var/log/pgbackrest

# Keep container running
cron -f