# Generated by Django 4.2.23 on 2025-10-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailchimp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
