# Generated by Django 4.2.23 on 2025-11-25 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailchimp', '0005_campaigncomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
