# Generated by Codex on 2025-08-12

from django.db import migrations


def seed_roles_permissions(apps, schema_editor):
    Role = apps.get_model("core", "Role")
    Permission = apps.get_model("core", "Permission")
    RolePermission = apps.get_model("access_control", "RolePermission")

    db_alias = schema_editor.connection.alias

    role_levels = {
        "Super Administrator": 1,
        "Organization Admin": 2,
        "Team Leader": 3,
        "Campaign Manager": 4,
        "Budget Controller": 5,
        "Approver": 6,
        "Reviewer": 7,
        "Data Analyst": 8,
        "Senior Media Buyer": 9,
        "Specialist Media Buyer": 10,
        "Junior Media Buyer": 11,
        "Designer": 12,
        "Copywriter": 13,
    }

    modules = [
        "ASSET",
        "CAMPAIGN",
        "BUDGET_REQUEST",
        "BUDGET_POOL",
        "BUDGET_ESCALATION",
    ]
    actions = ["VIEW", "EDIT", "APPROVE", "DELETE", "EXPORT"]

    permissions = {}
    for module in modules:
        for action in actions:
            perm, _ = Permission.objects.using(db_alias).get_or_create(
                module=module,
                action=action,
            )
            permissions[(module, action)] = perm

    roles = {}
    for name, level in role_levels.items():
        role, created = Role.objects.using(db_alias).get_or_create(
            name=name,
            organization=None,
            defaults={"level": level},
        )
        if not created and role.level != level:
            role.level = level
            role.save(update_fields=["level"])
        roles[name] = role

    role_permissions = {
        "Super Administrator": {module: actions for module in modules},
        "Super Administrator": {module: actions for module in modules},
        "Team Leader": {
            "ASSET": ["VIEW", "EDIT", "APPROVE", "EXPORT"],
            "CAMPAIGN": ["VIEW", "EDIT", "APPROVE", "EXPORT"],
            "BUDGET_REQUEST": ["VIEW", "EDIT", "APPROVE", "EXPORT"],
            "BUDGET_POOL": ["VIEW", "EDIT"],
            "BUDGET_ESCALATION": ["VIEW", "APPROVE"],
        },
        "Campaign Manager": {
            "ASSET": ["VIEW", "EDIT"],
            "CAMPAIGN": ["VIEW", "EDIT", "APPROVE", "EXPORT"],
            "BUDGET_REQUEST": ["VIEW", "EDIT"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
        "Budget Controller": {
            "ASSET": ["VIEW"],
            "CAMPAIGN": ["VIEW"],
            "BUDGET_REQUEST": ["VIEW", "EDIT", "APPROVE", "EXPORT"],
            "BUDGET_POOL": ["VIEW", "EDIT", "APPROVE", "EXPORT"],
            "BUDGET_ESCALATION": ["VIEW", "APPROVE"],
        },
        "Data Analyst": {
            "ASSET": ["VIEW", "EXPORT"],
            "CAMPAIGN": ["VIEW", "EXPORT"],
            "BUDGET_REQUEST": ["VIEW", "EXPORT"],
            "BUDGET_POOL": ["VIEW", "EXPORT"],
            "BUDGET_ESCALATION": ["VIEW", "EXPORT"],
        },
        "Reviewer": {
            "ASSET": ["VIEW", "APPROVE"],
            "CAMPAIGN": ["VIEW"],
            "BUDGET_REQUEST": ["VIEW"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
        "Approver": {
            "ASSET": ["VIEW", "APPROVE"],
            "CAMPAIGN": ["VIEW", "APPROVE"],
            "BUDGET_REQUEST": ["VIEW", "APPROVE"],
            "BUDGET_POOL": ["VIEW", "APPROVE"],
            "BUDGET_ESCALATION": ["VIEW", "APPROVE"],
        },
        "Senior Media Buyer": {
            "ASSET": ["VIEW", "EDIT"],
            "CAMPAIGN": ["VIEW", "EDIT"],
            "BUDGET_REQUEST": ["VIEW", "EDIT"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
        "Specialist Media Buyer": {
            "ASSET": ["VIEW", "EDIT"],
            "CAMPAIGN": ["VIEW", "EDIT"],
            "BUDGET_REQUEST": ["VIEW"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
        "Junior Media Buyer": {
            "ASSET": ["VIEW"],
            "CAMPAIGN": ["VIEW"],
            "BUDGET_REQUEST": ["VIEW"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
        "Designer": {
            "ASSET": ["VIEW", "EDIT", "EXPORT"],
            "CAMPAIGN": ["VIEW"],
            "BUDGET_REQUEST": ["VIEW"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
        "Copywriter": {
            "ASSET": ["VIEW", "EDIT"],
            "CAMPAIGN": ["VIEW"],
            "BUDGET_REQUEST": ["VIEW"],
            "BUDGET_POOL": ["VIEW"],
            "BUDGET_ESCALATION": ["VIEW"],
        },
    }

    for role_name, module_actions in role_permissions.items():
        role = roles[role_name]
        for module, action_list in module_actions.items():
            for action in action_list:
                perm = permissions[(module, action)]
                role_perm, created = RolePermission.objects.using(db_alias).get_or_create(
                    role=role,
                    permission=perm,
                )
                if not created and role_perm.is_deleted:
                    role_perm.is_deleted = False
                    role_perm.save(update_fields=["is_deleted"])


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0001_initial"),
        ("core", "0008_rename_core_projec_email_abc123_idx_core_projec_email_45393c_idx_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_roles_permissions, migrations.RunPython.noop),
    ]
