# Generated by Django 5.2.6 on 2025-09-15 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the experiment', max_length=255)),
                ('experiment_type', models.CharField(choices=[('ab_test', 'Ab Test'), ('creative_rotation', 'Creative Rotation'), ('budget_split', 'Budget Split')], help_text='The type of the experiment', max_length=255)),
                ('linked_campaign_ids', models.JSONField(help_text='The ids of the linked campaigns')),
                ('hypothesis', models.TextField(help_text='The hypothesis of the experiment')),
                ('start_date', models.DateField(help_text='The start date of the experiment')),
                ('end_date', models.DateField(help_text='The end date of the experiment')),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('rolled_back', 'Rolled Back')], default='running', help_text='The status of the experiment', max_length=255)),
                ('description', models.TextField(help_text='The description of the experiment')),
                ('created_by', models.ForeignKey(db_column='created_by', help_text='The user who created the experiment', on_delete=django.db.models.deletion.CASCADE, related_name='owned_optimization_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'optimization_experiment',
            },
        ),
        migrations.CreateModel(
            name='ScalingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('budget_increase', 'Budget Increase'), ('budget_decrease', 'Budget Decrease'), ('audience_expand', 'Audience Expand'), ('audience_narrow', 'Audience Narrow'), ('creative_replace', 'Creative Replace')], help_text='The type of the scaling action', max_length=255)),
                ('action_details', models.JSONField(help_text='The details of the scaling action')),
                ('campaign_id', models.CharField(help_text='The id of the campaign that the scaling action belongs to', max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the scaling action was performed')),
                ('experiment_id', models.ForeignKey(db_column='experiment_id', help_text='The experiment that the scaling action belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_scaling_actions', to='optimization.optimizationexperiment')),
                ('performed_by', models.ForeignKey(db_column='performed_by', help_text='The user who performed the scaling action', on_delete=django.db.models.deletion.CASCADE, related_name='performed_scaling_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scaling_action',
            },
        ),
        migrations.CreateModel(
            name='RollbackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='The reason for the rollback')),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the rollback action was performed')),
                ('performed_by', models.ForeignKey(db_column='performed_by', help_text='The user who performed the rollback action', on_delete=django.db.models.deletion.CASCADE, related_name='performed_rollback_actions', to=settings.AUTH_USER_MODEL)),
                ('scaling_action_id', models.ForeignKey(help_text='The id of the scaling action that was rolled back', on_delete=django.db.models.deletion.CASCADE, related_name='owned_rollback_histories', to='optimization.scalingaction')),
            ],
            options={
                'db_table': 'rollback_history',
            },
        ),
        migrations.CreateModel(
            name='ExperimentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='The name of the metric', max_length=255)),
                ('metric_value', models.FloatField(help_text='The value of the metric')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the metric was recorded')),
                ('experiment_id', models.ForeignKey(db_column='experiment_id', help_text='The id of the experiment that the metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='owned_experiment_metrics', to='optimization.optimizationexperiment')),
            ],
            options={
                'db_table': 'experiment_metric',
                'indexes': [models.Index(fields=['experiment_id', 'recorded_at'], name='exp_metric_time_idx')],
            },
        ),
    ]
