# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(help_text='The name of the metric', max_length=255)),
                ('metric_value', models.FloatField(help_text='The value of the metric')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the metric was recorded')),
            ],
            options={
                'db_table': 'experiment_metric',
            },
        ),
        migrations.CreateModel(
            name='Optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affected_entity_ids', models.JSONField(blank=True, help_text="Affected campaign/ad set ids, e.g. {'campaign_ids': ['fb:123'], 'ad_set_ids': ['fb:456']}", null=True)),
                ('triggered_metrics', models.JSONField(blank=True, help_text="Metrics that triggered optimization, e.g. {'CPA': {'delta_pct': 35, 'window': '24h'}}", null=True)),
                ('baseline_metrics', models.JSONField(blank=True, help_text="Baseline metrics before adjustments, e.g. {'CPA': 12.3, 'CTR': 0.9}", null=True)),
                ('observed_metrics', models.JSONField(blank=True, help_text='Observed metrics after action, for monitoring/outcome tracking', null=True)),
                ('action_type', models.CharField(choices=[('pause', 'Pause'), ('scale', 'Scale'), ('duplicate', 'Duplicate'), ('edit', 'Edit')], default='pause', help_text='Planned action type (pause/scale/duplicate/edit)', max_length=20)),
                ('planned_action', models.TextField(blank=True, help_text='Planned action details (what will be changed and how)')),
                ('execution_status', models.CharField(choices=[('detected', 'Detected'), ('planned', 'Planned'), ('executed', 'Executed'), ('monitoring', 'Monitoring'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='detected', help_text='Execution status from detection to monitoring/outcome', max_length=20)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When the optimization action was executed', null=True)),
                ('monitored_at', models.DateTimeField(blank=True, help_text='When post-adjustment monitoring/outcome was last updated', null=True)),
                ('outcome_notes', models.TextField(blank=True, help_text='Notes about outcome and performance changes after optimization')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'optimization',
            },
        ),
        migrations.CreateModel(
            name='OptimizationExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the experiment', max_length=255)),
                ('experiment_type', models.CharField(choices=[('ab_test', 'Ab Test'), ('creative_rotation', 'Creative Rotation'), ('budget_split', 'Budget Split')], help_text='The type of the experiment', max_length=255)),
                ('linked_campaign_ids', models.JSONField(help_text='The ids of the linked campaigns')),
                ('hypothesis', models.TextField(help_text='The hypothesis of the experiment')),
                ('start_date', models.DateField(help_text='The start date of the experiment')),
                ('end_date', models.DateField(help_text='The end date of the experiment')),
                ('status', models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('rolled_back', 'Rolled Back')], default='running', help_text='The status of the experiment', max_length=255)),
                ('description', models.TextField(help_text='The description of the experiment')),
            ],
            options={
                'db_table': 'optimization_experiment',
            },
        ),
        migrations.CreateModel(
            name='RollbackHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='The reason for the rollback')),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the rollback action was performed')),
            ],
            options={
                'db_table': 'rollback_history',
            },
        ),
        migrations.CreateModel(
            name='ScalingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('budget_increase', 'Budget Increase'), ('budget_decrease', 'Budget Decrease'), ('audience_expand', 'Audience Expand'), ('audience_narrow', 'Audience Narrow'), ('creative_replace', 'Creative Replace')], help_text='The type of the scaling action', max_length=255)),
                ('action_details', models.JSONField(help_text='The details of the scaling action')),
                ('campaign_id', models.CharField(help_text='The id of the campaign that the scaling action belongs to', max_length=255)),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the scaling action was performed')),
            ],
            options={
                'db_table': 'scaling_action',
            },
        ),
        migrations.CreateModel(
            name='ScalingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('hybrid', 'Hybrid')], help_text='Scaling strategy (horizontal / vertical / hybrid)', max_length=20)),
                ('scaling_target', models.TextField(blank=True, help_text='Description of scaling targets (budget, KPIs, etc.)')),
                ('risk_considerations', models.TextField(blank=True, help_text='Key risks and mitigation considerations for this scaling plan')),
                ('max_scaling_limit', models.CharField(blank=True, help_text='Maximum scaling limits (e.g. max budget or % increase)', max_length=255)),
                ('stop_conditions', models.TextField(blank=True, help_text='Conditions under which scaling should be stopped or rolled back')),
                ('affected_entities', models.JSONField(blank=True, help_text='List of affected campaigns/ad sets and relevant identifiers', null=True)),
                ('expected_outcomes', models.TextField(blank=True, help_text='Expected outcomes / KPI ranges for the overall scaling plan')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Lifecycle status of the scaling plan', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution of the scaling plan started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution of the scaling plan completed', null=True)),
                ('review_summary', models.TextField(blank=True, help_text='High-level summary of scaling impact after completion')),
                ('review_lessons_learned', models.TextField(blank=True, help_text='Key lessons learned from this scaling activity')),
                ('review_future_actions', models.TextField(blank=True, help_text='Recommended changes or improvements for future scaling tasks')),
                ('review_completed_at', models.DateTimeField(blank=True, help_text='When the post-scaling review was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scaling_plan',
            },
        ),
        migrations.CreateModel(
            name='ScalingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1, help_text='Order of this step within the scaling plan')),
                ('name', models.CharField(blank=True, help_text='Optional name/label for this scaling step', max_length=255)),
                ('planned_change', models.TextField(blank=True, help_text='Description of planned change (e.g. budget from 500→800)')),
                ('expected_metrics', models.JSONField(blank=True, help_text='Expected metrics for this step (e.g. ROAS, CPA, CTR)', null=True)),
                ('actual_metrics', models.JSONField(blank=True, help_text='Actual observed metrics after this scaling step', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Execution status for this step', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When this step is planned to be executed', null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When this step was actually executed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes, adjustments, or comments for this step')),
                ('stop_triggered', models.BooleanField(default=False, help_text='Whether this step triggered stop/rollback conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Parent scaling plan', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='optimization.scalingplan')),
                ('related_scaling_action', models.ForeignKey(blank=True, help_text='Optional link to underlying scaling action, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_steps', to='optimization.scalingaction')),
            ],
            options={
                'db_table': 'scaling_step',
                'ordering': ['plan_id', 'step_order', 'id'],
            },
        ),
    ]
