# Generated by Django 4.2.23 on 2026-01-07 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_alter_task_type'),
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScalingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('horizontal', 'Horizontal'), ('vertical', 'Vertical'), ('hybrid', 'Hybrid')], help_text='Scaling strategy (horizontal / vertical / hybrid)', max_length=20)),
                ('scaling_target', models.TextField(blank=True, help_text='Description of scaling targets (budget, KPIs, etc.)')),
                ('risk_considerations', models.TextField(blank=True, help_text='Key risks and mitigation considerations for this scaling plan')),
                ('max_scaling_limit', models.CharField(blank=True, help_text='Maximum scaling limits (e.g. max budget or % increase)', max_length=255)),
                ('stop_conditions', models.TextField(blank=True, help_text='Conditions under which scaling should be stopped or rolled back')),
                ('affected_entities', models.JSONField(blank=True, help_text='List of affected campaigns/ad sets and relevant identifiers', null=True)),
                ('expected_outcomes', models.TextField(blank=True, help_text='Expected outcomes / KPI ranges for the overall scaling plan')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Lifecycle status of the scaling plan', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, help_text='When execution of the scaling plan started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When execution of the scaling plan completed', null=True)),
                ('review_summary', models.TextField(blank=True, help_text='High-level summary of scaling impact after completion')),
                ('review_lessons_learned', models.TextField(blank=True, help_text='Key lessons learned from this scaling activity')),
                ('review_future_actions', models.TextField(blank=True, help_text='Recommended changes or improvements for future scaling tasks')),
                ('review_completed_at', models.DateTimeField(blank=True, help_text='When the post-scaling review was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(help_text='Parent task that owns this scaling plan', on_delete=django.db.models.deletion.CASCADE, related_name='scaling_plan', to='task.task')),
            ],
            options={
                'db_table': 'scaling_plan',
            },
        ),
        migrations.CreateModel(
            name='ScalingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField(default=1, help_text='Order of this step within the scaling plan')),
                ('name', models.CharField(blank=True, help_text='Optional name/label for this scaling step', max_length=255)),
                ('planned_change', models.TextField(blank=True, help_text='Description of planned change (e.g. budget from 500→800)')),
                ('expected_metrics', models.JSONField(blank=True, help_text='Expected metrics for this step (e.g. ROAS, CPA, CTR)', null=True)),
                ('actual_metrics', models.JSONField(blank=True, help_text='Actual observed metrics after this scaling step', null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', help_text='Execution status for this step', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When this step is planned to be executed', null=True)),
                ('executed_at', models.DateTimeField(blank=True, help_text='When this step was actually executed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes, adjustments, or comments for this step')),
                ('stop_triggered', models.BooleanField(default=False, help_text='Whether this step triggered stop/rollback conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Parent scaling plan', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='optimization.scalingplan')),
                ('related_scaling_action', models.ForeignKey(blank=True, help_text='Optional link to underlying scaling action, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_steps', to='optimization.scalingaction')),
            ],
            options={
                'db_table': 'scaling_step',
                'ordering': ['plan_id', 'step_order', 'id'],
            },
        ),
    ]
