# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('optimization', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalingplan',
            name='task',
            field=models.OneToOneField(help_text='Parent task that owns this scaling plan', on_delete=django.db.models.deletion.CASCADE, related_name='scaling_plan', to='task.task'),
        ),
        migrations.AddField(
            model_name='scalingaction',
            name='experiment_id',
            field=models.ForeignKey(db_column='experiment_id', help_text='The experiment that the scaling action belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_scaling_actions', to='optimization.optimizationexperiment'),
        ),
        migrations.AddField(
            model_name='scalingaction',
            name='performed_by',
            field=models.ForeignKey(db_column='performed_by', help_text='The user who performed the scaling action', on_delete=django.db.models.deletion.CASCADE, related_name='performed_scaling_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rollbackhistory',
            name='performed_by',
            field=models.ForeignKey(db_column='performed_by', help_text='The user who performed the rollback action', on_delete=django.db.models.deletion.CASCADE, related_name='performed_rollback_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rollbackhistory',
            name='scaling_action_id',
            field=models.ForeignKey(help_text='The id of the scaling action that was rolled back', on_delete=django.db.models.deletion.CASCADE, related_name='owned_rollback_histories', to='optimization.scalingaction'),
        ),
        migrations.AddField(
            model_name='optimizationexperiment',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', help_text='The user who created the experiment', on_delete=django.db.models.deletion.CASCADE, related_name='owned_optimization_experiments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optimization',
            name='task',
            field=models.OneToOneField(blank=True, help_text='The task that owns this optimization (1:1 relationship)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization', to='task.task'),
        ),
        migrations.AddField(
            model_name='experimentmetric',
            name='experiment_id',
            field=models.ForeignKey(db_column='experiment_id', help_text='The id of the experiment that the metric belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='owned_experiment_metrics', to='optimization.optimizationexperiment'),
        ),
        migrations.AddIndex(
            model_name='experimentmetric',
            index=models.Index(fields=['experiment_id', 'recorded_at'], name='exp_metric_time_idx'),
        ),
    ]
