# Generated by Django 4.2.23 on 2025-09-03 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(help_text='MIME type for browser/frontend display', max_length=255)),
                ('size', models.BigIntegerField(help_text='File size in bytes')),
                ('checksum', models.CharField(blank=True, help_text='File checksum for integrity verification', max_length=64, null=True)),
                ('storage_key', models.CharField(help_text='Relative storage path for file location', max_length=500, unique=True)),
                ('original_filename', models.CharField(help_text='Original filename as uploaded by user', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_fsm.FSMField(choices=[('incoming', 'Incoming - File just uploaded'), ('scanning', 'Scanning - Virus scan in progress'), ('ready', 'Ready - File is safe and available'), ('infected', 'Infected - File contains virus/malware'), ('missing', 'Missing - File missing from storage'), ('error_scanning', 'ErrorScanning - Scanner error occurred')], default='incoming', help_text='File status for virus scanning and availability', max_length=20, protected=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether file is publicly accessible')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'metric_files',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uploaded_by', 'created_at'], name='metric_file_uploade_2968a8_idx'), models.Index(fields=['mime_type'], name='metric_file_mime_ty_787e7c_idx'), models.Index(fields=['is_public'], name='metric_file_is_publ_ac61e7_idx'), models.Index(fields=['is_deleted'], name='metric_file_is_dele_774e7e_idx'), models.Index(fields=['status'], name='metric_file_status_bf5b51_idx'), models.Index(fields=['checksum'], name='metric_file_checksu_bc454b_idx')],
            },
        ),
    ]
