# Generated by Django 4.2.23 on 2026-01-11 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("task", "0014_merge_20260110_0420"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alert_type", models.CharField(choices=[("spend_spike", "Spend Spike"), ("policy_violation", "Policy Violation"), ("performance_drop", "Performance Drop"), ("delivery_issue", "Delivery Issue"), ("other", "Other")], help_text="Type of alert that triggered this task", max_length=50)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], help_text="Severity level of the alert", max_length=20)),
                ("affected_entities", models.JSONField(blank=True, default=list, help_text="List of affected campaigns/ad sets or identifiers")),
                ("initial_metrics", models.JSONField(blank=True, default=dict, help_text="Initial metric snapshot at alert creation")),
                ("status", models.CharField(choices=[("open", "Open"), ("acknowledged", "Acknowledged"), ("in_progress", "In Progress"), ("mitigated", "Mitigated"), ("resolved", "Resolved"), ("closed", "Closed")], default="open", help_text="Lifecycle status of the alert task", max_length=20)),
                ("investigation_notes", models.TextField(blank=True, help_text="Initial investigation notes or assumptions")),
                ("resolution_steps", models.TextField(blank=True, help_text="Actions taken to resolve or mitigate the alert")),
                ("related_references", models.JSONField(blank=True, default=list, help_text="Links or references to campaigns, assets, or policy docs")),
                ("postmortem_root_cause", models.TextField(blank=True, help_text="Root cause summary after resolution")),
                ("postmortem_prevention", models.TextField(blank=True, help_text="Preventive measures identified after resolution")),
                ("resolved_at", models.DateTimeField(blank=True, help_text="When the alert was resolved", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, help_text="When the alert was acknowledged", null=True)),
                ("acknowledged_by", models.ForeignKey(blank=True, help_text="User who acknowledged the alert", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="acknowledged_alert_tasks", to=settings.AUTH_USER_MODEL)),
                ("assigned_to", models.ForeignKey(blank=True, help_text="User responsible for handling the alert", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="assigned_alert_tasks", to=settings.AUTH_USER_MODEL)),
                ("task", models.OneToOneField(help_text="Parent task that owns this alert task", on_delete=django.db.models.deletion.CASCADE, related_name="alert_task", to="task.task")),
            ],
            options={
                "db_table": "alert_task",
            },
        ),
    ]
