# Generated by Django 4.2.23 on 2026-01-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttask',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When the alert was acknowledged', null=True),
        ),
    ]
