# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerting', '0002_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerttask',
            name='task',
            field=models.OneToOneField(help_text='Parent task that owns this alert task', on_delete=django.db.models.deletion.CASCADE, related_name='alert_task', to='task.task'),
        ),
    ]
