# Generated by Django 4.2.23 on 2026-01-12 12:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_rename_core_projec_email_abc123_idx_core_projec_email_45393c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('#1E88E5', 'Blue'), ('#E53935', 'Red'), ('#43A047', 'Green'), ('#FB8C00', 'Orange'), ('#8E24AA', 'Purple'), ('#3949AB', 'Indigo'), ('#00ACC1', 'Cyan'), ('#F4511E', 'Deep Orange'), ('#6D4C41', 'Brown'), ('#546E7A', 'Blue Grey')], default='#1E88E5', max_length=7)),
                ('visibility', models.CharField(choices=[('private', 'Private - Only owner can see'), ('shared', 'Shared - Visible to specific users'), ('public', 'Public - Anyone with link can view')], default='private', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('organization', models.ForeignKey(help_text="Tenant boundary. Must match owner's organization.", on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.organization')),
                ('owner', models.ForeignKey(help_text='Calendar owner', on_delete=django.db.models.deletion.CASCADE, related_name='owned_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(help_text='Event start (UTC recommended)')),
                ('end_datetime', models.DateTimeField(help_text='Event end (UTC recommended)')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('event_type', models.CharField(choices=[('default', 'Default Event'), ('out_of_office', 'Out of Office'), ('focus_time', 'Focus Time'), ('working_location', 'Working Location')], default='default', max_length=30)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('visibility', models.CharField(choices=[('default', 'Default'), ('public', 'Public'), ('private', 'Private')], default='default', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('original_start', models.DateTimeField(blank=True, help_text='Original start for a modified instance', null=True)),
                ('has_conference', models.BooleanField(default=False)),
                ('conference_data', models.JSONField(blank=True, default=dict)),
                ('guests_can_modify', models.BooleanField(default=False)),
                ('guests_can_invite_others', models.BooleanField(default=True)),
                ('guests_can_see_other_guests', models.BooleanField(default=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ical_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match calendar.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1E88E5', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match user.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event categories',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('by_day', models.JSONField(blank=True, default=list)),
                ('by_month_day', models.JSONField(blank=True, default=list)),
                ('by_set_pos', models.JSONField(blank=True, default=list)),
                ('by_month', models.JSONField(blank=True, default=list)),
                ('count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('exception_dates', models.JSONField(blank=True, default=list)),
                ('rrule_string', models.TextField(blank=True, null=True)),
                ('organization', models.ForeignKey(help_text='Tenant boundary.', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_date', models.DateTimeField(help_text='Occurrence start datetime being modified/deleted (UTC recommended)')),
                ('is_cancelled', models.BooleanField(default=False, help_text='True if this specific instance is cancelled')),
                ('modified_event', models.ForeignKey(blank=True, help_text='Full modified event (optional). Null when deleted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_modifications', to='calendars.event')),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match recurrence_rule / events org.', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='core.organization')),
                ('original_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendars.event')),
                ('recurrence_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendars.recurrencerule')),
            ],
            options={
                'ordering': ['exception_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('event_reminder', 'Event reminder'), ('event_invitation', 'Event invitation'), ('event_updated', 'Event updated'), ('event_cancelled', 'Event cancelled'), ('event_response', 'Attendee response'), ('calendar_shared', 'Calendar shared with you'), ('calendar_unshared', 'Calendar access removed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendars.calendar')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendars.event')),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match user.organization and related objects org.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notifications', to='core.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('notification', 'In-app notification'), ('popup', 'Pop-up alert'), ('sms', 'SMS')], default='notification', max_length=20)),
                ('minutes_before', models.PositiveIntegerField(blank=True, null=True)),
                ('time_value', models.PositiveIntegerField(blank=True, null=True)),
                ('time_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendars.event')),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match event.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to='core.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'minutes_before'],
            },
        ),
        migrations.CreateModel(
            name='EventCategoryAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='calendars.eventcategory')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='calendars.event')),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match event/category org.', on_delete=django.db.models.deletion.CASCADE, related_name='event_category_assignments', to='core.organization')),
            ],
            options={
                'ordering': ['event', 'category'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Attendee email address', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attendee_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('resource', 'Resource (room, equipment)')], default='required', max_length=20)),
                ('response_status', models.CharField(choices=[('needs_action', 'No response yet'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative/Maybe')], default='needs_action', max_length=20)),
                ('response_comment', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_organizer', models.BooleanField(default=False)),
                ('can_modify', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calendars.event')),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match event.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='core.organization')),
                ('user', models.ForeignKey(blank=True, help_text='Internal user (if registered).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_organizer', 'attendee_type', 'email'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, help_text='Recurrence pattern for this series (if recurring).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendars.recurrencerule'),
        ),
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(blank=True, help_text='External iCal URL', null=True)),
                ('color_override', models.CharField(blank=True, max_length=7, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from view without unsubscribing')),
                ('notification_enabled', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='calendars.calendar')),
                ('organization', models.ForeignKey(help_text='Tenant boundary.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to='core.organization')),
                ('user', models.ForeignKey(help_text='The subscriber (who is viewing)', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view_free_busy', 'See only free/busy (hide details)'), ('view_all', 'View all event details'), ('edit', 'Make changes to events'), ('manage', 'Make changes and manage sharing'), ('owner', 'Owner - full control')], default='view_all', max_length=20)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='calendars.calendar')),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match calendar.organization and shared_with.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares', to='core.organization')),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_view', models.CharField(choices=[('day', 'Day view'), ('week', 'Week view'), ('month', 'Month view'), ('year', 'Year view'), ('agenda', 'Agenda view')], default='week', max_length=20)),
                ('week_start', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (6, 'Saturday')], default=1)),
                ('time_format', models.CharField(choices=[('12h', '12-hour (1:00 PM)'), ('24h', '24-hour (13:00)')], default='12h', max_length=5)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('default_event_duration', models.PositiveIntegerField(default=60)),
                ('default_reminders', models.JSONField(blank=True, default=list)),
                ('working_hours_enabled', models.BooleanField(default=False)),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('show_declined_events', models.BooleanField(default=False)),
                ('auto_add_invitations', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(help_text='Tenant boundary. Must match user.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to='core.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Calendar settings',
            },
        ),
        migrations.AddIndex(
            model_name='recurrencerule',
            index=models.Index(fields=['organization', 'frequency'], name='calendars_r_organiz_2dbf7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('count__isnull', True), ('until__isnull', False)), models.Q(('count__isnull', False), ('until__isnull', True)), models.Q(('count__isnull', True), ('until__isnull', True)), _connector='OR'), name='recurrence_count_or_until'),
        ),
        migrations.AddIndex(
            model_name='recurrenceexception',
            index=models.Index(fields=['organization', 'recurrence_rule', 'exception_date'], name='calendars_r_organiz_c40521_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrenceexception',
            index=models.Index(fields=['organization', 'original_event', 'exception_date'], name='calendars_r_organiz_db6196_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurrenceexception',
            constraint=models.UniqueConstraint(fields=('organization', 'recurrence_rule', 'exception_date'), name='unique_exception_per_date_per_org'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user', 'is_read', 'created_at'], name='calendars_n_organiz_2bba72_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user', 'notification_type'], name='calendars_n_organiz_a893b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'event', 'user'], name='calendars_n_organiz_9875cf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['organization', 'event', 'user'], name='calendars_e_organiz_142a11_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['organization', 'scheduled_time', 'is_sent'], name='calendars_e_organiz_b3c159_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['organization', 'is_sent', 'scheduled_time'], name='calendars_e_organiz_fb9924_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategoryassignment',
            index=models.Index(fields=['organization', 'event', 'category'], name='calendars_e_organiz_f464bd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategoryassignment',
            index=models.Index(fields=['organization', 'category', 'is_deleted'], name='calendars_e_organiz_482093_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'event', 'category'), name='unique_category_assignment_per_org'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['organization', 'user', 'is_deleted'], name='calendars_e_organiz_801e42_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'user', 'name'), name='unique_category_per_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'event', 'user'], name='calendars_e_organiz_ddb7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'event', 'email'], name='calendars_e_organiz_d2d0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'user', 'response_status'], name='calendars_e_organiz_cdd30e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'email', 'response_status'], name='calendars_e_organiz_9cbcf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'event', 'email'), name='unique_attendee_per_event_per_org'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'calendar', 'start_datetime', 'end_datetime'], name='calendars_e_organiz_deb3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'calendar', 'is_deleted'], name='calendars_e_organiz_e9e578_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'start_datetime', 'end_datetime'], name='calendars_e_organiz_be0d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'created_by', 'is_deleted'], name='calendars_e_organiz_df4ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'is_recurring', 'recurrence_rule'], name='calendars_e_organiz_e54f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status', 'start_datetime'], name='calendars_e_organiz_605bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'calendar', 'status', 'start_datetime'], name='calendars_e_organiz_089aa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('ical_uid__isnull', False)), fields=('organization', 'ical_uid'), name='unique_ical_uid_per_org'),
        ),
        migrations.AddIndex(
            model_name='calendarsubscription',
            index=models.Index(fields=['organization', 'user', 'is_hidden'], name='calendars_c_organiz_23e546_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsubscription',
            index=models.Index(fields=['organization', 'calendar'], name='calendars_c_organiz_f70355_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('calendar__isnull', False)), fields=('organization', 'user', 'calendar'), name='unique_internal_subscription'),
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('source_url__isnull', False)), fields=('organization', 'user', 'source_url'), name='unique_external_subscription'),
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('calendar__isnull', False), ('source_url__isnull', True)), models.Q(('calendar__isnull', True), ('source_url__isnull', False)), _connector='OR'), name='subscription_calendar_or_source_url'),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['organization', 'calendar', 'shared_with'], name='calendars_c_organiz_2620c3_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['organization', 'shared_with', 'is_deleted'], name='calendars_c_organiz_feb670_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarshare',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'calendar', 'shared_with'), name='unique_calendar_share_per_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='calendarsettings',
            index=models.Index(fields=['organization', 'user'], name='calendars_c_organiz_838da1_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarsettings',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_calendar_settings_per_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'owner', 'is_deleted'], name='calendars_c_organiz_5134d2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'owner', 'is_primary'], name='calendars_c_organiz_80545e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'visibility'], name='calendars_c_organiz_cfd803_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'owner', 'name'), name='unique_calendar_name_per_owner_per_org'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_deleted', False)), fields=('organization', 'owner'), name='unique_primary_calendar_per_owner_per_org'),
        ),
    ]
