# Generated by Django 4.2.23 on 2026-02-18 09:55

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('#1E88E5', 'Blue'), ('#E53935', 'Red'), ('#43A047', 'Green'), ('#FB8C00', 'Orange'), ('#8E24AA', 'Purple'), ('#3949AB', 'Indigo'), ('#00ACC1', 'Cyan'), ('#F4511E', 'Deep Orange'), ('#6D4C41', 'Brown'), ('#546E7A', 'Blue Grey')], default='#1E88E5', max_length=7)),
                ('visibility', models.CharField(choices=[('private', 'Private - Only owner can see'), ('shared', 'Shared - Visible to specific users'), ('public', 'Public - Anyone with link can view')], default='private', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_view', models.CharField(choices=[('day', 'Day view'), ('week', 'Week view'), ('month', 'Month view'), ('year', 'Year view'), ('agenda', 'Agenda view')], default='week', max_length=20)),
                ('week_start', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (6, 'Saturday')], default=1)),
                ('time_format', models.CharField(choices=[('12h', '12-hour (1:00 PM)'), ('24h', '24-hour (13:00)')], default='12h', max_length=5)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('default_event_duration', models.PositiveIntegerField(default=60)),
                ('default_reminders', models.JSONField(blank=True, default=list)),
                ('working_hours_enabled', models.BooleanField(default=False)),
                ('working_hours_start', models.TimeField(blank=True, null=True)),
                ('working_hours_end', models.TimeField(blank=True, null=True)),
                ('working_days', models.JSONField(blank=True, default=list)),
                ('email_notifications_enabled', models.BooleanField(default=True)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('show_declined_events', models.BooleanField(default=False)),
                ('auto_add_invitations', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Calendar settings',
            },
        ),
        migrations.CreateModel(
            name='CalendarShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('permission', models.CharField(choices=[('view_free_busy', 'See only free/busy (hide details)'), ('view_all', 'View all event details'), ('edit', 'Make changes to events'), ('manage', 'Make changes and manage sharing'), ('owner', 'Owner - full control')], default='view_all', max_length=20)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarSubscription',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_url', models.URLField(blank=True, help_text='External iCal URL', null=True)),
                ('color_override', models.CharField(blank=True, max_length=7, null=True)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hide from view without unsubscribing')),
                ('notification_enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_datetime', models.DateTimeField(help_text='Event start (UTC recommended)')),
                ('end_datetime', models.DateTimeField(help_text='Event end (UTC recommended)')),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('is_all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('tentative', 'Tentative'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20)),
                ('event_type', models.CharField(choices=[('default', 'Default Event'), ('out_of_office', 'Out of Office'), ('focus_time', 'Focus Time'), ('working_location', 'Working Location')], default='default', max_length=30)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('visibility', models.CharField(choices=[('default', 'Default'), ('public', 'Public'), ('private', 'Private')], default='default', max_length=20)),
                ('is_recurring', models.BooleanField(default=False)),
                ('original_start', models.DateTimeField(blank=True, help_text='Original start for a modified instance', null=True)),
                ('has_conference', models.BooleanField(default=False)),
                ('conference_data', models.JSONField(blank=True, default=dict)),
                ('guests_can_modify', models.BooleanField(default=False)),
                ('guests_can_invite_others', models.BooleanField(default=True)),
                ('guests_can_see_other_guests', models.BooleanField(default=True)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ical_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('etag', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, help_text='Attendee email address', max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attendee_type', models.CharField(choices=[('required', 'Required'), ('optional', 'Optional'), ('resource', 'Resource (room, equipment)')], default='required', max_length=20)),
                ('response_status', models.CharField(choices=[('needs_action', 'No response yet'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative/Maybe')], default='needs_action', max_length=20)),
                ('response_comment', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_organizer', models.BooleanField(default=False)),
                ('can_modify', models.BooleanField(default=False)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-is_organizer', 'attendee_type', 'email'],
            },
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#1E88E5', max_length=7)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Event categories',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventCategoryAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['event', 'category'],
            },
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('email', 'Email'), ('notification', 'In-app notification'), ('popup', 'Pop-up alert'), ('sms', 'SMS')], default='notification', max_length=20)),
                ('minutes_before', models.PositiveIntegerField(blank=True, null=True)),
                ('time_value', models.PositiveIntegerField(blank=True, null=True)),
                ('time_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('send_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['event', 'minutes_before'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('event_reminder', 'Event reminder'), ('event_invitation', 'Event invitation'), ('event_updated', 'Event updated'), ('event_cancelled', 'Event cancelled'), ('event_response', 'Attendee response'), ('calendar_shared', 'Calendar shared with you'), ('calendar_unshared', 'Calendar access removed')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceException',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exception_date', models.DateTimeField(help_text='Occurrence start datetime being modified/deleted (UTC recommended)')),
                ('is_cancelled', models.BooleanField(default=False, help_text='True if this specific instance is cancelled')),
            ],
            options={
                'ordering': ['exception_date'],
            },
        ),
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
                ('by_day', models.JSONField(blank=True, default=list)),
                ('by_month_day', models.JSONField(blank=True, default=list)),
                ('by_set_pos', models.JSONField(blank=True, default=list)),
                ('by_month', models.JSONField(blank=True, default=list)),
                ('count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(999)])),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('exception_dates', models.JSONField(blank=True, default=list)),
                ('rrule_string', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
