# Generated by Django 4.2.23 on 2026-01-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='etag',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
