# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencerule',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary.', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_rules', to='core.organization'),
        ),
        migrations.AddField(
            model_name='recurrenceexception',
            name='modified_event',
            field=models.ForeignKey(blank=True, help_text='Full modified event (optional). Null when deleted.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exception_modifications', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='recurrenceexception',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match recurrence_rule / events org.', on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='core.organization'),
        ),
        migrations.AddField(
            model_name='recurrenceexception',
            name='original_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_exceptions', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='recurrenceexception',
            name='recurrence_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='calendars.recurrencerule'),
        ),
        migrations.AddField(
            model_name='notification',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendars.calendar'),
        ),
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='notification',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match user.organization and related objects org.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notifications', to='core.organization'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match event.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to='core.organization'),
        ),
        migrations.AddField(
            model_name='eventreminder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_reminders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventcategoryassignment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_assignments', to='calendars.eventcategory'),
        ),
        migrations.AddField(
            model_name='eventcategoryassignment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_assignments', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='eventcategoryassignment',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match event/category org.', on_delete=django.db.models.deletion.CASCADE, related_name='event_category_assignments', to='core.organization'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match user.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to='core.organization'),
        ),
        migrations.AddField(
            model_name='eventcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='calendars.event'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match event.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='core.organization'),
        ),
        migrations.AddField(
            model_name='eventattendee',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Internal user (if registered).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='calendars.calendar'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match calendar.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_rule',
            field=models.ForeignKey(blank=True, help_text='Recurrence pattern for this series (if recurring).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='calendars.recurrencerule'),
        ),
        migrations.AddField(
            model_name='calendarsubscription',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='calendars.calendar'),
        ),
        migrations.AddField(
            model_name='calendarsubscription',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to='core.organization'),
        ),
        migrations.AddField(
            model_name='calendarsubscription',
            name='user',
            field=models.ForeignKey(help_text='The subscriber (who is viewing)', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarshare',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='calendars.calendar'),
        ),
        migrations.AddField(
            model_name='calendarshare',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match calendar.organization and shared_with.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_shares', to='core.organization'),
        ),
        migrations.AddField(
            model_name='calendarshare',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='organization',
            field=models.ForeignKey(help_text='Tenant boundary. Must match user.organization.', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to='core.organization'),
        ),
        migrations.AddField(
            model_name='calendarsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='organization',
            field=models.ForeignKey(help_text="Tenant boundary. Must match owner's organization.", on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='core.organization'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Calendar owner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calendar',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional project binding for project-scoped calendars.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendars', to='core.project'),
        ),
        migrations.AddIndex(
            model_name='recurrencerule',
            index=models.Index(fields=['organization', 'frequency'], name='calendars_r_organiz_2dbf7e_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurrencerule',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('count__isnull', True), ('until__isnull', False)), models.Q(('count__isnull', False), ('until__isnull', True)), models.Q(('count__isnull', True), ('until__isnull', True)), _connector='OR'), name='recurrence_count_or_until'),
        ),
        migrations.AddIndex(
            model_name='recurrenceexception',
            index=models.Index(fields=['organization', 'recurrence_rule', 'exception_date'], name='calendars_r_organiz_c40521_idx'),
        ),
        migrations.AddIndex(
            model_name='recurrenceexception',
            index=models.Index(fields=['organization', 'original_event', 'exception_date'], name='calendars_r_organiz_db6196_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurrenceexception',
            constraint=models.UniqueConstraint(fields=('organization', 'recurrence_rule', 'exception_date'), name='unique_exception_per_date_per_org'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user', 'is_read', 'created_at'], name='calendars_n_organiz_2bba72_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'user', 'notification_type'], name='calendars_n_organiz_a893b6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'event', 'user'], name='calendars_n_organiz_9875cf_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['organization', 'event', 'user'], name='calendars_e_organiz_142a11_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['organization', 'scheduled_time', 'is_sent'], name='calendars_e_organiz_b3c159_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreminder',
            index=models.Index(fields=['organization', 'is_sent', 'scheduled_time'], name='calendars_e_organiz_fb9924_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategoryassignment',
            index=models.Index(fields=['organization', 'event', 'category'], name='calendars_e_organiz_f464bd_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategoryassignment',
            index=models.Index(fields=['organization', 'category', 'is_deleted'], name='calendars_e_organiz_482093_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcategoryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'event', 'category'), name='unique_category_assignment_per_org'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['organization', 'user', 'is_deleted'], name='calendars_e_organiz_801e42_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'user', 'name'), name='unique_category_per_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'event', 'user'], name='calendars_e_organiz_ddb7ec_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'event', 'email'], name='calendars_e_organiz_d2d0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'user', 'response_status'], name='calendars_e_organiz_cdd30e_idx'),
        ),
        migrations.AddIndex(
            model_name='eventattendee',
            index=models.Index(fields=['organization', 'email', 'response_status'], name='calendars_e_organiz_9cbcf4_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventattendee',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'event', 'email'), name='unique_attendee_per_event_per_org'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'calendar', 'start_datetime', 'end_datetime'], name='calendars_e_organiz_deb3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'calendar', 'is_deleted'], name='calendars_e_organiz_e9e578_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'start_datetime', 'end_datetime'], name='calendars_e_organiz_be0d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'created_by', 'is_deleted'], name='calendars_e_organiz_df4ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'is_recurring', 'recurrence_rule'], name='calendars_e_organiz_e54f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'status', 'start_datetime'], name='calendars_e_organiz_605bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['organization', 'calendar', 'status', 'start_datetime'], name='calendars_e_organiz_089aa3_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('end_datetime__gt', models.F('start_datetime'))), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('ical_uid__isnull', False)), fields=('organization', 'ical_uid'), name='unique_ical_uid_per_org'),
        ),
        migrations.AddIndex(
            model_name='calendarsubscription',
            index=models.Index(fields=['organization', 'user', 'is_hidden'], name='calendars_c_organiz_23e546_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarsubscription',
            index=models.Index(fields=['organization', 'calendar'], name='calendars_c_organiz_f70355_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('calendar__isnull', False)), fields=('organization', 'user', 'calendar'), name='unique_internal_subscription'),
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('source_url__isnull', False)), fields=('organization', 'user', 'source_url'), name='unique_external_subscription'),
        ),
        migrations.AddConstraint(
            model_name='calendarsubscription',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('calendar__isnull', False), ('source_url__isnull', True)), models.Q(('calendar__isnull', True), ('source_url__isnull', False)), _connector='OR'), name='subscription_calendar_or_source_url'),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['organization', 'calendar', 'shared_with'], name='calendars_c_organiz_2620c3_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarshare',
            index=models.Index(fields=['organization', 'shared_with', 'is_deleted'], name='calendars_c_organiz_feb670_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarshare',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('organization', 'calendar', 'shared_with'), name='unique_calendar_share_per_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='calendarsettings',
            index=models.Index(fields=['organization', 'user'], name='calendars_c_organiz_838da1_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarsettings',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_calendar_settings_per_user_per_org'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'owner', 'is_deleted'], name='calendars_c_organiz_5134d2_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'owner', 'is_primary'], name='calendars_c_organiz_80545e_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'visibility'], name='calendars_c_organiz_cfd803_idx'),
        ),
        migrations.AddIndex(
            model_name='calendar',
            index=models.Index(fields=['organization', 'project', 'is_deleted'], name='calendars_c_organiz_87e5ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('owner__isnull', False)), fields=('organization', 'owner', 'name'), name='unique_calendar_name_per_owner_per_org'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_deleted', False), ('owner__isnull', False)), fields=('organization', 'owner'), name='unique_primary_calendar_per_owner_per_org'),
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('project__isnull', False)), fields=('project',), name='unique_project_calendar'),
        ),
    ]
