# Generated by Django 4.2.23 on 2026-04-01 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('task', '0005_alter_approvalrecord_options_and_more'),
        ('decision', '0005_alter_decisionstatetransition_from_status_and_more'),
        ('calendars', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('decision', 'Decision Event'), ('task', 'Task Event'), ('decision_review', 'Decision Review Event')], help_text='Type of calendar event derived from source entity', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Event start time, derived from source entity (e.g. committed_at / due_date)')),
                ('end_time', models.DateTimeField(blank=True, help_text='Event end time (optional)', null=True)),
                ('title', models.CharField(help_text='Display title shown on the calendar', max_length=255)),
                ('decision', models.ForeignKey(blank=True, help_text='Source Decision (required for decision / decision_review events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='decision.decision')),
                ('organization', models.ForeignKey(help_text="Tenant boundary. Must match source entity's organization.", on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.organization')),
                ('review', models.ForeignKey(blank=True, help_text='Source Review (used for decision_review events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='decision.review')),
                ('task', models.ForeignKey(blank=True, help_text='Source Task (required for task events)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='task.task')),
            ],
            options={
                'db_table': 'calendar_derived_events',
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['organization', 'start_time', 'event_type'], name='calendar_de_organiz_1327b7_idx')],
            },
        ),
    ]
