# Generated by Django 4.2.23 on 2026-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0003_project_calendar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calendar',
            name='unique_primary_calendar_per_owner_per_org',
        ),
        migrations.AddConstraint(
            model_name='calendar',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_deleted', False), ('owner__isnull', False)), fields=('organization', 'owner'), name='unique_primary_calendar_per_owner_per_org'),
        ),
    ]
