# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('context_summary', models.TextField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('confidence', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, protected=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_reference_case', models.BooleanField(default=False)),
                ('project_seq', models.PositiveIntegerField()),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_decisions', to=settings.AUTH_USER_MODEL)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_decisions', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_decisions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='core.project')),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('metric', models.CharField(blank=True, choices=[('ROAS', 'ROAS'), ('CPA', 'CPA'), ('CONVERSION_RATE', 'Conversion Rate'), ('REVENUE', 'Revenue'), ('PURCHASES', 'Purchases'), ('CTR', 'CTR'), ('CLICKS', 'Clicks'), ('IMPRESSIONS', 'Impressions'), ('CPC', 'CPC'), ('CPM', 'CPM'), ('AD_SPEND', 'Ad Spend'), ('AOV', 'AOV')], max_length=30, null=True)),
                ('movement', models.CharField(blank=True, choices=[('SHARP_INCREASE', 'Sharp Increase'), ('MODERATE_INCREASE', 'Moderate Increase'), ('SLIGHT_INCREASE', 'Slight Increase'), ('NO_SIGNIFICANT_CHANGE', 'No Significant Change'), ('SLIGHT_DECREASE', 'Slight Decrease'), ('MODERATE_DECREASE', 'Moderate Decrease'), ('SHARP_DECREASE', 'Sharp Decrease'), ('VOLATILE', 'Volatile'), ('UNEXPECTED_SPIKE', 'Unexpected Spike'), ('UNEXPECTED_DROP', 'Unexpected Drop')], max_length=30, null=True)),
                ('period', models.CharField(blank=True, choices=[('LAST_24_HOURS', 'Last 24 Hours'), ('LAST_3_DAYS', 'Last 3 Days'), ('LAST_7_DAYS', 'Last 7 Days'), ('LAST_14_DAYS', 'Last 14 Days'), ('LAST_30_DAYS', 'Last 30 Days')], max_length=20, null=True)),
                ('comparison', models.CharField(choices=[('NONE', 'None'), ('PREVIOUS_PERIOD', 'Previous Period'), ('SAME_PERIOD_LAST_WEEK', 'Same Period Last Week'), ('SINCE_LAUNCH', 'Since Launch')], default='NONE', max_length=30)),
                ('scope_type', models.CharField(blank=True, choices=[('CAMPAIGN', 'Campaign'), ('AD_SET', 'Ad Set'), ('AD', 'Ad'), ('CHANNEL', 'Channel'), ('AUDIENCE', 'Audience'), ('REGION', 'Region')], max_length=20, null=True)),
                ('scope_value', models.CharField(blank=True, max_length=255, null=True)),
                ('delta_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('delta_unit', models.CharField(blank=True, choices=[('PERCENT', 'Percent'), ('CURRENCY', 'Currency'), ('ABSOLUTE', 'Absolute')], max_length=20, null=True)),
                ('display_text', models.TextField(blank=True, default='')),
                ('display_text_override', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decision_signals', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_signals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('outcome_text', models.TextField()),
                ('reflection_text', models.TextField()),
                ('quality', models.CharField(choices=[('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decision.decision')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('transition_method', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='decision.decision')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_state_transitions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DecisionEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decision_edges', to=settings.AUTH_USER_MODEL)),
                ('from_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='decision.decision')),
                ('to_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_edges',
            },
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('validation_snapshot', models.JSONField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_commit_records', to=settings.AUTH_USER_MODEL)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commit_record', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_commit_records',
            },
        ),
        migrations.AddConstraint(
            model_name='decisionedge',
            constraint=models.UniqueConstraint(fields=('from_decision', 'to_decision'), name='unique_decision_edge'),
        ),
        migrations.AddConstraint(
            model_name='decisionedge',
            constraint=models.CheckConstraint(check=models.Q(('from_decision', models.F('to_decision')), _negated=True), name='decision_edge_no_self_loop'),
        ),
        migrations.AddConstraint(
            model_name='decision',
            constraint=models.UniqueConstraint(fields=('project', 'project_seq'), name='unique_project_decision_seq'),
        ),
    ]
