# Generated by Django 4.2.23 on 2026-01-21 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('context_summary', models.TextField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('confidence', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20, protected=True)),
                ('requires_approval', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_reference_case', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_decisions', to=settings.AUTH_USER_MODEL)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_decisions', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('PERFORMANCE', 'Performance'), ('CLIENT', 'Client'), ('PLATFORM', 'Platform'), ('INTUITION', 'Intuition'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_signals',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('outcome_text', models.TextField()),
                ('reflection_text', models.TextField()),
                ('quality', models.CharField(choices=[('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decision.decision')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('is_selected', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Draft'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], max_length=20)),
                ('transition_method', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='decision.decision')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_state_transitions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('committed_at', models.DateTimeField(auto_now_add=True)),
                ('validation_snapshot', models.JSONField(blank=True, null=True)),
                ('committed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_commit_records', to=settings.AUTH_USER_MODEL)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commit_record', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_commit_records',
            },
        ),
    ]
