# Generated by Django 4.2.23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, help_text='Optional title for the decision', max_length=255, null=True)),
                ('context_summary', models.TextField(help_text='Summary of the context that led to this decision')),
                ('reasoning', models.TextField(help_text='Explanation of why the selected option was chosen')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], help_text='Expected risk level of this decision', max_length=10)),
                ('confidence', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Confidence level (1-5) in this decision')),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], default='DRAFT', help_text='Current lifecycle status', max_length=20, protected=True)),
                ('committed_at', models.DateTimeField(blank=True, help_text='Timestamp when decision was committed', null=True)),
                ('requires_approval', models.BooleanField(default=False, help_text='Whether this decision requires lead approval before commit')),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when approval was granted', null=True)),
                ('is_reference_case', models.BooleanField(default=False, help_text='Flagged as a reference case by Lead')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Lead who approved this high-risk decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_decisions', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(help_text='User who created this decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_decisions', to=settings.AUTH_USER_MODEL)),
                ('committed_by', models.ForeignKey(blank=True, help_text='User who committed this decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committed_decisions', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='User who last edited this decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_edited_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('METRIC_CHANGE', 'Metric Change'), ('CLIENT_REQUEST', 'Client Request'), ('INTUITION', 'Intuition'), ('ALERT', 'Alert'), ('TREND', 'Trend'), ('OTHER', 'Other')], help_text='Type of signal', max_length=20)),
                ('description', models.TextField(help_text='Description of the signal')),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], help_text='Perceived severity of the signal', max_length=10, null=True)),
                ('source', models.CharField(blank=True, help_text='Optional source of the signal', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of signals')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(help_text='Associated decision', on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_signals',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Description of this option')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether this option was selected')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of options')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(help_text='Associated decision', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_options',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome_text', models.TextField(help_text='Summary of what happened after execution')),
                ('reflection_text', models.TextField(help_text='What was learned from this decision')),
                ('quality', models.CharField(choices=[('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor')], help_text='Assessment of decision quality', max_length=15)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, help_text='When this review was created')),
                ('playbook_tags', models.JSONField(blank=True, default=list, help_text='Optional tags linking to playbooks or learning notes')),
                ('decision', models.ForeignKey(help_text='Associated decision', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='decision.decision')),
                ('reviewer', models.ForeignKey(help_text='User who wrote this review', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionStateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], help_text='Previous state', max_length=20)),
                ('to_state', models.CharField(choices=[('DRAFT', 'Draft'), ('COMMITTED', 'Committed'), ('REVIEWED', 'Reviewed'), ('ARCHIVED', 'Archived')], help_text='New state', max_length=20)),
                ('transition_method', models.CharField(help_text='Name of the method that triggered this transition', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this transition occurred')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context about the transition')),
                ('decision', models.ForeignKey(help_text='Associated decision', on_delete=django.db.models.deletion.CASCADE, related_name='state_transitions', to='decision.decision')),
                ('triggered_by', models.ForeignKey(blank=True, help_text='User who triggered this transition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_transitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'decision_state_transitions',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CommitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_statements', models.JSONField(default=list, help_text='List of confirmation statements checked during commit')),
                ('committed_at', models.DateTimeField(auto_now_add=True, help_text='Commit timestamp')),
                ('committed_by', models.ForeignKey(help_text='User who committed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commit_records', to=settings.AUTH_USER_MODEL)),
                ('decision', models.OneToOneField(help_text='Associated decision', on_delete=django.db.models.deletion.CASCADE, related_name='commit_record', to='decision.decision')),
            ],
            options={
                'db_table': 'decision_commit_records',
            },
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['status'], name='decision_status_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['author', '-created_at'], name='decision_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['risk_level'], name='decision_risk_level_idx'),
        ),
        migrations.AddIndex(
            model_name='decision',
            index=models.Index(fields=['is_reference_case'], name='decision_is_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionstatetransition',
            index=models.Index(fields=['decision', '-timestamp'], name='decision_trans_decision_idx'),
        ),
    ]

