# Generated by Django 4.2.23 on 2026-01-11 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='decision',
            new_name='decisions_status_ab1252_idx',
            old_name='decision_status_idx',
        ),
        migrations.RenameIndex(
            model_name='decision',
            new_name='decisions_author__43ba27_idx',
            old_name='decision_author_created_idx',
        ),
        migrations.RenameIndex(
            model_name='decision',
            new_name='decisions_risk_le_7eaab2_idx',
            old_name='decision_risk_level_idx',
        ),
        migrations.RenameIndex(
            model_name='decision',
            new_name='decisions_is_refe_15184c_idx',
            old_name='decision_is_ref_idx',
        ),
        migrations.RenameIndex(
            model_name='decisionstatetransition',
            new_name='decision_st_decisio_9d0336_idx',
            old_name='decision_trans_decision_idx',
        ),
    ]
