# Generated by Django 4.2.23 on 2026-02-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0006_decision_project_seq'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-created_at']},
        ),
    ]
