# Generated by Django 4.2.23 on 2026-03-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_importedcsvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkflowrun',
            name='chat_followed_up',
            field=models.BooleanField(default=False),
        ),
    ]
