# Generated by Django 4.2.23 on 2026-03-24 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def create_default_workflow(apps, schema_editor):
    WorkflowDef = apps.get_model('agent', 'AgentWorkflowDefinition')
    WorkflowStep = apps.get_model('agent', 'AgentWorkflowStep')

    wf = WorkflowDef.objects.create(
        name='Default Analysis Workflow',
        description='Analyze data, confirm, create decision, confirm, create tasks',
        is_default=True,
        is_system=True,
        status='active',
    )
    steps = [
        ('Analyze Data', 'analyze_data', 1, {}),
        ('Confirm Analysis', 'await_confirmation', 2,
         {'message': 'Analysis complete. Would you like to create a decision based on these findings?'}),
        ('Create Decision', 'create_decision', 3, {}),
        ('Confirm Decision', 'await_confirmation', 4,
         {'message': 'Decision draft created. Would you like to create tasks based on the recommendations?'}),
        ('Create Tasks', 'create_tasks', 5, {}),
    ]
    for name, step_type, order, config in steps:
        WorkflowStep.objects.create(
            workflow=wf, name=name, step_type=step_type,
            order=order, config=config,
        )


def reverse_default_workflow(apps, schema_editor):
    WorkflowDef = apps.get_model('agent', 'AgentWorkflowDefinition')
    WorkflowDef.objects.filter(
        is_system=True, name='Default Analysis Workflow'
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('agent', '0003_add_chat_followed_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentWorkflowDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_default', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('draft', 'Draft'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_definitions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_workflow_definitions', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='current_step_order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AgentWorkflowStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('step_type', models.CharField(choices=[('analyze_data', 'Analyze Data'), ('call_dify', 'Call Dify'), ('call_llm', 'Call LLM'), ('create_decision', 'Create Decision'), ('create_tasks', 'Create Tasks'), ('custom_api', 'Custom API'), ('await_confirmation', 'Await Confirmation')], max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('config', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='agent.agentworkflowdefinition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='AgentStepExecution',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.PositiveIntegerField()),
                ('step_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('awaiting', 'Awaiting Confirmation')], default='pending', max_length=20)),
                ('input_data', models.JSONField(blank=True, null=True)),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='agent.agentworkflowstep')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='agent.agentworkflowrun')),
            ],
            options={
                'ordering': ['step_order'],
            },
        ),
        migrations.AddField(
            model_name='agentworkflowrun',
            name='workflow_definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to='agent.agentworkflowdefinition'),
        ),
        migrations.RunPython(create_default_workflow, reverse_default_workflow),
    ]
