# Generated by Django 4.2.23 on 2026-03-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("miro", "0001_initial"),
        ("agent", "0004_agent_workflow_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentworkflowrun",
            name="miro_board",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agent_workflow_runs",
                to="miro.board",
            ),
        ),
        migrations.AddField(
            model_name="agentworkflowrun",
            name="miro_snapshot",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agentworkflowstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("analyze_data", "Analyze Data"),
                    ("call_dify", "Call Dify"),
                    ("call_llm", "Call LLM"),
                    ("create_decision", "Create Decision"),
                    ("create_tasks", "Create Tasks"),
                    ("generate_miro_snapshot", "Generate Miro Snapshot"),
                    ("create_miro_board", "Create Miro Board"),
                    ("custom_api", "Custom API"),
                    ("await_confirmation", "Await Confirmation"),
                ],
                max_length=30,
            ),
        ),
    ]
