# Generated by Django 4.2.23 on 2026-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_extend_default_workflow_with_miro_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentworkflowrun',
            name='chat_follow_up_started',
            field=models.BooleanField(default=False),
        ),
    ]
