# Generated by Django 4.2.23 on 2026-01-04 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_rename_core_projec_email_abc123_idx_core_projec_email_45393c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the sheet (tab name)', max_length=200)),
                ('position', models.IntegerField(help_text='Position/order of the sheet within the spreadsheet')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the spreadsheet', max_length=200)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this spreadsheet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_spreadsheets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this spreadsheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.IntegerField(help_text='Position/row number within the sheet')),
                ('sheet', models.ForeignKey(help_text='Sheet this row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='spreadsheet.sheet')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Name of the column (e.g., 'A', 'B', 'Column1')", max_length=200)),
                ('position', models.IntegerField(help_text='Position/column number within the sheet')),
                ('sheet', models.ForeignKey(help_text='Sheet this column belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='spreadsheet.sheet')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='spreadsheet',
            field=models.ForeignKey(help_text='Spreadsheet this sheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='spreadsheet.spreadsheet'),
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value_type', models.CharField(choices=[('empty', 'Empty'), ('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('formula', 'Formula')], default='empty', help_text='Type of value stored in this cell', max_length=20)),
                ('string_value', models.TextField(blank=True, help_text="String value. Text starting with '=' stored with ' prefix for round-trip editing.", null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=10, help_text='Numeric value', max_digits=30, null=True)),
                ('boolean_value', models.BooleanField(blank=True, help_text='Boolean value', null=True)),
                ('formula_value', models.TextField(blank=True, help_text="Formula value (must start with '=')", null=True)),
                ('column', models.ForeignKey(help_text='Column this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheet.sheetcolumn')),
                ('row', models.ForeignKey(help_text='Row this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheet.sheetrow')),
                ('sheet', models.ForeignKey(help_text='Sheet this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheet.sheet')),
            ],
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['project', 'is_deleted'], name='spreadsheet_project_f4f9c0_idx'),
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['owner', 'is_deleted'], name='spreadsheet_owner_i_89c43e_idx'),
        ),
        migrations.AddConstraint(
            model_name='spreadsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'name'), name='unique_spreadsheet_name_per_project_active'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'is_deleted'], name='spreadsheet_sheet_i_043f92_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'position'], name='spreadsheet_sheet_i_f294a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetrow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'position'), name='unique_row_position_per_sheet_active'),
        ),
        migrations.AddIndex(
            model_name='sheetcolumn',
            index=models.Index(fields=['sheet', 'is_deleted'], name='spreadsheet_sheet_i_8cfea6_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetcolumn',
            index=models.Index(fields=['sheet', 'position'], name='spreadsheet_sheet_i_40b33e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'position'), name='unique_column_position_per_sheet_active'),
        ),
        migrations.AddIndex(
            model_name='sheet',
            index=models.Index(fields=['spreadsheet', 'is_deleted'], name='spreadsheet_spreads_6a2c03_idx'),
        ),
        migrations.AddIndex(
            model_name='sheet',
            index=models.Index(fields=['spreadsheet', 'position'], name='spreadsheet_spreads_9836c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('spreadsheet', 'name'), name='unique_sheet_name_per_spreadsheet_active'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('spreadsheet', 'position'), name='unique_sheet_position_per_spreadsheet_active'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['sheet', 'is_deleted'], name='spreadsheet_sheet_i_0f2f99_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['row', 'column'], name='spreadsheet_row_id_3d59cb_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'row', 'column'), name='unique_cell_position_per_sheet_active'),
        ),
    ]
