# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value_type', models.CharField(choices=[('empty', 'Empty'), ('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('formula', 'Formula')], default='empty', help_text='Type of value stored in this cell', max_length=20)),
                ('string_value', models.TextField(blank=True, help_text="String value. Text starting with '=' stored with ' prefix for round-trip editing.", null=True)),
                ('number_value', models.DecimalField(blank=True, decimal_places=500, help_text='Numeric value', max_digits=1000, null=True)),
                ('boolean_value', models.BooleanField(blank=True, help_text='Boolean value', null=True)),
                ('formula_value', models.TextField(blank=True, help_text="Formula value (must start with '=')", null=True)),
                ('raw_input', models.TextField(blank=True, help_text="Original user input, including formulas starting with '='", null=True)),
                ('computed_type', models.CharField(choices=[('empty', 'Empty'), ('number', 'Number'), ('string', 'String'), ('boolean', 'Boolean'), ('error', 'Error')], default='empty', help_text='Computed result type for formula or raw input', max_length=20)),
                ('computed_number', models.DecimalField(blank=True, decimal_places=500, help_text='Computed numeric result', max_digits=1000, null=True)),
                ('computed_string', models.TextField(blank=True, help_text='Computed string result', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Formula error code (e.g. #DIV/0!, #REF!)', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the sheet (tab name)', max_length=200)),
                ('position', models.IntegerField(help_text='Position/order of the sheet within the spreadsheet')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Name of the spreadsheet', max_length=200)),
                ('project', models.ForeignKey(help_text='Project this spreadsheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowPattern',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.IntegerField(default=1)),
                ('origin_spreadsheet_id', models.IntegerField(blank=True, null=True)),
                ('origin_sheet_id', models.IntegerField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_patterns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpreadsheetHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('scope', models.CharField(choices=[('CELL', 'Cell'), ('ROW', 'Row'), ('COLUMN', 'Column')], max_length=10)),
                ('row_index', models.IntegerField(blank=True, null=True)),
                ('col_index', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(max_length=20)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='spreadsheet.sheet')),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='spreadsheet.spreadsheet')),
            ],
        ),
        migrations.CreateModel(
            name='SheetStructureOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('op_type', models.CharField(choices=[('ROW_INSERT', 'Row Insert'), ('COL_INSERT', 'Column Insert'), ('ROW_DELETE', 'Row Delete'), ('COL_DELETE', 'Column Delete')], max_length=20)),
                ('anchor_position', models.IntegerField(help_text='Anchor position for the operation (insert/delete start index)')),
                ('count', models.IntegerField(help_text='Number of rows/columns inserted or deleted')),
                ('affected_ids', models.JSONField(default=list, help_text='List of affected row/column IDs')),
                ('affected_positions', models.JSONField(default=dict, help_text='Mapping of affected ID to original position')),
                ('is_reverted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sheet_structure_operations', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(help_text='Sheet this operation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='structure_operations', to='spreadsheet.sheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SheetRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('position', models.IntegerField(help_text='Position/row number within the sheet')),
                ('sheet', models.ForeignKey(help_text='Sheet this row belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='spreadsheet.sheet')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='SheetColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text="Name of the column (e.g., 'A', 'B', 'C', should be automatically generated in serialization)", max_length=200)),
                ('position', models.IntegerField(help_text='Position/column number within the sheet')),
                ('sheet', models.ForeignKey(help_text='Sheet this column belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='spreadsheet.sheet')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='sheet',
            name='spreadsheet',
            field=models.ForeignKey(help_text='Spreadsheet this sheet belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='spreadsheet.spreadsheet'),
        ),
        migrations.CreateModel(
            name='PatternJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('step_cursor', models.IntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=50, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pattern_jobs', to=settings.AUTH_USER_MODEL)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='spreadsheet.workflowpattern')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_jobs', to='spreadsheet.sheet')),
                ('spreadsheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_jobs', to='spreadsheet.spreadsheet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CellDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('from_cell', models.ForeignKey(help_text='Formula cell that depends on another cell', on_delete=django.db.models.deletion.CASCADE, related_name='formula_dependencies', to='spreadsheet.cell')),
                ('to_cell', models.ForeignKey(help_text='Referenced cell that a formula depends on', on_delete=django.db.models.deletion.CASCADE, related_name='formula_dependents', to='spreadsheet.cell')),
            ],
        ),
        migrations.AddField(
            model_name='cell',
            name='column',
            field=models.ForeignKey(help_text='Column this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheet.sheetcolumn'),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(help_text='Row this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheet.sheetrow'),
        ),
        migrations.AddField(
            model_name='cell',
            name='sheet',
            field=models.ForeignKey(help_text='Sheet this cell belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='spreadsheet.sheet'),
        ),
        migrations.CreateModel(
            name='WorkflowPatternStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('params', models.JSONField(default=dict)),
                ('disabled', models.BooleanField(default=False)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='spreadsheet.workflowpattern')),
            ],
            options={
                'ordering': ['seq'],
                'indexes': [models.Index(fields=['pattern', 'seq'], name='spreadsheet_pattern_e84f24_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='workflowpatternstep',
            constraint=models.UniqueConstraint(fields=('pattern', 'seq'), name='unique_pattern_step_seq'),
        ),
        migrations.AddIndex(
            model_name='workflowpattern',
            index=models.Index(fields=['owner', 'is_archived'], name='spreadsheet_owner_i_9e0904_idx'),
        ),
        migrations.AddIndex(
            model_name='spreadsheethighlight',
            index=models.Index(fields=['sheet', 'scope'], name='spreadsheet_sheet_i_d9fc8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='spreadsheethighlight',
            constraint=models.UniqueConstraint(fields=('sheet', 'scope', 'row_index', 'col_index'), name='unique_sheet_highlight_scope_position'),
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['project', 'is_deleted'], name='spreadsheet_project_f4f9c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='spreadsheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('project', 'name'), name='unique_spreadsheet_name_per_project_active'),
        ),
        migrations.AddIndex(
            model_name='sheetstructureoperation',
            index=models.Index(fields=['sheet', 'op_type'], name='spreadsheet_sheet_i_b2bbc3_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetstructureoperation',
            index=models.Index(fields=['sheet', 'is_reverted'], name='spreadsheet_sheet_i_538d94_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'is_deleted'], name='spreadsheet_sheet_i_043f92_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetrow',
            index=models.Index(fields=['sheet', 'position'], name='spreadsheet_sheet_i_f294a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetrow',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'position'), name='unique_row_position_per_sheet_active'),
        ),
        migrations.AddConstraint(
            model_name='sheetrow',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='sheetrow_position_non_negative'),
        ),
        migrations.AddIndex(
            model_name='sheetcolumn',
            index=models.Index(fields=['sheet', 'is_deleted'], name='spreadsheet_sheet_i_8cfea6_idx'),
        ),
        migrations.AddIndex(
            model_name='sheetcolumn',
            index=models.Index(fields=['sheet', 'position'], name='spreadsheet_sheet_i_40b33e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'position'), name='unique_column_position_per_sheet_active'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolumn',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='sheetcolumn_position_non_negative'),
        ),
        migrations.AddIndex(
            model_name='sheet',
            index=models.Index(fields=['spreadsheet', 'is_deleted'], name='spreadsheet_spreads_6a2c03_idx'),
        ),
        migrations.AddIndex(
            model_name='sheet',
            index=models.Index(fields=['spreadsheet', 'position'], name='spreadsheet_spreads_9836c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('spreadsheet', 'name'), name='unique_sheet_name_per_spreadsheet_active'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('spreadsheet', 'position'), name='unique_sheet_position_per_spreadsheet_active'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='sheet_position_non_negative'),
        ),
        migrations.AddIndex(
            model_name='patternjob',
            index=models.Index(fields=['created_by', 'status'], name='spreadsheet_created_58d676_idx'),
        ),
        migrations.AddIndex(
            model_name='patternjob',
            index=models.Index(fields=['pattern', 'status'], name='spreadsheet_pattern_8c1b20_idx'),
        ),
        migrations.AddIndex(
            model_name='patternjob',
            index=models.Index(fields=['sheet', 'status'], name='spreadsheet_sheet_i_4f560a_idx'),
        ),
        migrations.AddIndex(
            model_name='celldependency',
            index=models.Index(fields=['to_cell', 'is_deleted'], name='spreadsheet_to_cell_1f9b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='celldependency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('from_cell', 'to_cell'), name='unique_cell_dependency_active'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['sheet', 'is_deleted'], name='spreadsheet_sheet_i_0f2f99_idx'),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['sheet', 'row', 'column'], name='spreadsheet_sheet_i_562091_idx'),
        ),
        migrations.AddConstraint(
            model_name='cell',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('sheet', 'row', 'column'), name='unique_cell_position_per_sheet_active'),
        ),
    ]
