# Generated by Django 4.2.23 on 2026-01-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spreadsheet',
            name='spreadsheet_owner_i_89c43e_idx',
        ),
        migrations.RemoveField(
            model_name='spreadsheet',
            name='owner',
        ),
    ]
