# Generated by Django 4.2.23 on 2026-02-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_add_cell_format'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spreadsheetcellformat',
            new_name='spreadsheet_sheet_i_c79485_idx',
            old_name='spreadsheet_cellformat_sheet_idx',
        ),
    ]
