# Generated by Django 4.2.23 on 2026-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0002_remove_spreadsheet_spreadsheet_owner_i_89c43e_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sheetcolumn',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='sheetrow',
            options={'ordering': ['position']},
        ),
        migrations.RemoveIndex(
            model_name='cell',
            name='spreadsheet_row_id_3d59cb_idx',
        ),
        migrations.AlterField(
            model_name='sheetcolumn',
            name='name',
            field=models.CharField(help_text="Name of the column (e.g., 'A', 'B', 'C', should be automatically generated in serialization)", max_length=200),
        ),
        migrations.AddIndex(
            model_name='cell',
            index=models.Index(fields=['sheet', 'row', 'column'], name='spreadsheet_sheet_i_562091_idx'),
        ),
        migrations.AddConstraint(
            model_name='sheet',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='sheet_position_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sheetcolumn',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='sheetcolumn_position_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sheetrow',
            constraint=models.CheckConstraint(check=models.Q(('position__gte', 0)), name='sheetrow_position_non_negative'),
        ),
    ]
