# Generated by Django 4.2.23 on 2026-01-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0005_cell_dependency'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='celldependency',
            new_name='spreadsheet_to_cell_1f9b73_idx',
            old_name='spreadsheet_to_cell_3a2b86_idx',
        ),
    ]
