# Generated by Django 4.2.23 on 2026-01-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0007_alter_cell_decimal_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='computed_type',
            field=models.CharField(choices=[('empty', 'Empty'), ('number', 'Number'), ('string', 'String'), ('boolean', 'Boolean'), ('error', 'Error')], default='empty', help_text='Computed result type for formula or raw input', max_length=20),
        ),
    ]
