# Generated by Django 4.2.23 on 2026-03-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0008_add_pivot_persistence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pivotconfig',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
