# Generated by Django 4.2.23 on 2026-02-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0010_workflow_patterns'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS spreadsheet_sheet_op_type_idx RENAME TO spreadsheet_sheet_i_b2bbc3_idx;",
            "ALTER INDEX IF EXISTS spreadsheet_sheet_i_b2bbc3_idx RENAME TO spreadsheet_sheet_op_type_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='sheetstructureoperation',
                    new_name='spreadsheet_sheet_i_b2bbc3_idx',
                    old_name='spreadsheet_sheet_op_type_idx',
                )
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS spreadsheet_sheet_is_reverted_idx RENAME TO spreadsheet_sheet_i_538d94_idx;",
            "ALTER INDEX IF EXISTS spreadsheet_sheet_i_538d94_idx RENAME TO spreadsheet_sheet_is_reverted_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='sheetstructureoperation',
                    new_name='spreadsheet_sheet_i_538d94_idx',
                    old_name='spreadsheet_sheet_is_reverted_idx',
                )
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS spreadsheet_owner_i_e92511_idx RENAME TO spreadsheet_owner_i_9e0904_idx;",
            "ALTER INDEX IF EXISTS spreadsheet_owner_i_9e0904_idx RENAME TO spreadsheet_owner_i_e92511_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='workflowpattern',
                    new_name='spreadsheet_owner_i_9e0904_idx',
                    old_name='spreadsheet_owner_i_e92511_idx',
                )
            ],
        ),
        migrations.RunSQL(
            "ALTER INDEX IF EXISTS spreadsheet_pattern_a128c3_idx RENAME TO spreadsheet_pattern_e84f24_idx;",
            "ALTER INDEX IF EXISTS spreadsheet_pattern_e84f24_idx RENAME TO spreadsheet_pattern_a128c3_idx;",
            state_operations=[
                migrations.RenameIndex(
                    model_name='workflowpatternstep',
                    new_name='spreadsheet_pattern_e84f24_idx',
                    old_name='spreadsheet_pattern_a128c3_idx',
                )
            ],
        ),
    ]
