# Generated by Django 4.2.23 on 2026-02-09 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0012_pattern_job'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='patternjob',
            new_name='spreadsheet_created_58d676_idx',
            old_name='spreadsheet_created_96ee1a_idx',
        ),
        migrations.RenameIndex(
            model_name='patternjob',
            new_name='spreadsheet_pattern_8c1b20_idx',
            old_name='spreadsheet_pattern_1dfd5b_idx',
        ),
        migrations.RenameIndex(
            model_name='patternjob',
            new_name='spreadsheet_sheet_i_4f560a_idx',
            old_name='spreadsheet_sheet_s_2a5292_idx',
        ),
    ]
