# Generated by Django 4.2.23 on 2026-02-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0014_spreadsheet_highlights'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='spreadsheethighlight',
            new_name='spreadsheet_sheet_i_d9fc8c_idx',
            old_name='spreadsheet_sheet__ac1c74_idx',
        ),
        migrations.AddField(
            model_name='spreadsheethighlight',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
