# Generated by Django 4.2.23 on 2026-03-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('report', '0001_initial'), ('report', '0002_initial')]

    initial = True

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience_type', models.CharField(choices=[('client', 'Client'), ('manager', 'Manager'), ('internal_team', 'Internal Team'), ('self', 'Self'), ('other', 'Other')], help_text='Who the report is intended for', max_length=30)),
                ('audience_details', models.TextField(blank=True, help_text='Optional audience details (required if audience type is other)')),
                ('audience_prompt_version', models.CharField(blank=True, help_text='Pinned prompt template version for this audience at creation time', max_length=50)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Structured context for the report: {reporting_period: {type, text, start_date?, end_date?}, situation, what_changed}')),
                ('outcome_summary', models.TextField(help_text='High-level, qualitative outcome summary')),
                ('narrative_explanation', models.TextField(blank=True, help_text='Optional narrative explanation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(help_text='The task that owns this report task (1:1 relationship)', on_delete=django.db.models.deletion.CASCADE, related_name='report_task', to='task.task')),
            ],
            options={
                'db_table': 'report_task',
            },
        ),
        migrations.CreateModel(
            name='ReportTaskKeyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveSmallIntegerField(help_text='Order of this action (1-6)')),
                ('action_text', models.CharField(help_text='Concise description of a key action taken', max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_task', models.ForeignKey(help_text='Parent report task', on_delete=django.db.models.deletion.CASCADE, related_name='key_actions', to='report.reporttask')),
            ],
            options={
                'db_table': 'report_task_key_action',
                'ordering': ['order_index', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='reporttaskkeyaction',
            constraint=models.UniqueConstraint(fields=('report_task', 'order_index'), name='uniq_report_task_key_action_order'),
        ),
        migrations.AddConstraint(
            model_name='reporttaskkeyaction',
            constraint=models.CheckConstraint(check=models.Q(('order_index__gte', 1), ('order_index__lte', 6)), name='check_report_task_key_action_order_range'),
        ),
    ]
