# Generated by Django 4.2.23 on 2026-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_convert_context_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttask',
            name='audience_type',
            field=models.CharField(choices=[('client', 'Client'), ('manager', 'Manager'), ('internal_team', 'Internal Team'), ('self', 'Self'), ('other', 'Other')], help_text='Who the report is intended for', max_length=30),
        ),
    ]
