# Generated by Django 4.2.23 on 2026-01-28 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0009_projectinvitation_approval_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackWorkspaceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('slack_team_id', models.CharField(help_text='The unique ID of the Slack Workspace (e.g., T123456).', max_length=50)),
                ('slack_team_name', models.CharField(help_text='The name of the Slack Workspace.', max_length=255)),
                ('encrypted_access_token', models.TextField(help_text='Encrypted Bot User OAuth Token.')),
                ('installer_slack_user_id', models.CharField(blank=True, help_text='Slack ID of the user who installed the app.', max_length=50, null=True)),
                ('default_channel_id', models.CharField(blank=True, help_text='Default Slack Channel ID to send notifications to (fallback).', max_length=50, null=True)),
                ('default_channel_name', models.CharField(blank=True, help_text='Name of the default channel (e.g., #general).', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this connection is currently active/enabled.')),
                ('organization', models.ForeignKey(help_text='The MediaJira organization this connection belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='slack_connections', to='core.organization')),
            ],
            options={
                'verbose_name': 'Slack Connection',
                'verbose_name_plural': 'Slack Connections',
                'unique_together': {('organization', 'slack_team_id')},
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_type', models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_STATUS_CHANGE', 'Task Status Change'), ('COMMENT_UPDATED', 'Comment Updated'), ('DEADLINE_REMINDER', 'Deadline Reminder')], default='TASK_STATUS_CHANGE', help_text=' The type of event to listen for.', max_length=50)),
                ('task_status', models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], help_text='Specific task status to filter by (only used if event_type is TASK_STATUS_CHANGE).', max_length=50, null=True)),
                ('slack_channel_id', models.CharField(blank=True, help_text="Specific channel ID. If empty, uses the connection's default channel.", max_length=50, null=True)),
                ('slack_channel_name', models.CharField(blank=True, help_text='Specific channel name.', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this notification preference is currently enabled.')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='slack_integration.slackworkspaceconnection')),
                ('project', models.ForeignKey(help_text='The MediaJira project this preference applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='slack_preferences', to='core.project')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'unique_together': {('connection', 'project', 'event_type', 'task_status', 'slack_channel_id')},
            },
        ),
    ]
