# Generated by Django 4.2.23 on 2026-02-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='event_type',
            field=models.CharField(choices=[('TASK_CREATED', 'Task Created'), ('TASK_STATUS_CHANGE', 'Task Status Change'), ('COMMENT_UPDATED', 'Comment Updated'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('DECISION_CREATED', 'Decision Created')], default='TASK_STATUS_CHANGE', help_text=' The type of event to listen for.', max_length=50),
        ),
    ]
