# Generated by Django 4.2.23 on 2025-08-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Reference to Task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='task.task'),
        ),
    ]
