# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0002_initial'),
        ('task', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Reference to Task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='task.task'),
        ),
        migrations.AddField(
            model_name='asset',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Reference to Team', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='core.team'),
        ),
        migrations.AlterUniqueTogether(
            name='reviewassignment',
            unique_together={('asset_id', 'user_id', 'role')},
        ),
        migrations.AlterUniqueTogether(
            name='assetversion',
            unique_together={('asset', 'version_number')},
        ),
    ]
