# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klaviyo_email_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_draft_status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('archived', 'Archived')], default='ready', help_text='EmailDraft status that will trigger this workflow.', max_length=32)),
                ('email_drafts', models.ManyToManyField(blank=True, help_text='Email drafts that can trigger this workflow when their status changes.', related_name='workflows', to='klaviyo.emaildraft')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(choices=[('draft_status_change', 'Draft Status Change')], default='draft_status_change', max_length=64)),
                ('trigger_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of data when the trigger fired.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('email_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='klaviyo.emaildraft')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='klaviyo.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KlaviyoImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('preview_url', models.URLField(max_length=1000)),
                ('scan_status', django_fsm.FSMField(choices=[('incoming', 'Incoming - File just uploaded'), ('scanning', 'Scanning - Virus scan in progress'), ('ready', 'Ready - File is safe and available'), ('infected', 'Infected - File contains virus/malware'), ('missing', 'Missing - File missing from storage'), ('error_scanning', 'ErrorScanning - Scanner error occurred')], default='incoming', max_length=20, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_klaviyo_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klaviyo Image',
                'verbose_name_plural': 'Klaviyo Images',
                'db_table': 'klaviyo_image',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(max_length=50)),
                ('content', models.JSONField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('email_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='klaviyo.emaildraft')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
