# Generated by Django 4.2.23 on 2025-11-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klaviyo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='email_drafts',
            field=models.ManyToManyField(blank=True, help_text='Email drafts that can trigger this workflow when their status changes.', related_name='workflows', to='klaviyo.emaildraft'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='trigger_draft_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('archived', 'Archived')], default='ready', help_text='EmailDraft status that will trigger this workflow.', max_length=32),
        ),
        migrations.AlterField(
            model_name='emaildraft',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('sent', 'Sent'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkflowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('trigger_type', models.CharField(choices=[('draft_status_change', 'Draft Status Change')], default='draft_status_change', max_length=64)),
                ('trigger_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of data when the trigger fired.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('email_draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='klaviyo.emaildraft')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='klaviyo.workflow')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
