# Generated by Django 4.2.23 on 2026-01-01 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('klaviyo', '0002_workflow_email_drafts_workflow_trigger_draft_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KlaviyoImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('storage_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('size_bytes', models.BigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('md5', models.CharField(max_length=32, unique=True)),
                ('preview_url', models.URLField(max_length=1000)),
                ('scan_status', django_fsm.FSMField(choices=[('incoming', 'Incoming - File just uploaded'), ('scanning', 'Scanning - Virus scan in progress'), ('ready', 'Ready - File is safe and available'), ('infected', 'Infected - File contains virus/malware'), ('missing', 'Missing - File missing from storage'), ('error_scanning', 'ErrorScanning - Scanner error occurred')], default='incoming', max_length=20, protected=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_klaviyo_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Klaviyo Image',
                'verbose_name_plural': 'Klaviyo Images',
                'db_table': 'klaviyo_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
