# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Human-readable workflow name', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the workflow's purpose")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current lifecycle status of the workflow', max_length=32)),
                ('version', models.IntegerField(default=1, help_text='Current version number for this workflow')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this workflow belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Project this workflow belongs to (optional for organization-global workflows)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.project')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('node_type', models.CharField(choices=[('start', 'Start'), ('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('action', 'Action'), ('condition', 'Condition'), ('approval', 'Approval'), ('delay', 'Delay'), ('end', 'End')], help_text='Category of this status node (to_do, in_progress, or done) - aligned with Jira Status Categories', max_length=32)),
                ('label', models.CharField(help_text="Human-readable label for this node (e.g., 'Manager Approval')", max_length=255)),
                ('color', models.CharField(blank=True, default='#6b7280', help_text="Color hex code for UI display (e.g., '#3b82f6', '#10b981')", max_length=32)),
                ('data', models.JSONField(blank=True, default=dict, help_text='\n        Flexible storage for node position and custom properties.\n        Aligned with Jira Status model - stores position and key-value properties.\n        Example structure:\n        {\n            "position": {"x": 100, "y": 200},  # Canvas position for visual editor\n            "properties": {                     # Custom properties (like Jira Status Properties)\n                "key1": "value1",\n                "key2": "value2"\n            }\n        }\n        ')),
                ('workflow', models.ForeignKey(help_text='The workflow this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('connection_type', models.CharField(choices=[('sequential', 'Sequential'), ('conditional', 'Conditional'), ('parallel', 'Parallel'), ('loop', 'Loop')], default='sequential', help_text='Type of connection (sequential, conditional, parallel)', max_length=32)),
                ('name', models.CharField(blank=True, help_text="Custom name for this transition (e.g., 'Start Work', 'Merge'). If not provided, defaults to 'Source → Target'", max_length=255, null=True)),
                ('condition_config', models.JSONField(blank=True, default=dict, help_text='\n        Configuration for conditional and loop connections.\n        \n        Conditional connection example:\n        {\n            "field": "budget.amount",\n            "operator": "greater_than",\n            "value": 10000,\n            "label": "Budget exceeds $10,000"\n        }\n        \n        Loop connection example:\n        {\n            "max_iterations": 100,\n            "loop_variable": "current_item",\n            "collection": "{{items}}",\n            "label": "For each item"\n        }\n        ')),
                ('priority', models.IntegerField(default=0, help_text='Priority for execution when multiple connections exist (higher = first)')),
                ('source_handle', models.CharField(choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left')], default='right', help_text='Which side of the source node the connection originates from', max_length=20)),
                ('target_handle', models.CharField(choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left')], default='left', help_text='Which side of the target node the connection connects to', max_length=20)),
                ('event_type', models.CharField(blank=True, choices=[('manual_transition', 'Manual Transition'), ('issue_created', 'Issue Created'), ('issue_updated', 'Issue Updated'), ('issue_commented', 'Issue Commented'), ('issue_assigned', 'Issue Assigned'), ('issue_resolved', 'Issue Resolved')], default='manual_transition', help_text='Event that triggers this transition (aligned with Jira Transition Events)', max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict, help_text='\n        Custom properties for this transition (key-value pairs).\n        Aligned with Jira\'s Transition Properties feature.\n        Example: {"approval_required": true, "notification_enabled": false}\n        ')),
                ('source_node', models.ForeignKey(help_text='The node where this connection starts', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflows.workflownode')),
                ('target_node', models.ForeignKey(help_text='The node where this connection ends', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflows.workflownode')),
                ('workflow', models.ForeignKey(help_text='The workflow this connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Connection',
                'verbose_name_plural': 'Workflow Connections',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version_number', models.IntegerField(help_text='Version number for this workflow definition')),
                ('name', models.CharField(help_text='Version-specific workflow name snapshot', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Version-specific description snapshot')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Status of this specific version', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured configuration for triggers, conditions and actions')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this workflow version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_versions', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(help_text='Logical workflow this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Version',
                'verbose_name_plural': 'Workflow Versions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_b9b61e_idx'), models.Index(fields=['workflow', '-created_at'], name='workflows_w_workflo_d65e3a_idx')],
                'unique_together': {('workflow', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule_type', models.CharField(choices=[('restrict_transition', 'Restrict Transition'), ('validate_details', 'Validate Details'), ('perform_actions', 'Perform Actions')], help_text='Category of rule - restrict, validate, or perform actions', max_length=32)),
                ('rule_subtype', models.CharField(choices=[('block_until_approval', 'Block transition until approval'), ('restrict_by_subtasks', 'Restrict based on status of subtasks'), ('restrict_from_all_users', 'Restrict from all users'), ('restrict_by_field_value', 'Restrict to when a field is a specific value'), ('restrict_by_previous_status', 'Restrict to when issue has been through a specific status'), ('restrict_by_user_status_update', "Restrict users who have previously updated an issue's status"), ('restrict_by_user_role', 'Restrict who can move an issue'), ('require_form_attached', 'Require an issue to have a form attached'), ('require_form_submission', 'Require form submission on an issue'), ('validate_field', 'Validate a field'), ('validate_previous_status', 'Validate that an issue has been through a specific status'), ('validate_parent_status', 'Validate that parent issues are in a specific status'), ('validate_user_permission', 'Validate that people have a specific permission'), ('show_screen', 'Show a screen'), ('assign_issue', 'Assign an issue'), ('copy_field_value', 'Copy the value of one field to another'), ('set_security_level', "Set an issue's security level"), ('trigger_webhook', 'Trigger a webhook'), ('update_field', 'Update an issue field')], help_text='Specific type of rule within the category', max_length=64)),
                ('name', models.CharField(blank=True, help_text='Optional custom name for this rule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this rule does')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='\n        Rule-specific configuration. Structure varies by rule_subtype.\n        \n        Examples:\n        \n        Block Until Approval:\n        {\n            "approver_role": "manager",\n            "timeout_hours": 24\n        }\n        \n        Validate Field:\n        {\n            "field_name": "priority",\n            "operator": "is_not_empty",\n            "error_message": "Priority must be set"\n        }\n        \n        Assign Issue:\n        {\n            "assign_to": "reporter",\n            "fallback_user_id": 123\n        }\n        ')),
                ('order', models.IntegerField(default=0, help_text='Execution order when multiple rules exist (lower = earlier)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('connection', models.ForeignKey(help_text='The connection this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.workflowconnection')),
            ],
            options={
                'verbose_name': 'Workflow Rule',
                'verbose_name_plural': 'Workflow Rules',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['connection', 'rule_type'], name='workflows_w_connect_849530_idx'), models.Index(fields=['connection', 'order'], name='workflows_w_connect_12f901_idx'), models.Index(fields=['connection', 'is_active'], name='workflows_w_connect_b6be26_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'node_type'], name='workflows_w_workflo_86c425_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'created_at'], name='workflows_w_workflo_d6ea27_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['workflow'], name='workflows_w_workflo_d6f7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['source_node'], name='workflows_w_source__2424b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['target_node'], name='workflows_w_target__45991c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['workflow', 'connection_type'], name='workflows_w_workflo_d1d782_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'status'], name='workflows_w_organiz_867754_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['created_by', 'status'], name='workflows_w_created_e9b9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', '-created_at'], name='workflows_w_organiz_163c75_idx'),
        ),
    ]
