# Generated by Django 4.2.23 on 2025-12-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_projectinvitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(help_text='Human-readable workflow name', max_length=255)),
                ('description', models.TextField(blank=True, help_text="Detailed description of the workflow's purpose")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this workflow is currently active and can be used')),
                ('version', models.IntegerField(default=1, help_text='Version number for workflow versioning support')),
                ('project', models.ForeignKey(blank=True, help_text='Project this workflow belongs to (optional for global workflows)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.project')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('node_type', models.CharField(choices=[('start', 'Start Node'), ('end', 'End Node'), ('action', 'Action Node'), ('condition', 'Condition Node'), ('approval', 'Approval Node'), ('delay', 'Delay Node')], help_text='Type of this node (start, action, condition, etc.)', max_length=32)),
                ('label', models.CharField(help_text="Human-readable label for this node (e.g., 'Manager Approval')", max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='\n        Flexible storage for node configuration and position.\n        Example structure:\n        {\n            "position": {"x": 100, "y": 200},  # Canvas position for visual editor\n            "config": {                         # Node-specific configuration\n                "action_type": "send_email",\n                "email_template": "welcome"\n            }\n        }\n        ')),
                ('workflow', models.ForeignKey(help_text='The workflow this node belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Node',
                'verbose_name_plural': 'Workflow Nodes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('connection_type', models.CharField(choices=[('sequential', 'Sequential'), ('conditional', 'Conditional'), ('parallel', 'Parallel'), ('loop', 'Loop')], default='sequential', help_text='Type of connection (sequential, conditional, parallel)', max_length=32)),
                ('condition_config', models.JSONField(blank=True, default=dict, help_text='\n        Configuration for conditional and loop connections.\n        \n        Conditional connection example:\n        {\n            "field": "budget.amount",\n            "operator": "greater_than",\n            "value": 10000,\n            "label": "Budget exceeds $10,000"\n        }\n        \n        Loop connection example:\n        {\n            "max_iterations": 100,\n            "loop_variable": "current_item",\n            "collection": "{{items}}",\n            "label": "For each item"\n        }\n        ')),
                ('priority', models.IntegerField(default=0, help_text='Priority for execution when multiple connections exist (higher = first)')),
                ('source_node', models.ForeignKey(help_text='The node where this connection starts', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflows.workflownode')),
                ('target_node', models.ForeignKey(help_text='The node where this connection ends', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflows.workflownode')),
                ('workflow', models.ForeignKey(help_text='The workflow this connection belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflows.workflow')),
            ],
            options={
                'verbose_name': 'Workflow Connection',
                'verbose_name_plural': 'Workflow Connections',
                'ordering': ['-priority', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'node_type'], name='workflows_w_workflo_86c425_idx'),
        ),
        migrations.AddIndex(
            model_name='workflownode',
            index=models.Index(fields=['workflow', 'created_at'], name='workflows_w_workflo_d6ea27_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['workflow'], name='workflows_w_workflo_d6f7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['source_node'], name='workflows_w_source__2424b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['target_node'], name='workflows_w_target__45991c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['workflow', 'connection_type'], name='workflows_w_workflo_d1d782_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['project', 'is_active'], name='workflows_w_project_95b751_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['is_active', '-created_at'], name='workflows_w_is_acti_327939_idx'),
        ),
    ]
