# Generated by Django 4.2.23 on 2025-12-20 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_rename_core_projec_email_abc123_idx_core_projec_email_45393c_idx_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version_number', models.IntegerField(help_text='Version number for this workflow definition')),
                ('name', models.CharField(help_text='Version-specific workflow name snapshot', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Version-specific description snapshot')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Status of this specific version', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured configuration for triggers, conditions and actions')),
            ],
            options={
                'verbose_name': 'Workflow Version',
                'verbose_name_plural': 'Workflow Versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='workflows_w_project_95b751_idx',
        ),
        migrations.RemoveIndex(
            model_name='workflow',
            name='workflows_w_is_acti_327939_idx',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='is_active',
        ),
        migrations.AddField(
            model_name='workflow',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this workflow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflow',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this workflow belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.organization'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current lifecycle status of the workflow', max_length=32),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project this workflow belongs to (optional for organization-global workflows)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.project'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='version',
            field=models.IntegerField(default=1, help_text='Current version number for this workflow'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'status'], name='workflows_w_organiz_867754_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['created_by', 'status'], name='workflows_w_created_e9b9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', '-created_at'], name='workflows_w_organiz_163c75_idx'),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this workflow version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflow_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workflowversion',
            name='workflow',
            field=models.ForeignKey(help_text='Logical workflow this version belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', 'status'], name='workflows_w_workflo_b9b61e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowversion',
            index=models.Index(fields=['workflow', '-created_at'], name='workflows_w_workflo_d65e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowversion',
            unique_together={('workflow', 'version_number')},
        ),
    ]
