# Generated by Django 4.2.23 on 2025-12-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflownode',
            name='color',
            field=models.CharField(blank=True, default='gray', help_text="Color identifier for UI display (e.g., 'blue', 'yellow', 'green')", max_length=32),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Flexible storage for node configuration and position.\n        Example structure:\n        {\n            "position": {"x": 100, "y": 200},  # Canvas position for visual editor\n            "category": "in_progress",          # Optional: status category (to_do, in_progress, done)\n            "config": {                         # Node-specific configuration\n                "action_type": "send_email",\n                "email_template": "welcome"\n            }\n        }\n        '),
        ),
        migrations.CreateModel(
            name='NodeTypeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.SlugField(help_text="Machine‑readable key for this node type, e.g. 'create_task'", max_length=64, unique=True)),
                ('name', models.CharField(help_text='Human‑readable node type name', max_length=128)),
                ('category', models.CharField(choices=[('TASK_MANAGEMENT', 'Task Management'), ('DRAFT_GENERATORS', 'Draft Generators'), ('CONTROL_FLOW', 'Control Flow'), ('ACTIONS', 'Actions')], help_text='High‑level category of this node type', max_length=32)),
                ('description', models.TextField(blank=True, help_text='Detailed description for editors and users')),
                ('icon', models.CharField(blank=True, help_text='Icon name or identifier used by frontend', max_length=64)),
                ('color', models.CharField(blank=True, help_text='Color token or hex code used by frontend', max_length=32)),
                ('input_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema describing the expected input payload of this node')),
                ('output_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema describing the output payload of this node')),
                ('config_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema used to validate the node configuration')),
                ('default_config', models.JSONField(blank=True, default=dict, help_text='Default configuration template for this node type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this node type is available for use')),
            ],
            options={
                'verbose_name': 'Node Type Definition',
                'verbose_name_plural': 'Node Type Definitions',
                'indexes': [models.Index(fields=['category', 'is_active'], name='workflows_n_categor_92651c_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule_type', models.CharField(choices=[('restrict_transition', 'Restrict Transition'), ('validate_details', 'Validate Details'), ('perform_actions', 'Perform Actions')], help_text='Category of rule - restrict, validate, or perform actions', max_length=32)),
                ('rule_subtype', models.CharField(choices=[('block_until_approval', 'Block transition until approval'), ('restrict_by_subtasks', 'Restrict based on status of subtasks'), ('restrict_from_all_users', 'Restrict from all users'), ('restrict_by_field_value', 'Restrict to when a field is a specific value'), ('restrict_by_previous_status', 'Restrict to when issue has been through a specific status'), ('restrict_by_user_status_update', "Restrict users who have previously updated an issue's status"), ('restrict_by_user_role', 'Restrict who can move an issue'), ('require_form_attached', 'Require an issue to have a form attached'), ('require_form_submission', 'Require form submission on an issue'), ('validate_field', 'Validate a field'), ('validate_previous_status', 'Validate that an issue has been through a specific status'), ('validate_parent_status', 'Validate that parent issues are in a specific status'), ('validate_user_permission', 'Validate that people have a specific permission'), ('show_screen', 'Show a screen'), ('assign_issue', 'Assign an issue'), ('copy_field_value', 'Copy the value of one field to another'), ('set_security_level', "Set an issue's security level"), ('trigger_webhook', 'Trigger a webhook'), ('update_field', 'Update an issue field')], help_text='Specific type of rule within the category', max_length=64)),
                ('name', models.CharField(blank=True, help_text='Optional custom name for this rule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this rule does')),
                ('configuration', models.JSONField(blank=True, default=dict, help_text='\n        Rule-specific configuration. Structure varies by rule_subtype.\n        \n        Examples:\n        \n        Block Until Approval:\n        {\n            "approver_role": "manager",\n            "timeout_hours": 24\n        }\n        \n        Validate Field:\n        {\n            "field_name": "priority",\n            "operator": "is_not_empty",\n            "error_message": "Priority must be set"\n        }\n        \n        Assign Issue:\n        {\n            "assign_to": "reporter",\n            "fallback_user_id": 123\n        }\n        ')),
                ('order', models.IntegerField(default=0, help_text='Execution order when multiple rules exist (lower = earlier)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this rule is currently active')),
                ('connection', models.ForeignKey(help_text='The connection this rule applies to', on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='workflows.workflowconnection')),
            ],
            options={
                'verbose_name': 'Workflow Rule',
                'verbose_name_plural': 'Workflow Rules',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['connection', 'rule_type'], name='workflows_w_connect_849530_idx'), models.Index(fields=['connection', 'order'], name='workflows_w_connect_12f901_idx'), models.Index(fields=['connection', 'is_active'], name='workflows_w_connect_b6be26_idx')],
            },
        ),
    ]
