# Generated by Django 4.2.23 on 2026-01-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_add_color_to_node_and_update_rule_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowconnection',
            name='event_type',
            field=models.CharField(blank=True, choices=[('manual_transition', 'Manual Transition'), ('issue_created', 'Issue Created'), ('issue_updated', 'Issue Updated'), ('issue_commented', 'Issue Commented'), ('issue_assigned', 'Issue Assigned'), ('issue_resolved', 'Issue Resolved')], default='manual_transition', help_text='Event that triggers this transition (aligned with Jira Transition Events)', max_length=64),
        ),
        migrations.AddField(
            model_name='workflowconnection',
            name='properties',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Custom properties for this transition (key-value pairs).\n        Aligned with Jira\'s Transition Properties feature.\n        Example: {"approval_required": true, "notification_enabled": false}\n        '),
        ),
        # source_handle and target_handle already exist in database, skipping AddField operations
        migrations.AlterField(
            model_name='workflownode',
            name='color',
            field=models.CharField(blank=True, default='#6b7280', help_text="Color hex code for UI display (e.g., '#3b82f6', '#10b981')", max_length=32),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='\n        Flexible storage for node position and custom properties.\n        Aligned with Jira Status model - stores position and key-value properties.\n        Example structure:\n        {\n            "position": {"x": 100, "y": 200},  # Canvas position for visual editor\n            "properties": {                     # Custom properties (like Jira Status Properties)\n                "key1": "value1",\n                "key2": "value2"\n            }\n        }\n        '),
        ),
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], help_text='Category of this status node (to_do, in_progress, or done) - aligned with Jira Status Categories', max_length=32),
        ),
    ]
