# Generated by Django 4.2.23 on 2026-01-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0004_workflowconnection_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowconnection',
            name='name',
            field=models.CharField(blank=True, help_text="Custom name for this transition (e.g., 'Start Work', 'Merge'). If not provided, defaults to 'Source → Target'", max_length=255, null=True),
        ),
    ]

