# Generated by Django 4.2.23 on 2026-01-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0005_workflowconnection_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NodeTypeDefinition',
        ),
    ]
