# Generated by Django 4.2.23 on 2026-01-03 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0006_remove_node_type_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('start', 'Start'), ('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], help_text='Category of this status node (to_do, in_progress, or done) - aligned with Jira Status Categories', max_length=32),
        ),
    ]
