# Generated by Django 4.2.23 on 2026-01-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_add_start_node_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowconnection',
            name='source_handle',
            field=models.CharField(choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left')], default='right', help_text='Which side of the source node the connection originates from', max_length=20),
        ),
        migrations.AddField(
            model_name='workflowconnection',
            name='target_handle',
            field=models.CharField(choices=[('top', 'Top'), ('right', 'Right'), ('bottom', 'Bottom'), ('left', 'Left')], default='left', help_text='Which side of the target node the connection connects to', max_length=20),
        ),
    ]
