# Generated by Django 4.2.23 on 2026-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_workflowconnection_source_handle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflownode',
            name='node_type',
            field=models.CharField(choices=[('start', 'Start'), ('to_do', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('action', 'Action'), ('condition', 'Condition'), ('approval', 'Approval'), ('delay', 'Delay'), ('end', 'End')], help_text='Category of this status node (to_do, in_progress, or done) - aligned with Jira Status Categories', max_length=32),
        ),
    ]
