# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='The title of the task', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, protected=True)),
                ('due_date', models.DateField(blank=True, help_text='The due date of the task', null=True)),
                ('type', models.CharField(choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution'), ('scaling', 'Scaling'), ('alert', 'Alert'), ('experiment', 'Experiment'), ('optimization', 'Optimization'), ('communication', 'Client Communication'), ('platform_policy_update', 'Platform Policy Update')], help_text='Chosen type of the task', max_length=50)),
                ('priority', models.CharField(choices=[('HIGHEST', 'Highest'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('LOWEST', 'Lowest')], default='MEDIUM', help_text='Priority level of the task', max_length=20)),
                ('anomaly_status', models.CharField(default='NORMAL', help_text='Anomaly status for the task', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Task start date', null=True)),
                ('is_subtask', models.BooleanField(default=False, editable=False, help_text='Whether this task is a subtask. Once True, cannot be changed back.')),
                ('order_in_project', models.IntegerField(default=0, help_text='Order of task within its project')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Task creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Task last update timestamp')),
                ('object_id', models.CharField(blank=True, help_text='Id of the linked model', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the linked model', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_approver', models.ForeignKey(help_text='The user who is currently reviewing the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_approve', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user who owns the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project that the task belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task')),
                ('user', models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(help_text='Uploaded file', max_length=500, upload_to='task/attachments/%Y/%m/%d/')),
                ('original_filename', models.CharField(help_text='Original filename before upload', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('checksum', models.CharField(blank=True, help_text='SHA-256 checksum of the file', max_length=64)),
                ('scan_status', django_fsm.FSMField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('clean', 'Clean'), ('infected', 'Infected'), ('error_scanning', 'Error Scanning')], default='pending', help_text='Virus scan status', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the file', on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'task_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('causes', 'Causes'), ('blocks', 'Blocks'), ('clones', 'Clones'), ('relates_to', 'Relates To')], help_text='Type of relationship', max_length=20)),
                ('source_task', models.ForeignKey(help_text='Source task in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='task.task')),
                ('target_task', models.ForeignKey(help_text='Target task in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='task.task')),
            ],
            options={
                'db_table': 'task_relations',
                'indexes': [models.Index(fields=['source_task', 'relationship_type'], name='task_relati_source__6eff97_idx'), models.Index(fields=['target_task', 'relationship_type'], name='task_relati_target__05e002_idx')],
                'unique_together': {('source_task', 'target_task', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_task', models.ForeignKey(help_text='Child task (subtask)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationship', to='task.task')),
                ('parent_task', models.ForeignKey(help_text='Parent task', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task')),
            ],
            options={
                'db_table': 'task_hierarchies',
                'indexes': [models.Index(fields=['parent_task'], name='task_hierar_parent__41f3ee_idx'), models.Index(fields=['child_task'], name='task_hierar_child_t_63e1b1_idx')],
                'unique_together': {('parent_task', 'child_task')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(help_text='Whether approved')),
                ('comment', models.TextField(blank=True, help_text='Reason for approval or rejection', null=True)),
                ('decided_time', models.DateTimeField(auto_now_add=True, help_text='Decision timestamp')),
                ('step_number', models.PositiveIntegerField(help_text='Approval step number')),
                ('approved_by', models.ForeignKey(help_text='Approver user', on_delete=django.db.models.deletion.PROTECT, related_name='task_approval_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='task.task')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('task', 'step_number')},
            },
        ),
    ]
