# Generated by Django 4.2.23 on 2025-08-18 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='The title of the task', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', django_fsm.FSMField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('LOCKED', 'Locked'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, protected=True)),
                ('due_date', models.DateField(blank=True, help_text='The due date of the task', null=True)),
                ('type', models.CharField(choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective')], help_text='Chosen type of the task', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='Id of the linked model', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the linked model', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('current_approver', models.ForeignKey(help_text='The user who is currently reviewing the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_to_approve', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='The user who owns the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='The project that the task belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(help_text='Whether approved')),
                ('comment', models.TextField(blank=True, help_text='Reason for approval or rejection', null=True)),
                ('decided_time', models.DateTimeField(auto_now_add=True, help_text='Decision timestamp')),
                ('step_number', models.PositiveIntegerField(help_text='Approval step number')),
                ('approved_by', models.ForeignKey(help_text='Approver user', on_delete=django.db.models.deletion.PROTECT, related_name='task_approval_records', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='approval_records', to='task.task')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('task', 'step_number')},
            },
        ),
    ]
