# Generated by Django 4.2.23 on 2025-08-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='object_id',
            field=models.CharField(blank=True, help_text='Id of the linked model', null=True),
        ),
    ]
