# Generated by Django 4.2.23 on 2026-03-02 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name for this approval chain (e.g. 'Buyer → Lead → Client')", max_length=100)),
                ('task_type', models.CharField(blank=True, choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution'), ('scaling', 'Scaling'), ('alert', 'Alert'), ('experiment', 'Experiment'), ('optimization', 'Optimization'), ('communication', 'Client Communication'), ('platform_policy_update', 'Platform Policy Update')], help_text='Task type this chain applies to. Leave blank to apply to all task types.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project this chain applies to. Leave blank to apply across all projects.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_chains', to='core.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='current_approval_step',
            field=models.PositiveIntegerField(blank=True, help_text='Current step number in the approval chain (1-based). Null if no chain is assigned.', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='approval_chain',
            field=models.ForeignKey(blank=True, help_text='The predefined approval chain assigned to this task (null = legacy single-approver mode)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task.approvalchain'),
        ),
        migrations.CreateModel(
            name='ApprovalChainStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Position of this step in the chain (1-based, e.g. 1 = Buyer, 2 = Lead, 3 = Client)')),
                ('approver', models.ForeignKey(help_text='User responsible for approving at this step', on_delete=django.db.models.deletion.CASCADE, related_name='approval_chain_steps', to=settings.AUTH_USER_MODEL)),
                ('chain', models.ForeignKey(help_text='The approval chain this step belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='task.approvalchain')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('chain', 'order')},
            },
        ),
    ]
