# Generated by Django 4.2.23 on 2025-10-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_task_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("budget", "Budget"),
                    ("asset", "Asset"),
                    ("retrospective", "Retrospective"),
                    ("report", "Report"),
                ],
                help_text="Chosen type of the task",
                max_length=50,
            ),
        ),
    ]
