# Generated by Django 4.2

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_task_draft_payload"),
        ("meetings", "0002_meetingactionitem"),
    ]

    # Deprecated lineage snapshot branch.
    # Keep migration id for graph compatibility, but no-op to avoid
    # duplicate `origin_action_item_id` column with 0006_task_origin_action_item.
    operations = []
