# Generated by Django 4.2.23 on 2026-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_draft_payload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrecord',
            options={'ordering': ['revision_round', 'step_number']},
        ),
        migrations.AlterUniqueTogether(
            name='approvalrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='has_rejection_history',
            field=models.BooleanField(default=False, help_text='Whether this task had prior rejections at time of this record'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='resubmitted_after_reject',
            field=models.BooleanField(default=False, help_text='Whether this record was created after a resubmission'),
        ),
        migrations.AddField(
            model_name='approvalrecord',
            name='revision_round',
            field=models.PositiveIntegerField(default=0, help_text='Revision round this approval record belongs to'),
        ),
        migrations.AddField(
            model_name='task',
            name='revision_round',
            field=models.PositiveIntegerField(default=0, help_text='Tracks how many times this task has been resubmitted after rejection'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalrecord',
            unique_together={('task', 'step_number', 'revision_round')},
        ),
    ]
