# Generated by Django 4.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0004_task_draft_payload"),
        ("meetings", "0002_meetingactionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="origin_action_item_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="MeetingActionItem id at conversion time (immutable snapshot)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="origin_action_item_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Action item title at conversion time (immutable snapshot)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="origin_meeting_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Meeting id at conversion time (immutable snapshot)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="origin_meeting_title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Meeting title at conversion time (immutable snapshot)",
                max_length=255,
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(origin_action_item_id__isnull=False),
                fields=("origin_action_item_id",),
                name="task_unique_origin_action_item_id",
            ),
        ),
    ]
