# Generated by Django 4.2.23 on 2025-12-16 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0005_taskcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution')], help_text='Chosen type of the task', max_length=50),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(help_text='Associated Task', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(help_text='User who made the comment', on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
