# Generated by Django 4.2.23 on 2026-01-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_taskattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('causes', 'Causes'), ('blocks', 'Blocks'), ('clones', 'Clones'), ('relates_to', 'Relates To')], help_text='Type of relationship', max_length=20)),
                ('source_task', models.ForeignKey(help_text='Source task in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='task.task')),
                ('target_task', models.ForeignKey(help_text='Target task in the relationship', on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='task.task')),
            ],
            options={
                'db_table': 'task_relations',
                'indexes': [models.Index(fields=['source_task', 'relationship_type'], name='task_relati_source__6eff97_idx'), models.Index(fields=['target_task', 'relationship_type'], name='task_relati_target__05e002_idx')],
                'unique_together': {('source_task', 'target_task', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='TaskHierarchy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_task', models.ForeignKey(help_text='Child task (subtask)', on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationship', to='task.task')),
                ('parent_task', models.ForeignKey(help_text='Parent task', on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='task.task')),
            ],
            options={
                'db_table': 'task_hierarchies',
                'indexes': [models.Index(fields=['parent_task'], name='task_hierar_parent__41f3ee_idx'), models.Index(fields=['child_task'], name='task_hierar_child_t_63e1b1_idx')],
                'unique_together': {('parent_task', 'child_task')},
            },
        ),
    ]
