# Generated by Django 4.2.23 on 2026-01-05 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_add_timestamp_fields'),
        ('task', '0010_change_parent_task_to_cascade'),
    ]

    operations = [
    ]
