# Generated by Django 4.2.23 on 2026-01-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_merge_20260105_0916'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_priority_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_proj_due_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_updated_at_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='task_created_at_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='order_in_project',
            field=models.IntegerField(default=0, help_text='Order of task within its project'),
        ),
    ]
