# Generated by Django 4.2.23 on 2026-01-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_remove_task_task_proj_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution'), ('scaling', 'Scaling')], help_text='Chosen type of the task', max_length=50),
        ),
    ]
