# Generated by Django 4.2.23 on 2026-01-10 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0013_add_anomaly_status_state'),
        ('task', '0013_alter_task_type'),
    ]

    operations = [
    ]
