# Generated by Django 4.2.23 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0014_merge_20260110_0420"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("budget", "Budget"),
                    ("asset", "Asset"),
                    ("retrospective", "Retrospective"),
                    ("report", "Report"),
                    ("execution", "Execution"),
                    ("scaling", "Scaling"),
                    ("alert", "Alert"),
                ],
                help_text="Chosen type of the task",
                max_length=50,
            ),
        ),
    ]
