# Generated by Django 4.2.23 on 2026-01-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_merge_final_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('budget', 'Budget'), ('asset', 'Asset'), ('retrospective', 'Retrospective'), ('report', 'Report'), ('execution', 'Execution'), ('scaling', 'Scaling'), ('experiment', 'Experiment'), ('communication', 'Client Communication')], help_text='Chosen type of the task', max_length=50),
        ),
    ]
