# Generated by Django 4.2.23 on 2026-01-12 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0019_alter_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.CharField(
                choices=[
                    ("budget", "Budget"),
                    ("asset", "Asset"),
                    ("retrospective", "Retrospective"),
                    ("report", "Report"),
                    ("execution", "Execution"),
                    ("scaling", "Scaling"),
                    ("alert", "Alert"),
                    ("experiment", "Experiment"),
                    ("communication", "Client Communication"),
                ],
                help_text="Chosen type of the task",
                max_length=50,
            ),
        ),
    ]
