# Generated by Django 4.2.23 on 2026-02-11

from django.db import migrations


def delete_report_tasks(apps, schema_editor):
    Task = apps.get_model("task", "Task")
    Task.objects.filter(type="report").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0022_add_platform_policy_update_task_type"),
    ]

    operations = [
        migrations.RunPython(delete_report_tasks, migrations.RunPython.noop),
    ]
