#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

curDir=$(pwd)

# Frontend Part
echo "====start scan frontend code===="
cd ${curDir}/frontend

echo "====start lint-stage===="
npx lint-staged

echo "pre-commit huscky run finish"
