#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

curDir=$(pwd)

# Frontend Part
# Option 1: run inbuilt scripts
#cd ${curDir}/frontend && npm run lint && npm run build && npm test && npm audit fix 

# Option 2: run customised configuration
echo "start scan frontend code"
cd ${curDir}/frontend
npx lint-staged
# npm audit fix
# npm test
echo "frontend code scan finish"

# Backend Part
echo "start scan backend code"
cd ${curDir}/backend
# mypy .
# bandit -r 
# safety scan -r requirements.txt
echo "start scan backend finish"


echo "pre-commit huscky run finish"
