# Generated by Django 4.2.23 on 2026-02-18 09:55

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_verified', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verification_token', models.CharField(blank=True, max_length=100, null=True)),
                ('google_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('google_registered', models.BooleanField(default=False)),
                ('password_set', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('email_domain', models.CharField(blank=True, help_text="Email domain for SSO organization matching (e.g., 'agencyX.com')", max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_organizations', to='core.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Project description (optional)', null=True)),
                ('project_type', models.JSONField(blank=True, default=list, help_text="List of project types: ['paid_social', 'paid_search', 'programmatic', 'influencer_ugc', 'cross_channel', 'performance', 'brand_campaigns', 'app_acquisition']")),
                ('work_model', models.JSONField(blank=True, default=list, help_text="List of work models: ['solo_buyer', 'small_team', 'multi_team', 'external_agency']")),
                ('advertising_platforms', models.JSONField(blank=True, default=list, help_text="List of advertising platforms (e.g., ['meta', 'google_ads', 'tiktok', 'linkedin', 'snapchat', 'twitter', 'pinterest', 'programmatic_dsp', 'reddit'])")),
                ('objectives', models.JSONField(blank=True, default=list, help_text="Multi-select objectives list (e.g., ['awareness', 'consideration'])")),
                ('kpis', models.JSONField(blank=True, default=dict, help_text="Structured KPI configuration: {'ctr': {'target': 0.02, 'suggested_by': ['awareness']}}")),
                ('target_kpi_value', models.CharField(blank=True, help_text="Target KPI value as text (e.g., 'CPA target: $65', 'ROAS target: 3.5')", max_length=200, null=True)),
                ('budget_management_type', models.CharField(blank=True, choices=[('single_consolidated', 'Single consolidated budget'), ('platform_specific', 'Platform-specific budgets'), ('campaign_level', 'Campaign-level budgets (recommended)'), ('client_mandated', 'Client-mandated budget structure')], help_text='How budgets are managed in this project', max_length=50, null=True)),
                ('total_monthly_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Total expected monthly budget (used for pacing dashboards and alerts)', max_digits=15, null=True)),
                ('pacing_enabled', models.BooleanField(default=False, help_text='Whether pacing insights and alerts are enabled')),
                ('budget_config', models.JSONField(blank=True, default=dict, help_text='Additional budget configuration (pacing settings, alerts, etc.)')),
                ('primary_audience_type', models.CharField(blank=True, choices=[('broad_open', 'Broad / Open Targeting'), ('interests_based', 'Interests-Based Audience'), ('lookalike_similar', 'Lookalike / Similar Audiences'), ('remarketing', 'Remarketing'), ('custom_crm', 'Custom CRM-Based Audiences'), ('geographic', 'Geographic Targeting')], help_text='Primary target audience type', max_length=50, null=True)),
                ('audience_targeting', models.JSONField(blank=True, default=dict, help_text='Audience targeting configuration: {target_regions: [...], geographic_details: {...}, etc.}')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='Project owner (defaults to creator, can be changed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, null=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_teams', to='core.team')),
            ],
            options={
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('module', models.CharField(choices=[('ASSET', 'Asset'), ('CAMPAIGN', 'Campaign'), ('BUDGET_REQUEST', 'Budget Request'), ('BUDGET_POOL', 'Budget Pool'), ('BUDGET_ESCALATION', 'Budget Escalation')], max_length=20)),
                ('action', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit'), ('APPROVE', 'Approve'), ('DELETE', 'Delete'), ('EXPORT', 'Export')], max_length=20)),
            ],
            options={
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='AdChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_channels', to='core.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_project',
            field=models.ForeignKey(blank=True, help_text='The currently active project for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.project'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.organization'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role_id', models.IntegerField(choices=[(2, 'Team Leader'), (3, 'Member')], default=3, help_text='Role of the user in this team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(default=10, help_text='Lower number = higher privilege')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this role belongs to. Leave empty for super admin roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.organization')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(default='member', help_text="Role of the user in this project (e.g., 'owner', 'member', 'viewer')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'project')},
            },
        ),
        migrations.CreateModel(
            name='ProjectInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('role', models.CharField(default='member', help_text="Role the user will have in the project (e.g., 'owner', 'member', 'viewer')", max_length=50)),
                ('approved', models.BooleanField(default=False, help_text='Whether the invitation has been approved by a project owner')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When the invitation was approved', null=True)),
                ('token', models.CharField(help_text='Unique token for accepting the invitation', max_length=64, unique=True)),
                ('accepted', models.BooleanField(default=False, help_text='Whether the invitation has been accepted')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='When the invitation was accepted', null=True)),
                ('expires_at', models.DateTimeField(help_text='When the invitation expires')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Owner who approved the invitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project the user is being invited to', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'accepted'], name='core_projec_email_45393c_idx'), models.Index(fields=['token'], name='core_projec_token_16853f_idx')],
                'unique_together': {('email', 'project', 'accepted')},
            },
        ),
    ]
