# Generated by Django 4.2.23 on 2025-08-18 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_approval', '0003_alter_budgetrequest_task'),
        ('asset', '0002_alter_asset_task'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
