# Generated by Django 4.2.23 on 2025-08-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_task_adchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('ASSET', 'Asset'), ('CAMPAIGN', 'Campaign'), ('BUDGET_REQUEST', 'Budget Request'), ('BUDGET_POOL', 'Budget Pool'), ('BUDGET_ESCALATION', 'Budget Escalation')], max_length=20),
        ),
    ]
