# Generated by Django 5.2.6 on 2025-10-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_task'),
    ]

    operations = [
    ]
