# Generated by Django 4.2.23 on 2025-11-25 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_organization_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_project',
            field=models.ForeignKey(blank=True, help_text='The currently active project for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_users', to='core.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='advertising_platforms',
            field=models.JSONField(blank=True, default=list, help_text="List of advertising platforms (e.g., ['meta', 'google_ads', 'tiktok', 'linkedin', 'snapchat', 'twitter', 'pinterest', 'programmatic_dsp', 'reddit'])"),
        ),
        migrations.AddField(
            model_name='project',
            name='audience_targeting',
            field=models.JSONField(blank=True, default=dict, help_text='Audience targeting configuration: {target_regions: [...], geographic_details: {...}, etc.}'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_config',
            field=models.JSONField(blank=True, default=dict, help_text='Additional budget configuration (pacing settings, alerts, etc.)'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_management_type',
            field=models.CharField(blank=True, choices=[('single_consolidated', 'Single consolidated budget'), ('platform_specific', 'Platform-specific budgets'), ('campaign_level', 'Campaign-level budgets (recommended)'), ('client_mandated', 'Client-mandated budget structure')], help_text='How budgets are managed in this project', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Project description (optional)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='kpis',
            field=models.JSONField(blank=True, default=dict, help_text="KPI configuration: {main_kpi: 'cpa', kpi_options: [...]}. Main KPI is selected based on primary_objective"),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Project owner (defaults to creator, can be changed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='pacing_enabled',
            field=models.BooleanField(default=False, help_text='Whether pacing insights and alerts are enabled'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_audience_type',
            field=models.CharField(blank=True, choices=[('broad_open', 'Broad / Open Targeting'), ('interests_based', 'Interests-Based Audience'), ('lookalike_similar', 'Lookalike / Similar Audiences'), ('remarketing', 'Remarketing'), ('custom_crm', 'Custom CRM-Based Audiences'), ('geographic', 'Geographic Targeting')], help_text='Primary target audience type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_objective',
            field=models.CharField(blank=True, choices=[('awareness', 'Awareness'), ('consideration', 'Consideration'), ('conversion', 'Conversion'), ('retention_loyalty', 'Retention / Loyalty')], help_text='Primary objective of the campaign', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.JSONField(blank=True, default=list, help_text="List of project types: ['paid_social', 'paid_search', 'programmatic', 'influencer_ugc', 'cross_channel', 'performance', 'brand_campaigns', 'app_acquisition']"),
        ),
        migrations.AddField(
            model_name='project',
            name='target_kpi_value',
            field=models.CharField(blank=True, help_text="Target KPI value as text (e.g., 'CPA target: $65', 'ROAS target: 3.5')", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total expected monthly budget (used for pacing dashboards and alerts)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='work_model',
            field=models.JSONField(blank=True, default=list, help_text="List of work models: ['solo_buyer', 'small_team', 'multi_team', 'external_agency']"),
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.CharField(default='member', help_text="Role of the user in this project (e.g., 'owner', 'member', 'viewer')", max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'project')},
            },
        ),
    ]
