# Generated by Django 4.2.23 on 2025-12-16 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectinvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='projectinvitation',
            new_name='core_projec_email_45393c_idx',
            old_name='core_projec_email_abc123_idx',
        ),
        migrations.RenameIndex(
            model_name='projectinvitation',
            new_name='core_projec_token_16853f_idx',
            old_name='core_projec_token_abc123_idx',
        ),
    ]
