# Generated by Django 4.2.23 on 2026-02-04 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_avatar_to_customuser'),
        ('core', '0012_populate_default_roles'),
    ]

    operations = [
    ]
