import logging
from types import SimpleNamespace

from django.db import transaction
from django.utils import timezone
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from miro.serializers import (
    BoardCreateSerializer,
    BoardItemCreateSerializer,
    BoardRevisionCreateSerializer,
)

logger = logging.getLogger(__name__)


def _build_board_title(session, workflow_run):
    user_timezone = getattr(getattr(session.user, "preferences", None), "timezone", None)
    current_time = timezone.now()
    if user_timezone:
        try:
            current_time = timezone.localtime(current_time, ZoneInfo(user_timezone))
        except ZoneInfoNotFoundError:
            current_time = timezone.localtime(current_time)
    else:
        current_time = timezone.localtime(current_time)

    timestamp = current_time.strftime("%Y-%m-%d %H:%M")
    return f"Agent Miro Board {timestamp}"


def _materialize_snapshot_ids(snapshot, id_map):
    items = snapshot.get("items", [])

    materialized_items = []
    for item in items:
        source_id = str(item.get("id"))
        parent_source_id = item.get("parent_item_id")
        materialized = {
            **item,
            "id": id_map[source_id],
            "parent_item_id": id_map.get(str(parent_source_id)) if parent_source_id else None,
        }
        materialized_items.append(materialized)

    return {
        "viewport": snapshot.get("viewport", {}),
        "items": materialized_items,
    }


@transaction.atomic
def create_board_from_snapshot(*, project, session, workflow_run, snapshot):
    board_title = _build_board_title(session, workflow_run)
    logger.info(
        "Creating Miro board from snapshot for workflow_run=%s title=%s item_count=%s",
        getattr(workflow_run, "id", None),
        board_title,
        len(snapshot.get("items", [])),
    )

    request = SimpleNamespace(user=session.user)
    board_serializer = BoardCreateSerializer(
        data={
            "project_id": project.id,
            "title": board_title,
            "viewport": snapshot.get("viewport", {}),
        },
        context={"request": request},
    )
    board_serializer.is_valid(raise_exception=True)
    board = board_serializer.save()

    source_to_created_id = {}
    for item_data in sorted(
        snapshot.get("items", []),
        key=lambda item: (0 if not item.get("parent_item_id") else 1, item.get("z_index", 0)),
    ):
        source_id = str(item_data["id"])
        parent_item_id = item_data.get("parent_item_id")
        item_serializer = BoardItemCreateSerializer(
            data={
                "type": item_data["type"],
                "parent_item_id": source_to_created_id.get(str(parent_item_id)) if parent_item_id else None,
                "x": item_data["x"],
                "y": item_data["y"],
                "width": item_data["width"],
                "height": item_data["height"],
                "rotation": item_data.get("rotation"),
                "style": item_data.get("style", {}),
                "content": item_data.get("content", ""),
                "z_index": item_data["z_index"],
            },
            context={"request": request, "board": board},
        )
        item_serializer.is_valid(raise_exception=True)
        board_item = item_serializer.save()
        source_to_created_id[source_id] = str(board_item.id)

    persisted_snapshot = _materialize_snapshot_ids(snapshot, source_to_created_id)
    revision_serializer = BoardRevisionCreateSerializer(
        data={
            "snapshot": persisted_snapshot,
            "note": "Generated by agent workflow",
        },
        context={"board": board},
    )
    revision_serializer.is_valid(raise_exception=True)
    revision_serializer.save()

    return board, persisted_snapshot
